/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Questioner.Web
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  ActivateTemplateQuestionerTemplateRequest,
  CreateQuestionerTemplateRequest,
  CreateQuestionerTemplateResponse,
  DeleteInactiveQuestionerTemplatesResponse,
  ListQuestionerTemplatesResponse,
  QuestionerTemplateDto,
  UpdateQuestionerTemplateRequest,
} from '.././models';

import { questionerInstance } from '../../../mutators/questionerMutator';

export const questionerWebQuestionerTemplatesActivateTemplate = (
  externalId: string,
  activateTemplateQuestionerTemplateRequest: ActivateTemplateQuestionerTemplateRequest
) => {
  return questionerInstance<void>({
    url: `/api/v1/questionerTemplates/ActivateTemplate/${externalId}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: activateTemplateQuestionerTemplateRequest,
  });
};

export const getQuestionerWebQuestionerTemplatesActivateTemplateMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof questionerWebQuestionerTemplatesActivateTemplate>>,
    TError,
    { externalId: string; data: ActivateTemplateQuestionerTemplateRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof questionerWebQuestionerTemplatesActivateTemplate>>,
  TError,
  { externalId: string; data: ActivateTemplateQuestionerTemplateRequest },
  TContext
> => {
  const mutationKey = ['questionerWebQuestionerTemplatesActivateTemplate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof questionerWebQuestionerTemplatesActivateTemplate>>,
    { externalId: string; data: ActivateTemplateQuestionerTemplateRequest }
  > = (props) => {
    const { externalId, data } = props ?? {};

    return questionerWebQuestionerTemplatesActivateTemplate(externalId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type QuestionerWebQuestionerTemplatesActivateTemplateMutationResult = NonNullable<
  Awaited<ReturnType<typeof questionerWebQuestionerTemplatesActivateTemplate>>
>;
export type QuestionerWebQuestionerTemplatesActivateTemplateMutationBody =
  ActivateTemplateQuestionerTemplateRequest;
export type QuestionerWebQuestionerTemplatesActivateTemplateMutationError = void;

export const useQuestionerWebQuestionerTemplatesActivateTemplate = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof questionerWebQuestionerTemplatesActivateTemplate>>,
      TError,
      { externalId: string; data: ActivateTemplateQuestionerTemplateRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof questionerWebQuestionerTemplatesActivateTemplate>>,
  TError,
  { externalId: string; data: ActivateTemplateQuestionerTemplateRequest },
  TContext
> => {
  const mutationOptions =
    getQuestionerWebQuestionerTemplatesActivateTemplateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Create a new QuestionerTemplate (auto-tenant scoped)
 */
export const questionerWebQuestionerTemplatesCreate = (
  createQuestionerTemplateRequest: CreateQuestionerTemplateRequest,
  signal?: AbortSignal
) => {
  return questionerInstance<CreateQuestionerTemplateResponse>({
    url: `/api/v1/questionerTemplates`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createQuestionerTemplateRequest,
    signal,
  });
};

export const getQuestionerWebQuestionerTemplatesCreateMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof questionerWebQuestionerTemplatesCreate>>,
    TError,
    { data: CreateQuestionerTemplateRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof questionerWebQuestionerTemplatesCreate>>,
  TError,
  { data: CreateQuestionerTemplateRequest },
  TContext
> => {
  const mutationKey = ['questionerWebQuestionerTemplatesCreate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof questionerWebQuestionerTemplatesCreate>>,
    { data: CreateQuestionerTemplateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return questionerWebQuestionerTemplatesCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type QuestionerWebQuestionerTemplatesCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof questionerWebQuestionerTemplatesCreate>>
>;
export type QuestionerWebQuestionerTemplatesCreateMutationBody = CreateQuestionerTemplateRequest;
export type QuestionerWebQuestionerTemplatesCreateMutationError = void;

/**
 * @summary Create a new QuestionerTemplate (auto-tenant scoped)
 */
export const useQuestionerWebQuestionerTemplatesCreate = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof questionerWebQuestionerTemplatesCreate>>,
      TError,
      { data: CreateQuestionerTemplateRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof questionerWebQuestionerTemplatesCreate>>,
  TError,
  { data: CreateQuestionerTemplateRequest },
  TContext
> => {
  const mutationOptions = getQuestionerWebQuestionerTemplatesCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const questionerWebQuestionerTemplatesDelete = (externalId: string) => {
  return questionerInstance<void>({
    url: `/api/v1/questionerTemplates/${externalId}`,
    method: 'DELETE',
  });
};

export const getQuestionerWebQuestionerTemplatesDeleteMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof questionerWebQuestionerTemplatesDelete>>,
    TError,
    { externalId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof questionerWebQuestionerTemplatesDelete>>,
  TError,
  { externalId: string },
  TContext
> => {
  const mutationKey = ['questionerWebQuestionerTemplatesDelete'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof questionerWebQuestionerTemplatesDelete>>,
    { externalId: string }
  > = (props) => {
    const { externalId } = props ?? {};

    return questionerWebQuestionerTemplatesDelete(externalId);
  };

  return { mutationFn, ...mutationOptions };
};

export type QuestionerWebQuestionerTemplatesDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof questionerWebQuestionerTemplatesDelete>>
>;

export type QuestionerWebQuestionerTemplatesDeleteMutationError = void;

export const useQuestionerWebQuestionerTemplatesDelete = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof questionerWebQuestionerTemplatesDelete>>,
      TError,
      { externalId: string },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof questionerWebQuestionerTemplatesDelete>>,
  TError,
  { externalId: string },
  TContext
> => {
  const mutationOptions = getQuestionerWebQuestionerTemplatesDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const questionerWebQuestionerTemplatesGetById = (
  externalId: string,
  signal?: AbortSignal
) => {
  return questionerInstance<QuestionerTemplateDto>({
    url: `/api/v1/questionerTemplates/${externalId}`,
    method: 'GET',
    signal,
  });
};

export const getQuestionerWebQuestionerTemplatesGetByIdQueryKey = (externalId?: string) => {
  return [`/api/v1/questionerTemplates/${externalId}`] as const;
};

export const getQuestionerWebQuestionerTemplatesGetByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof questionerWebQuestionerTemplatesGetById>>,
  TError = void,
>(
  externalId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof questionerWebQuestionerTemplatesGetById>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getQuestionerWebQuestionerTemplatesGetByIdQueryKey(externalId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof questionerWebQuestionerTemplatesGetById>>
  > = ({ signal }) => questionerWebQuestionerTemplatesGetById(externalId, signal);

  return { queryKey, queryFn, enabled: !!externalId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof questionerWebQuestionerTemplatesGetById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type QuestionerWebQuestionerTemplatesGetByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof questionerWebQuestionerTemplatesGetById>>
>;
export type QuestionerWebQuestionerTemplatesGetByIdQueryError = void;

export function useQuestionerWebQuestionerTemplatesGetById<
  TData = Awaited<ReturnType<typeof questionerWebQuestionerTemplatesGetById>>,
  TError = void,
>(
  externalId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof questionerWebQuestionerTemplatesGetById>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof questionerWebQuestionerTemplatesGetById>>,
          TError,
          Awaited<ReturnType<typeof questionerWebQuestionerTemplatesGetById>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useQuestionerWebQuestionerTemplatesGetById<
  TData = Awaited<ReturnType<typeof questionerWebQuestionerTemplatesGetById>>,
  TError = void,
>(
  externalId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof questionerWebQuestionerTemplatesGetById>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof questionerWebQuestionerTemplatesGetById>>,
          TError,
          Awaited<ReturnType<typeof questionerWebQuestionerTemplatesGetById>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useQuestionerWebQuestionerTemplatesGetById<
  TData = Awaited<ReturnType<typeof questionerWebQuestionerTemplatesGetById>>,
  TError = void,
>(
  externalId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof questionerWebQuestionerTemplatesGetById>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useQuestionerWebQuestionerTemplatesGetById<
  TData = Awaited<ReturnType<typeof questionerWebQuestionerTemplatesGetById>>,
  TError = void,
>(
  externalId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof questionerWebQuestionerTemplatesGetById>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getQuestionerWebQuestionerTemplatesGetByIdQueryOptions(externalId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const questionerWebQuestionerTemplatesUpdate = (
  externalId: string,
  updateQuestionerTemplateRequest: UpdateQuestionerTemplateRequest
) => {
  return questionerInstance<void>({
    url: `/api/v1/questionerTemplates/${externalId}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: updateQuestionerTemplateRequest,
  });
};

export const getQuestionerWebQuestionerTemplatesUpdateMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof questionerWebQuestionerTemplatesUpdate>>,
    TError,
    { externalId: string; data: UpdateQuestionerTemplateRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof questionerWebQuestionerTemplatesUpdate>>,
  TError,
  { externalId: string; data: UpdateQuestionerTemplateRequest },
  TContext
> => {
  const mutationKey = ['questionerWebQuestionerTemplatesUpdate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof questionerWebQuestionerTemplatesUpdate>>,
    { externalId: string; data: UpdateQuestionerTemplateRequest }
  > = (props) => {
    const { externalId, data } = props ?? {};

    return questionerWebQuestionerTemplatesUpdate(externalId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type QuestionerWebQuestionerTemplatesUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof questionerWebQuestionerTemplatesUpdate>>
>;
export type QuestionerWebQuestionerTemplatesUpdateMutationBody = UpdateQuestionerTemplateRequest;
export type QuestionerWebQuestionerTemplatesUpdateMutationError = void;

export const useQuestionerWebQuestionerTemplatesUpdate = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof questionerWebQuestionerTemplatesUpdate>>,
      TError,
      { externalId: string; data: UpdateQuestionerTemplateRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof questionerWebQuestionerTemplatesUpdate>>,
  TError,
  { externalId: string; data: UpdateQuestionerTemplateRequest },
  TContext
> => {
  const mutationOptions = getQuestionerWebQuestionerTemplatesUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const questionerWebQuestionerTemplatesDeleteInactive = () => {
  return questionerInstance<DeleteInactiveQuestionerTemplatesResponse>({
    url: `/api/v1/questionerTemplates/delete/inactive`,
    method: 'DELETE',
  });
};

export const getQuestionerWebQuestionerTemplatesDeleteInactiveMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof questionerWebQuestionerTemplatesDeleteInactive>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof questionerWebQuestionerTemplatesDeleteInactive>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['questionerWebQuestionerTemplatesDeleteInactive'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof questionerWebQuestionerTemplatesDeleteInactive>>,
    void
  > = () => {
    return questionerWebQuestionerTemplatesDeleteInactive();
  };

  return { mutationFn, ...mutationOptions };
};

export type QuestionerWebQuestionerTemplatesDeleteInactiveMutationResult = NonNullable<
  Awaited<ReturnType<typeof questionerWebQuestionerTemplatesDeleteInactive>>
>;

export type QuestionerWebQuestionerTemplatesDeleteInactiveMutationError = void;

export const useQuestionerWebQuestionerTemplatesDeleteInactive = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof questionerWebQuestionerTemplatesDeleteInactive>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof questionerWebQuestionerTemplatesDeleteInactive>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getQuestionerWebQuestionerTemplatesDeleteInactiveMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const questionerWebQuestionerTemplatesGetActiveTemplate = (signal?: AbortSignal) => {
  return questionerInstance<QuestionerTemplateDto>({
    url: `/api/v1/questionerTemplates/active`,
    method: 'GET',
    signal,
  });
};

export const getQuestionerWebQuestionerTemplatesGetActiveTemplateQueryKey = () => {
  return [`/api/v1/questionerTemplates/active`] as const;
};

export const getQuestionerWebQuestionerTemplatesGetActiveTemplateQueryOptions = <
  TData = Awaited<ReturnType<typeof questionerWebQuestionerTemplatesGetActiveTemplate>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof questionerWebQuestionerTemplatesGetActiveTemplate>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getQuestionerWebQuestionerTemplatesGetActiveTemplateQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof questionerWebQuestionerTemplatesGetActiveTemplate>>
  > = ({ signal }) => questionerWebQuestionerTemplatesGetActiveTemplate(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof questionerWebQuestionerTemplatesGetActiveTemplate>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type QuestionerWebQuestionerTemplatesGetActiveTemplateQueryResult = NonNullable<
  Awaited<ReturnType<typeof questionerWebQuestionerTemplatesGetActiveTemplate>>
>;
export type QuestionerWebQuestionerTemplatesGetActiveTemplateQueryError = void;

export function useQuestionerWebQuestionerTemplatesGetActiveTemplate<
  TData = Awaited<ReturnType<typeof questionerWebQuestionerTemplatesGetActiveTemplate>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof questionerWebQuestionerTemplatesGetActiveTemplate>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof questionerWebQuestionerTemplatesGetActiveTemplate>>,
          TError,
          Awaited<ReturnType<typeof questionerWebQuestionerTemplatesGetActiveTemplate>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useQuestionerWebQuestionerTemplatesGetActiveTemplate<
  TData = Awaited<ReturnType<typeof questionerWebQuestionerTemplatesGetActiveTemplate>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof questionerWebQuestionerTemplatesGetActiveTemplate>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof questionerWebQuestionerTemplatesGetActiveTemplate>>,
          TError,
          Awaited<ReturnType<typeof questionerWebQuestionerTemplatesGetActiveTemplate>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useQuestionerWebQuestionerTemplatesGetActiveTemplate<
  TData = Awaited<ReturnType<typeof questionerWebQuestionerTemplatesGetActiveTemplate>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof questionerWebQuestionerTemplatesGetActiveTemplate>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useQuestionerWebQuestionerTemplatesGetActiveTemplate<
  TData = Awaited<ReturnType<typeof questionerWebQuestionerTemplatesGetActiveTemplate>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof questionerWebQuestionerTemplatesGetActiveTemplate>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getQuestionerWebQuestionerTemplatesGetActiveTemplateQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const questionerWebQuestionerTemplatesList = (signal?: AbortSignal) => {
  return questionerInstance<ListQuestionerTemplatesResponse>({
    url: `/api/v1/questionerTemplates/list`,
    method: 'GET',
    signal,
  });
};

export const getQuestionerWebQuestionerTemplatesListQueryKey = () => {
  return [`/api/v1/questionerTemplates/list`] as const;
};

export const getQuestionerWebQuestionerTemplatesListQueryOptions = <
  TData = Awaited<ReturnType<typeof questionerWebQuestionerTemplatesList>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof questionerWebQuestionerTemplatesList>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getQuestionerWebQuestionerTemplatesListQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof questionerWebQuestionerTemplatesList>>
  > = ({ signal }) => questionerWebQuestionerTemplatesList(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof questionerWebQuestionerTemplatesList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type QuestionerWebQuestionerTemplatesListQueryResult = NonNullable<
  Awaited<ReturnType<typeof questionerWebQuestionerTemplatesList>>
>;
export type QuestionerWebQuestionerTemplatesListQueryError = void;

export function useQuestionerWebQuestionerTemplatesList<
  TData = Awaited<ReturnType<typeof questionerWebQuestionerTemplatesList>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof questionerWebQuestionerTemplatesList>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof questionerWebQuestionerTemplatesList>>,
          TError,
          Awaited<ReturnType<typeof questionerWebQuestionerTemplatesList>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useQuestionerWebQuestionerTemplatesList<
  TData = Awaited<ReturnType<typeof questionerWebQuestionerTemplatesList>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof questionerWebQuestionerTemplatesList>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof questionerWebQuestionerTemplatesList>>,
          TError,
          Awaited<ReturnType<typeof questionerWebQuestionerTemplatesList>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useQuestionerWebQuestionerTemplatesList<
  TData = Awaited<ReturnType<typeof questionerWebQuestionerTemplatesList>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof questionerWebQuestionerTemplatesList>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useQuestionerWebQuestionerTemplatesList<
  TData = Awaited<ReturnType<typeof questionerWebQuestionerTemplatesList>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof questionerWebQuestionerTemplatesList>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getQuestionerWebQuestionerTemplatesListQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
