/**
 * Change Password Form.
 * Sub-component for SecuritySettingsScreen handling password change inputs,
 * client-side validation, and API mutation via Orval hooks.
 */
import React, { useCallback, useState } from 'react';

import { StyleSheet, Text, TextInput, View } from 'react-native';

import { notifyError, notifySuccess } from '../../../../lib/notifications';
import { FM } from '../../../../localization/helpers';
import { useIdentityServiceAPIMeChangePassword } from '../../../../server/autoGeneratedHooks/identity/me/me';
import { TestIds } from '../../../../shared/testIds';
import { useTheme } from '../../../../theme/hooks/useTheme';
import { isValueDefined } from '../../../../utils/is';
import { Button } from '../../../core/Button';
import ButtonVariant from '../../../core/Button/utils/ButtonVariant';
import {
  TITLE_FONT_SIZE,
  TITLE_GAP,
  DESCRIPTION_FONT_SIZE,
  MEDIUM_SPACING,
  BODY_FONT_SIZE,
  INPUT_BORDER_RADIUS,
  INPUT_PADDING,
  INPUT_BORDER_WIDTH,
  INPUT_HEIGHT,
  SMALL_SPACING,
  MIN_PASSWORD_LENGTH,
} from '../constants';

const TITLE_FONT_WEIGHT = '600' as const;

const styles = StyleSheet.create({
  sectionTitle: {
    fontSize: TITLE_FONT_SIZE,
    fontWeight: TITLE_FONT_WEIGHT,
    marginBottom: TITLE_GAP,
  },
  fieldLabel: {
    fontSize: DESCRIPTION_FONT_SIZE,
    marginBottom: TITLE_GAP,
    marginTop: MEDIUM_SPACING,
  },
  textInput: {
    borderWidth: INPUT_BORDER_WIDTH,
    borderRadius: INPUT_BORDER_RADIUS,
    padding: INPUT_PADDING,
    fontSize: BODY_FONT_SIZE,
    height: INPUT_HEIGHT,
  },
  buttonSpacing: { marginTop: SMALL_SPACING },
});

export function validatePasswordForm(
  currentPassword: string,
  newPassword: string,
  confirmPassword: string,
): string | null {
  if (currentPassword.trim() === '')
    return FM('settings.security.messages.currentPasswordRequired');

  if (newPassword.trim() === '')
    return FM('settings.security.messages.newPasswordRequired');

  if (newPassword.length < MIN_PASSWORD_LENGTH)
    return FM('settings.security.messages.passwordTooShort', String(MIN_PASSWORD_LENGTH));

  if (newPassword !== confirmPassword)
    return FM('settings.security.messages.passwordMismatch');

  return null;
}

const ChangePasswordForm = (): React.ReactElement => {
  const { theme } = useTheme();
  const { colors } = theme;

  const changePassword = useIdentityServiceAPIMeChangePassword();

  const [currentPassword, setCurrentPassword] = useState('');
  const [newPassword, setNewPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');

  const handleSubmit = useCallback(() => {
    const error = validatePasswordForm(currentPassword, newPassword, confirmPassword);

    if (isValueDefined(error)) {
      notifyError(error);
      return;
    }

    changePassword.mutate(
      { data: { currentPassword, newPassword } },
      {
        onSuccess: () => {
          notifySuccess(FM('settings.security.messages.passwordChanged'));
          setCurrentPassword('');
          setNewPassword('');
          setConfirmPassword('');
        },
        onError: () => {
          notifyError(FM('settings.security.messages.passwordError'));
        },
      },
    );
  }, [currentPassword, newPassword, confirmPassword, changePassword]);

  const isPending = changePassword.isPending;
  const buttonLabel = isPending
    ? FM('common.saving')
    : FM('settings.security.changePasswordButton');

  return (
    <View>
      <Text style={[styles.sectionTitle, { color: colors.text }]}>
        {FM('settings.security.changePassword')}
      </Text>

      <Text style={[styles.fieldLabel, { color: colors.textSecondary }]}>
        {FM('settings.security.currentPassword')}
      </Text>
      <TextInput
        secureTextEntry
        accessibilityHint={FM('settings.security.currentPasswordHint')}
        accessibilityLabel={FM('settings.security.currentPassword')}
        placeholder={FM('settings.security.currentPasswordPlaceholder')}
        placeholderTextColor={colors.textSecondary}
        style={[styles.textInput, { borderColor: colors.border, color: colors.text }]}
        testID={TestIds.SECURITY_CURRENT_PASSWORD_INPUT}
        value={currentPassword}
        onChangeText={setCurrentPassword}
      />

      <Text style={[styles.fieldLabel, { color: colors.textSecondary }]}>
        {FM('settings.security.newPassword')}
      </Text>
      <TextInput
        secureTextEntry
        accessibilityHint={FM('settings.security.newPasswordHint')}
        accessibilityLabel={FM('settings.security.newPassword')}
        placeholder={FM('settings.security.newPasswordPlaceholder')}
        placeholderTextColor={colors.textSecondary}
        style={[styles.textInput, { borderColor: colors.border, color: colors.text }]}
        testID={TestIds.SECURITY_NEW_PASSWORD_INPUT}
        value={newPassword}
        onChangeText={setNewPassword}
      />

      <Text style={[styles.fieldLabel, { color: colors.textSecondary }]}>
        {FM('settings.security.confirmPassword')}
      </Text>
      <TextInput
        secureTextEntry
        accessibilityHint={FM('settings.security.confirmPasswordHint')}
        accessibilityLabel={FM('settings.security.confirmPassword')}
        placeholder={FM('settings.security.confirmPasswordPlaceholder')}
        placeholderTextColor={colors.textSecondary}
        style={[styles.textInput, { borderColor: colors.border, color: colors.text }]}
        testID={TestIds.SECURITY_CONFIRM_PASSWORD_INPUT}
        value={confirmPassword}
        onChangeText={setConfirmPassword}
      />

      <View style={styles.buttonSpacing}>
        <Button
          accessibilityHint={FM('settings.security.changePasswordButtonHint')}
          accessibilityLabel={FM('settings.security.changePasswordButton')}
          disabled={isPending}
          label={buttonLabel}
          testID={TestIds.SECURITY_CHANGE_PASSWORD_BUTTON}
          variant={ButtonVariant.Primary}
          onPress={handleSubmit}
        />
      </View>
    </View>
  );
};

export default ChangePasswordForm;
