/**
 * Unit tests for ChangePasswordForm validation and callback logic.
 * Tests pure validation function and handleSubmit behavior, not rendering.
 */
import { validatePasswordForm } from './ChangePasswordForm';
import { MIN_PASSWORD_LENGTH } from '../constants';

// ---------------------------------------------------------------------------
// Mocks
// ---------------------------------------------------------------------------

jest.mock('../../../../localization/helpers', () => ({
  FM: (key: string, ...args: string[]) =>
    args.length > 0 ? `${key}:${args.join(',')}` : key,
}));

jest.mock('../../../../theme/hooks/useTheme', () => ({
  useTheme: jest.fn(),
}));

jest.mock('../../../../server/autoGeneratedHooks/identity/me/me', () => ({
  useIdentityServiceAPIMeChangePassword: jest.fn(),
}));

const mockNotifyError = jest.fn();
const mockNotifySuccess = jest.fn();
jest.mock('../../../../lib/notifications', () => ({
  notifyError: (...args: unknown[]) => mockNotifyError(...args),
  notifySuccess: (...args: unknown[]) => mockNotifySuccess(...args),
}));

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const VALID_CURRENT_PASSWORD = 'OldPass123!';
const SHORT_PASSWORD = 'Ab1';
const VALID_NEW_PASSWORD = 'NewSecure99!';
const MISMATCHED_CONFIRM = 'DifferentPassword1!';

// ---------------------------------------------------------------------------
// Tests: validatePasswordForm (pure function)
// ---------------------------------------------------------------------------

describe('validatePasswordForm', () => {
  it('returns error when current password is empty', () => {
    const result = validatePasswordForm('', VALID_NEW_PASSWORD, VALID_NEW_PASSWORD);
    expect(result).toBe('settings.security.messages.currentPasswordRequired');
  });

  it('returns error when current password is only whitespace', () => {
    const result = validatePasswordForm('   ', VALID_NEW_PASSWORD, VALID_NEW_PASSWORD);
    expect(result).toBe('settings.security.messages.currentPasswordRequired');
  });

  it('returns error when new password is empty', () => {
    const result = validatePasswordForm(VALID_CURRENT_PASSWORD, '', '');
    expect(result).toBe('settings.security.messages.newPasswordRequired');
  });

  it('returns error when new password is only whitespace', () => {
    const result = validatePasswordForm(VALID_CURRENT_PASSWORD, '   ', '   ');
    expect(result).toBe('settings.security.messages.newPasswordRequired');
  });

  it('returns error when new password is shorter than minimum length', () => {
    const result = validatePasswordForm(VALID_CURRENT_PASSWORD, SHORT_PASSWORD, SHORT_PASSWORD);
    expect(result).toBe(
      `settings.security.messages.passwordTooShort:${String(MIN_PASSWORD_LENGTH)}`,
    );
  });

  it('returns error when confirm password does not match new password', () => {
    const result = validatePasswordForm(
      VALID_CURRENT_PASSWORD,
      VALID_NEW_PASSWORD,
      MISMATCHED_CONFIRM,
    );
    expect(result).toBe('settings.security.messages.passwordMismatch');
  });

  it('returns null when all fields are valid and passwords match', () => {
    const result = validatePasswordForm(
      VALID_CURRENT_PASSWORD,
      VALID_NEW_PASSWORD,
      VALID_NEW_PASSWORD,
    );
    expect(result).toBeNull();
  });

  it('validates length before checking mismatch', () => {
    const result = validatePasswordForm(VALID_CURRENT_PASSWORD, SHORT_PASSWORD, MISMATCHED_CONFIRM);
    expect(result).toBe(
      `settings.security.messages.passwordTooShort:${String(MIN_PASSWORD_LENGTH)}`,
    );
  });

  it('accepts password at exactly minimum length', () => {
    const exactMinPassword = 'A'.repeat(MIN_PASSWORD_LENGTH);
    const result = validatePasswordForm(VALID_CURRENT_PASSWORD, exactMinPassword, exactMinPassword);
    expect(result).toBeNull();
  });

  it('rejects password one character below minimum length', () => {
    const belowMinPassword = 'A'.repeat(MIN_PASSWORD_LENGTH - 1);
    const result = validatePasswordForm(
      VALID_CURRENT_PASSWORD,
      belowMinPassword,
      belowMinPassword,
    );
    expect(result).toBe(
      `settings.security.messages.passwordTooShort:${String(MIN_PASSWORD_LENGTH)}`,
    );
  });
});

// ---------------------------------------------------------------------------
// Tests: handleSubmit callback logic (simulated)
// ---------------------------------------------------------------------------

describe('ChangePasswordForm - handleSubmit logic', () => {
  const mockMutate = jest.fn();

  beforeEach(() => {
    jest.clearAllMocks();
  });

  /**
   * Simulates the handleSubmit logic from the component.
   * Mirrors the actual implementation: validate -> notify error or mutate.
   */
  function simulateHandleSubmit(
    currentPassword: string,
    newPassword: string,
    confirmPassword: string,
  ): void {
    const { FM } = require('../../../../localization/helpers');
    const { notifyError, notifySuccess } = require('../../../../lib/notifications');

    const error = validatePasswordForm(currentPassword, newPassword, confirmPassword);

    if (error !== null) {
      notifyError(error);
      return;
    }

    mockMutate(
      { data: { currentPassword, newPassword } },
      {
        onSuccess: () => {
          notifySuccess(FM('settings.security.messages.passwordChanged'));
        },
        onError: () => {
          notifyError(FM('settings.security.messages.passwordError'));
        },
      },
    );
  }

  it('notifies error and does not call mutate when validation fails', () => {
    simulateHandleSubmit('', VALID_NEW_PASSWORD, VALID_NEW_PASSWORD);

    expect(mockNotifyError).toHaveBeenCalledWith(
      'settings.security.messages.currentPasswordRequired',
    );
    expect(mockMutate).not.toHaveBeenCalled();
  });

  it('calls mutate with correct data shape when validation passes', () => {
    simulateHandleSubmit(VALID_CURRENT_PASSWORD, VALID_NEW_PASSWORD, VALID_NEW_PASSWORD);

    expect(mockNotifyError).not.toHaveBeenCalled();
    expect(mockMutate).toHaveBeenCalledWith(
      { data: { currentPassword: VALID_CURRENT_PASSWORD, newPassword: VALID_NEW_PASSWORD } },
      expect.objectContaining({
        onSuccess: expect.any(Function),
        onError: expect.any(Function),
      }),
    );
  });

  it('notifies success on mutation success callback', () => {
    simulateHandleSubmit(VALID_CURRENT_PASSWORD, VALID_NEW_PASSWORD, VALID_NEW_PASSWORD);

    const callArgs = mockMutate.mock.calls[0] as [unknown, { onSuccess: () => void }];
    callArgs[1].onSuccess();

    expect(mockNotifySuccess).toHaveBeenCalledWith(
      'settings.security.messages.passwordChanged',
    );
  });

  it('notifies error on mutation error callback', () => {
    simulateHandleSubmit(VALID_CURRENT_PASSWORD, VALID_NEW_PASSWORD, VALID_NEW_PASSWORD);

    const callArgs = mockMutate.mock.calls[0] as [unknown, { onError: () => void }];
    callArgs[1].onError();

    expect(mockNotifyError).toHaveBeenCalledWith(
      'settings.security.messages.passwordError',
    );
  });

  it('does not include confirmPassword in mutation payload', () => {
    simulateHandleSubmit(VALID_CURRENT_PASSWORD, VALID_NEW_PASSWORD, VALID_NEW_PASSWORD);

    const payload = mockMutate.mock.calls[0] as [{ data: Record<string, unknown> }];
    expect(payload[0].data).not.toHaveProperty('confirmPassword');
  });
});
