/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OnlineMenu.Web
 * OpenAPI spec version: 1.0.0
 */

export interface AvailabilityBadgeStyle {
  /** @nullable */
  show?: boolean | null;
  /** @nullable */
  position?: string | null;
  /** @nullable */
  unavailableText?: string | null;
  /** @nullable */
  unavailableColor?: string | null;
  /** @nullable */
  unavailableBackgroundColor?: string | null;
}
