/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OnlineMenu.Web
 * OpenAPI spec version: 1.0.0
 */

export interface CategoryTypography {
  /** @nullable */
  titleFontSize?: number | null;
  /** @nullable */
  titleFontWeight?: string | null;
  /** @nullable */
  titleColor?: string | null;
  /** @nullable */
  descriptionFontSize?: number | null;
  /** @nullable */
  descriptionFontWeight?: string | null;
  /** @nullable */
  descriptionColor?: string | null;
  /** @nullable */
  descriptionVisible?: boolean | null;
}
