/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OnlineMenu.Web
 * OpenAPI spec version: 1.0.0
 */

export interface CreateLocationRequest {
  /**
   * @minLength 0
   * @maxLength 200
   */
  name: string;
  /**
   * @minLength 0
   * @maxLength 200
   * @nullable
   */
  addressLine1?: string | null;
  /**
   * @minLength 0
   * @maxLength 200
   * @nullable
   */
  addressLine2?: string | null;
  /**
   * @minLength 0
   * @maxLength 200
   * @nullable
   */
  city?: string | null;
  /**
   * @minLength 0
   * @maxLength 200
   * @nullable
   */
  state?: string | null;
  /**
   * @minLength 0
   * @maxLength 50
   * @nullable
   */
  postalCode?: string | null;
  /**
   * @minLength 0
   * @maxLength 200
   * @nullable
   */
  country?: string | null;
  /**
   * @minLength 0
   * @maxLength 50
   * @nullable
   */
  phone?: string | null;
  /**
   * @minLength 0
   * @maxLength 200
   * @nullable
   * @pattern ^[^@]+@[^@]+$
   */
  email?: string | null;
  /**
   * @minLength 0
   * @maxLength 50
   * @nullable
   */
  timezone?: string | null;
  isHeadquarters?: boolean;
}
