/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OnlineMenu.Web
 * OpenAPI spec version: 1.0.0
 */

export interface CreateDietaryTagRequest {
  key?: string;
  name?: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  icon?: string | null;
  /** @nullable */
  color?: string | null;
  displayOrder?: number;
}
