/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OnlineMenu.Web
 * OpenAPI spec version: 1.0.0
 */

export interface CreateExperimentRequest {
  menuId?: string;
  name?: string;
  /** Optional. Defaults to MenuId (variant A is the original menu). */
  variantAMenuId?: string;
  /** Accepts both a JSON string and a JSON object from the frontend.
Stored as a serialized JSON string in the database. */
  variantBConfig?: unknown;
}
