/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OnlineMenu.Web
 * OpenAPI spec version: 1.0.0
 */

export interface GenerateNutritionResponse {
  /** @nullable */
  calories?: number | null;
  /** @nullable */
  proteinGrams?: number | null;
  /** @nullable */
  carbsGrams?: number | null;
  /** @nullable */
  fatGrams?: number | null;
  /** @nullable */
  fiberGrams?: number | null;
  /** @nullable */
  sodiumMg?: number | null;
  /** @nullable */
  servingSize?: string | null;
  detectedAllergens?: string[];
}
