/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OnlineMenu.Web
 * OpenAPI spec version: 1.0.0
 */

export interface ImportedMenuItem {
  name?: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  price?: number | null;
  dietaryTags?: string[];
}
