/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OnlineMenu.Web
 * OpenAPI spec version: 1.0.0
 */

export interface ItemLayout {
  /** @nullable */
  variant?: string | null;
  /** @nullable */
  imagePosition?: string | null;
  /** @nullable */
  contentAlignment?: string | null;
  /** @nullable */
  minHeight?: number | null;
  /** @nullable */
  maxWidth?: number | null;
}
