/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OnlineMenu.Web
 * OpenAPI spec version: 1.0.0
 */
import type { ScansByDayDto } from './scansByDayDto';
import type { DeviceBreakdownDto } from './deviceBreakdownDto';
import type { ItemViewDto } from './itemViewDto';

export interface MenuAnalyticsDetailDto {
  totalScans?: number;
  scansByDay?: ScansByDayDto[];
  deviceBreakdown?: DeviceBreakdownDto[];
  topViewedItems?: ItemViewDto[];
}
