/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OnlineMenu.Web
 * OpenAPI spec version: 1.0.0
 */

export interface MenuVersionDiff {
  path?: string;
  changeType?: string;
  /** @nullable */
  oldValue?: string | null;
  /** @nullable */
  newValue?: string | null;
}
