/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OnlineMenu.Web
 * OpenAPI spec version: 1.0.0
 */

export type MergeStrategy = (typeof MergeStrategy)[keyof typeof MergeStrategy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MergeStrategy = {
  Replace: 0,
  Merge: 1,
} as const;
