/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OnlineMenu.Web
 * OpenAPI spec version: 1.0.0
 */

export type OnlineMenuWebAnalyticsGetMenuAnalyticsDetailParams = {
  /**
   * Start of the date range (inclusive). Defaults to 30 days ago.
   * @nullable
   */
  from?: string | null;
  /**
   * End of the date range (exclusive). Defaults to end of today.
   * @nullable
   */
  to?: string | null;
};
