/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OnlineMenu.Web
 * OpenAPI spec version: 1.0.0
 */
import type { PublicApiCategoryResponse } from './publicApiCategoryResponse';

export interface PublicApiMenuDetailResponse {
  id?: string;
  name?: string;
  /** @nullable */
  description?: string | null;
  isActive?: boolean;
  updatedAt?: string;
  categories?: PublicApiCategoryResponse[];
}
