/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OnlineMenu.Web
 * OpenAPI spec version: 1.0.0
 */

export interface PublicApiMenuItemResponse {
  name?: string;
  /** @nullable */
  description?: string | null;
  price?: number;
  isAvailable?: boolean;
  displayOrder?: number;
  /** @nullable */
  tags?: string[] | null;
  isFeatured?: boolean;
}
