/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OnlineMenu.Web
 * OpenAPI spec version: 1.0.0
 */
import type { PublicApiMenuItemResponse } from './publicApiMenuItemResponse';

export interface PublicApiCategoryResponse {
  name?: string;
  /** @nullable */
  description?: string | null;
  displayOrder?: number;
  items?: PublicApiMenuItemResponse[];
}
