/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OnlineMenu.Web
 * OpenAPI spec version: 1.0.0
 */
import type { PublicApiMenuResponse } from './publicApiMenuResponse';
import type { PaginationInfo } from './paginationInfo';

export interface PublicApiPaginatedResponseOfPublicApiMenuResponse {
  data?: PublicApiMenuResponse[];
  pagination?: PaginationInfo;
}
