/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OnlineMenu.Web
 * OpenAPI spec version: 1.0.0
 */
import type { MenuScanSummaryDto } from './menuScanSummaryDto';

export interface TenantAnalyticsSummaryDto {
  totalMenus?: number;
  activeMenus?: number;
  totalQrScans?: number;
  scansToday?: number;
  topMenusByScans?: MenuScanSummaryDto[];
}
