/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OnlineMenu.Web
 * OpenAPI spec version: 1.0.0
 */

export type TranslationStatus = (typeof TranslationStatus)[keyof typeof TranslationStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TranslationStatus = {
  Pending: 0,
  InProgress: 1,
  Completed: 2,
  Failed: 3,
  Stale: 4,
} as const;
