/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OnlineMenu.Web
 * OpenAPI spec version: 1.0.0
 */
import type { TranslatedCategory } from './translatedCategory';

export interface TranslatedMenuContents {
  /** @nullable */
  menuName?: string | null;
  /** @nullable */
  menuDescription?: string | null;
  /** @nullable */
  featuredSectionTitle?: string | null;
  categories?: TranslatedCategory[];
}
