/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OnlineMenu.Web
 * OpenAPI spec version: 1.0.0
 */
import type { TranslatedMenuItem } from './translatedMenuItem';

export interface TranslatedCategory {
  originalIndex?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  description?: string | null;
  items?: TranslatedMenuItem[];
}
