/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OnlineMenu.Web
 * OpenAPI spec version: 1.0.0
 */
import type { TranslatedVariant } from './translatedVariant';

export interface TranslatedVariantGroup {
  originalIndex?: number;
  /** @nullable */
  name?: string | null;
  variants?: TranslatedVariant[];
}
