/**
 * Tests for quizHelpers - API mapping and submission payload.
 */
import { toApiAnswer, mapApiQuestionToUi, buildSubmissionPayload } from './quizHelpers';
import { QuestionType as ApiQuestionType } from '../../../server/autoGeneratedHooks/questioner/models/questionType';
import QuestionType from '../../../shared/enums/QuestionType';

import type { DynamicQuiz } from '../../../components/DynamicForm';
import type { Question as ApiQuestionModel } from '../../../server/autoGeneratedHooks/questioner/models';

describe('quizHelpers - API Mapping', () => {
  describe('toApiAnswer', () => {
    it('returns null for undefined', () => {
      expect(toApiAnswer(undefined)).toBe(null);
    });

    it('returns boolValue for boolean', () => {
      expect(toApiAnswer(true)).toEqual({ boolValue: true });
      expect(toApiAnswer(false)).toEqual({ boolValue: false });
    });

    it('returns numericValue for number', () => {
      expect(toApiAnswer(42)).toEqual({ numericValue: 42 });
      expect(toApiAnswer(0)).toEqual({ numericValue: 0 });
    });

    it('returns stringValue for string', () => {
      expect(toApiAnswer('hello')).toEqual({ stringValue: 'hello' });
      expect(toApiAnswer('')).toEqual({ stringValue: '' });
    });

    it('returns multiValues for array', () => {
      expect(toApiAnswer(['a', 'b'])).toEqual({ multiValues: ['a', 'b'] });
    });

    it('converts array values to strings', () => {
      expect(toApiAnswer([1, 2, 3] as unknown as string[])).toEqual({ multiValues: ['1', '2', '3'] });
    });
  });

  describe('mapApiQuestionToUi', () => {
    it('maps basic API question to UI question', () => {
      const apiQuestion: ApiQuestionModel = {
        id: 'q1',
        name: 'What is your name?',
        type: ApiQuestionType.Text,
        page: 1,
        order: 1,
        isRequired: true,
        options: [],
        skipConditions: [],
      };
      const result = mapApiQuestionToUi(apiQuestion, 0);
      expect(result.id).toBe('q1');
      expect(result.name).toBe('What is your name?');
      expect(result.type).toBe('text');
      expect(result.page).toBe(1);
      expect(result.order).toBe(1);
      expect(result.isRequired).toBe(true);
      expect(result.answer).toBeUndefined();
    });

    it('normalizes 0-based page to 1-based', () => {
      const apiQuestion: ApiQuestionModel = { id: 'q1', name: 'Q', page: 0 };
      const result = mapApiQuestionToUi(apiQuestion, 0);
      expect(result.page).toBe(1);
    });

    it('generates id when not provided', () => {
      const apiQuestion: ApiQuestionModel = { name: 'Q' };
      const result = mapApiQuestionToUi(apiQuestion, 5);
      expect(result.id).toBe('q_5');
    });

    it('uses default order when not provided', () => {
      const apiQuestion: ApiQuestionModel = { id: 'q1', name: 'Q' };
      const result = mapApiQuestionToUi(apiQuestion, 3);
      expect(result.order).toBe(4);
    });

    it('converts text type to dropdown when options provided', () => {
      const apiQuestion: ApiQuestionModel = {
        id: 'q1',
        name: 'Choose',
        type: ApiQuestionType.Text,
        options: [{ label: 'A', value: 'a' }],
      };
      const result = mapApiQuestionToUi(apiQuestion, 0);
      expect(result.type).toBe('dropdown');
    });

    it('maps options correctly', () => {
      const apiQuestion: ApiQuestionModel = {
        id: 'q1',
        name: 'Choose',
        type: ApiQuestionType.Radio,
        options: [
          { label: 'Option A', value: 'a' },
          { label: 'Option B', value: 'b' },
        ],
      };
      const result = mapApiQuestionToUi(apiQuestion, 0);
      expect(result.options).toEqual([
        { label: 'Option A', value: 'a' },
        { label: 'Option B', value: 'b' },
      ]);
    });

    it('maps skipConditions correctly', () => {
      const apiQuestion: ApiQuestionModel = {
        id: 'q1',
        name: 'Q',
        skipConditions: [{ questionId: 'q0', questionAnswer: 'yes' }],
      };
      const result = mapApiQuestionToUi(apiQuestion, 0);
      expect(result.skipConditions).toEqual([{ questionId: 'q0', questionAnswer: 'yes' }]);
    });
  });

  describe('buildSubmissionPayload', () => {
    it('builds payload with all fields', () => {
      const form: DynamicQuiz = {
        id: 'form1',
        name: 'Form Name',
        description: 'Form Desc',
        questions: [
          {
            id: 'q1',
            name: 'Question 1',
            type: QuestionType.Text,
            page: 1,
            order: 1,
            isRequired: true,
            answer: 'My answer',
            options: [{ label: 'L', value: 'v' }],
            skipConditions: [{ questionId: 'q0', questionAnswer: 'yes' }],
          },
        ],
      };
      const tpl = { name: 'Template Name', description: 'Template Desc', externalId: 'ext-123' };
      const result = buildSubmissionPayload(form, tpl);

      expect(result.name).toBe('Template Name');
      expect(result.description).toBe('Template Desc');
      expect(result.questionerTemplateExternalId).toBe('ext-123');
      expect(result.contents!.questions).toHaveLength(1);
      expect(result.contents!.questions![0].answer).toEqual({ stringValue: 'My answer' });
    });

    it('falls back to form name when template name is null', () => {
      const form: DynamicQuiz = { id: 'form1', name: 'Form Name', questions: [] };
      const tpl = { name: null, externalId: 'ext-123' };
      const result = buildSubmissionPayload(form, tpl);
      expect(result.name).toBe('Form Name');
    });

    it('handles null template description - falls back to form description', () => {
      const form: DynamicQuiz = { id: 'form1', name: 'Form', description: 'Form Desc', questions: [] };
      const tpl = { name: 'Tpl', description: null, externalId: 'ext-123' };
      const result = buildSubmissionPayload(form, tpl);
      // When tpl.description is null, it uses form.description as fallback
      expect(result.description).toBe('Form Desc');
    });

    it('handles null description when both are null/undefined', () => {
      const form: DynamicQuiz = { id: 'form1', name: 'Form', questions: [] };
      const tpl = { name: 'Tpl', description: null, externalId: 'ext-123' };
      const result = buildSubmissionPayload(form, tpl);
      expect(result.description).toBe(null);
    });

    it('handles undefined template and form description', () => {
      const form: DynamicQuiz = { id: 'form1', name: 'Form', questions: [] };
      const tpl = { name: 'Tpl', externalId: 'ext-123' };
      const result = buildSubmissionPayload(form, tpl);
      expect(result.description).toBe(null);
    });
  });
});
