/**
 * Location hooks barrel export.
 */
export { useLocationMutations } from './hooks/useLocationMutations';
export { useLocationList } from './hooks/useLocationList';

export type {
  LocationDto,
  CreateLocationRequest,
  UpdateLocationRequest,
} from '../../../server/autoGeneratedHooks/onlinemenu/models';
