/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Content.Web
 * OpenAPI spec version: 1.0.0
 */

export interface ContentVariantDto {
  externalId?: string;
  variantType?: string;
  fileSizeBytes?: number;
  /** @nullable */
  width?: number | null;
  /** @nullable */
  height?: number | null;
  contentType?: string;
}
