/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Content.Web
 * OpenAPI spec version: 1.0.0
 */

export type ContentStatus = (typeof ContentStatus)[keyof typeof ContentStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContentStatus = {
  Uploading: 'Uploading',
  Processing: 'Processing',
  Ready: 'Ready',
  Failed: 'Failed',
  Deleted: 'Deleted',
} as const;
