/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Content.Web
 * OpenAPI spec version: 1.0.0
 */
import type { ContentCategory } from './contentCategory';

export interface RequestUploadUrlRequest {
  fileName?: string;
  contentType?: string;
  fileSizeBytes?: number;
  category?: ContentCategory;
  isPublic?: boolean;
}
