import React, { useState, useCallback, useMemo } from 'react';

import { StyleSheet, Text, TouchableOpacity } from 'react-native';

import ConfirmDialog from '@/components/Shared/ConfirmDialog';
import { notifySuccess } from '@/lib/notifications';
import { FM } from '@/localization/helpers';
import type { DeleteInactiveQuestionerTemplatesResponse } from '@/server/autoGeneratedHooks/questioner/models/deleteInactiveQuestionerTemplatesResponse';
import { useQuestionerWebQuestionerTemplatesDeleteInactive } from '@/server/autoGeneratedHooks/questioner/questionertemplates/questionertemplates';
import { DISABLED_OPACITY } from '@/shared/constants';
import { TestIds } from '@/shared/testIds';
import { useTheme } from '@/theme/hooks/useTheme';

const styles = StyleSheet.create({
  disabledButton: {
    opacity: DISABLED_OPACITY,
  },
});

interface DeleteInactiveButtonProps {
  onSuccess?: () => void;
  disabled?: boolean;
}

const DeleteInactiveButton = ({
  onSuccess,
  disabled = false,
}: DeleteInactiveButtonProps): React.ReactElement => {
  const { theme } = useTheme();
  const errorColor = theme.semantic.error['500'];

  const [showConfirmDialog, setShowConfirmDialog] = useState(false);

  const deleteMutation = useQuestionerWebQuestionerTemplatesDeleteInactive();

  const colorStyles = useMemo(
    () => ({
      buttonText: {
        color: errorColor,
      },
    }),
    [errorColor]
  );

  const handlePress = useCallback(() => {
    setShowConfirmDialog(true);
  }, []);

  const handleCancel = useCallback(() => {
    setShowConfirmDialog(false);
  }, []);

  const handleConfirm = useCallback(() => {
    deleteMutation.mutate(undefined, {
      onSuccess: (response: DeleteInactiveQuestionerTemplatesResponse) => {
        const count = response.deletedCount ?? 0;

        if (count > 0)
          notifySuccess(
            FM('quizTemplates.messages.deleteInactiveSuccess', String(count))
          );
         else
          notifySuccess(FM('quizTemplates.messages.deleteInactiveNone'));


        setShowConfirmDialog(false);
        onSuccess?.();
      },
      onError: () => {
        setShowConfirmDialog(false);
      },
    });
  }, [deleteMutation, onSuccess]);

  const isDisabled = disabled || deleteMutation.isPending;

  return (
    <>
      <TouchableOpacity
        accessibilityHint={FM('quizTemplates.deleteInactiveHint')}
        accessibilityLabel={FM('quizTemplates.deleteInactive')}
        accessibilityRole="button"
        accessibilityState={{ disabled: isDisabled }}
        disabled={isDisabled}
        style={isDisabled ? styles.disabledButton : undefined}
        testID={TestIds.DELETE_INACTIVE_BUTTON}
        onPress={handlePress}
      >
        <Text style={colorStyles.buttonText}>
          {FM('quizTemplates.deleteInactive')}
        </Text>
      </TouchableOpacity>

      <ConfirmDialog
        destructive
        loading={deleteMutation.isPending}
        message={FM('quizTemplates.confirmDeleteInactive')}
        title={FM('quizTemplates.deleteInactive')}
        visible={showConfirmDialog}
        onCancel={handleCancel}
        onConfirm={handleConfirm}
      />
    </>
  );
};

export default DeleteInactiveButton;
