import React from 'react';

import { fireEvent, render, screen, waitFor } from '@testing-library/react-native';

import DeleteInactiveButton from './DeleteInactiveButton';

// Mock react-redux
jest.mock('react-redux', () => ({
  useSelector: () => 'light',
}));

// Mock useTheme (new theme system)
jest.mock('@/theme/hooks/useTheme', () => ({
  useTheme: () => ({
    theme: {
      colors: { text: '#001219', textSecondary: '#555555', background: '#ffffff', surface: '#f7f7f7', surfaceElevated: '#ffffff', border: '#e6e6e6', divider: '#eeeeee' },
      palette: { primary: { '500': '#005f73' }, secondary: { '500': '#94d2bd' }, accent: { '500': '#ee9b00' } },
      semantic: { success: { '500': '#2d6a4f' }, warning: { '500': '#ee9b00' }, error: { '500': '#ae2012' }, info: { '500': '#005f73' } },
      typography: { fontFamily: 'System', headingScale: 1.25 },
      mode: 'light',
      branding: { logoUrl: null, faviconUrl: null },
    },
    mode: 'light',
    toggleMode: jest.fn(),
    setMode: jest.fn(),
    setTenantConfig: jest.fn(),
  }),
}));

// Mock notifications
const mockNotifySuccess = jest.fn();
jest.mock('@/lib/notifications', () => ({
  notifySuccess: (message: string) => mockNotifySuccess(message),
}));

// Mock the mutation hook
const mockMutate = jest.fn();
const mockMutationState = {
  mutate: mockMutate,
  status: 'idle' as 'idle' | 'pending' | 'success' | 'error',
  isPending: false,
};

jest.mock('@/server/autoGeneratedHooks/questioner/questionertemplates/questionertemplates', () => ({
  useQuestionerWebQuestionerTemplatesDeleteInactive: () => mockMutationState,
}));

/**
 * Unit tests for DeleteInactiveButton component logic.
 * These tests focus on:
 * - Mutation calls and callbacks
 * - Notification behavior based on response
 * - State management (dialog open/close, loading states)
 *
 * Visual/rendering tests are covered by Playwright E2E tests.
 */
describe('DeleteInactiveButton', () => {
  const defaultProps = {
    onSuccess: jest.fn(),
  };

  /** Opens the delete confirmation dialog and waits for it to be visible */
  const openDialog = async (): Promise<void> => {
    fireEvent.press(screen.getByTestId('delete-inactive-button'));
    await waitFor(() => {
      expect(screen.getByTestId('confirm-dialog')).toBeTruthy();
    });
  };

  beforeEach(() => {
    jest.clearAllMocks();
    mockMutationState.status = 'idle';
    mockMutationState.isPending = false;
  });

  describe('mutation behavior', () => {
    it('calls delete mutation when user confirms', async () => {
      mockMutate.mockImplementation((_, options) => {
        options?.onSuccess?.({ deletedCount: 5 });
      });

      render(<DeleteInactiveButton {...defaultProps} />);
      await openDialog();

      fireEvent.press(screen.getByTestId('confirm-button'));

      expect(mockMutate).toHaveBeenCalledTimes(1);
    });

    it('does not call mutation when user cancels', async () => {
      render(<DeleteInactiveButton {...defaultProps} />);
      await openDialog();

      fireEvent.press(screen.getByTestId('cancel-confirm-button'));

      expect(mockMutate).not.toHaveBeenCalled();
    });

    it('calls onSuccess callback after successful deletion', async () => {
      mockMutate.mockImplementation((_, options) => {
        options?.onSuccess?.({ deletedCount: 3 });
      });

      render(<DeleteInactiveButton {...defaultProps} />);
      await openDialog();

      fireEvent.press(screen.getByTestId('confirm-button'));

      expect(defaultProps.onSuccess).toHaveBeenCalledTimes(1);
    });

    it('does not call onSuccess when mutation fails', async () => {
      mockMutate.mockImplementation((_, options) => {
        options?.onError?.();
      });

      render(<DeleteInactiveButton {...defaultProps} />);
      await openDialog();

      fireEvent.press(screen.getByTestId('confirm-button'));

      expect(mockMutate).toHaveBeenCalled();
      expect(defaultProps.onSuccess).not.toHaveBeenCalled();
    });
  });

  describe('notification behavior', () => {
    it('shows success notification with count when deletedCount > 0', async () => {
      mockMutate.mockImplementation((_, options) => {
        options?.onSuccess?.({ deletedCount: 5 });
      });

      render(<DeleteInactiveButton {...defaultProps} />);
      await openDialog();

      fireEvent.press(screen.getByTestId('confirm-button'));

      expect(mockNotifySuccess).toHaveBeenCalledWith(
        expect.stringContaining('5')
      );
    });

    it('shows "no templates found" notification when deletedCount is 0', async () => {
      mockMutate.mockImplementation((_, options) => {
        options?.onSuccess?.({ deletedCount: 0 });
      });

      render(<DeleteInactiveButton {...defaultProps} />);
      await openDialog();

      fireEvent.press(screen.getByTestId('confirm-button'));

      expect(mockNotifySuccess).toHaveBeenCalledWith('No inactive templates found');
    });

    it('handles undefined deletedCount as 0', async () => {
      mockMutate.mockImplementation((_, options) => {
        options?.onSuccess?.({});
      });

      render(<DeleteInactiveButton {...defaultProps} />);
      await openDialog();

      fireEvent.press(screen.getByTestId('confirm-button'));

      expect(mockNotifySuccess).toHaveBeenCalledWith('No inactive templates found');
    });
  });

  describe('dialog state management', () => {
    it('closes dialog after successful deletion', async () => {
      mockMutate.mockImplementation((_, options) => {
        options?.onSuccess?.({ deletedCount: 2 });
      });

      render(<DeleteInactiveButton {...defaultProps} />);
      await openDialog();

      fireEvent.press(screen.getByTestId('confirm-button'));

      expect(screen.queryByTestId('confirm-dialog')).toBeNull();
    });

    it('closes dialog after mutation error', async () => {
      mockMutate.mockImplementation((_, options) => {
        options?.onError?.();
      });

      render(<DeleteInactiveButton {...defaultProps} />);
      await openDialog();

      fireEvent.press(screen.getByTestId('confirm-button'));

      expect(screen.queryByTestId('confirm-dialog')).toBeNull();
    });

    it('closes dialog on cancel', async () => {
      render(<DeleteInactiveButton {...defaultProps} />);
      await openDialog();

      fireEvent.press(screen.getByTestId('cancel-confirm-button'));

      expect(screen.queryByTestId('confirm-dialog')).toBeNull();
    });
  });

  describe('disabled state', () => {
    it('respects disabled prop', () => {
      render(<DeleteInactiveButton {...defaultProps} disabled />);

      const button = screen.getByTestId('delete-inactive-button');
      expect(button.props.accessibilityState?.disabled).toBe(true);
    });

    it('disables button while mutation is pending', async () => {
      mockMutationState.isPending = true;

      render(<DeleteInactiveButton {...defaultProps} />);

      const button = screen.getByTestId('delete-inactive-button');
      expect(button.props.accessibilityState?.disabled).toBe(true);
    });
  });
});
