import React, { useRef, useState } from 'react';

import { StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';

import CancelButton from '@/components/Buttons/CancelButton';
import SaveButton from '@/components/Buttons/SaveButton';
import ActionRow from '@/components/core/ActionRow/ActionRow';
import { FM } from '@/localization/helpers';
import type { CreateQuestionerTemplateRequest, UpdateQuestionerTemplateRequest } from '@/server/autoGeneratedHooks/questioner/models';
import { TestIds } from '@/shared/testIds';
import { useTheme } from '@/theme/hooks/useTheme';
import { layoutStyles } from '@/theme/utils/styles';
import { isValueDefined } from '@/utils/is';
// input label/spacing are now global in layoutStyles

const TRANSPARENT_COLOR = 'transparent';
const WHITE_COLOR = '#fff';

const styles = StyleSheet.create({
  statusRow: {
    flexDirection: 'row',
    marginVertical: 8,
  },
  statusButtonSpacingRight: {
    marginRight: 12,
  },
  statusPill: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: TRANSPARENT_COLOR,
  },
});

interface Props {
  initialName?: string;
  initialDescription?: string;
  initialIsActive?: boolean;
  onCancel?: () => void;
  // onSave should accept either create or update payload depending on usage
  onSave: (payload: CreateQuestionerTemplateRequest | UpdateQuestionerTemplateRequest) => void;
  // optional onChange to lift field changes to parent (name/description/isActive)
  onChange?: (fields: { name: string; description: string; isActive: boolean }) => void;
  saving?: boolean;
  showStatus?: boolean;
  hideActions?: boolean;
}

const TemplateForm = ({
  initialName = '',
  initialDescription = '',
  initialIsActive = false,
  onCancel,
  onSave,
  onChange,
  saving = false,
  showStatus = false,
  hideActions = false,
}: Props): React.ReactElement => {
  const { theme } = useTheme();
  const colors = theme.colors;
  const primary = theme.palette.primary['500'];
  const errorColor = theme.semantic.error['500'];

  const [name, setName] = useState(initialName);
  const [description, setDescription] = useState(initialDescription);
  const [isActive, setIsActive] = useState<boolean>(Boolean(initialIsActive));
  const [error, setError] = useState<string | null>(null);

  // Keep refs in sync with text inputs so validation can use the latest value
  // even if React state updates haven't flushed yet (helps E2E/mobile input timing).
  const nameRef = useRef(name);
  const descriptionRef = useRef(description);

  const nameLabel = FM('quizTemplates.label.name');
  const descriptionLabel = FM('quizTemplates.label.description');
  const statusLabel = FM('quizTemplates.label.status');

  const nameInputStyle = React.useMemo(
    () => [layoutStyles.input, { backgroundColor: colors.surface, color: colors.text }],
    [colors.surface, colors.text],
  );
  const descriptionInputStyle = React.useMemo(
    () => [layoutStyles.input, { backgroundColor: colors.surface, color: colors.text }],
    [colors.surface, colors.text],
  );
  const labelTextStyle = React.useMemo(
    () => [layoutStyles.inputLabel, { color: colors.text }],
    [colors.text],
  );
  const errorTextStyle = React.useMemo(() => ({ color: errorColor }), [errorColor]);

  const activePillStyle = React.useMemo(
    () => [styles.statusPill, { backgroundColor: isActive ? primary : TRANSPARENT_COLOR }],
    [primary, isActive],
  );
  const inactivePillStyle = React.useMemo(
    () => [styles.statusPill, { backgroundColor: !isActive ? errorColor : TRANSPARENT_COLOR }],
    [errorColor, isActive],
  );
  const activeTextStyle = React.useMemo(
    () => ({ color: isActive ? WHITE_COLOR : colors.textSecondary }),
    [colors.textSecondary, isActive],
  );
  const inactiveTextStyle = React.useMemo(
    () => ({ color: !isActive ? WHITE_COLOR : colors.textSecondary }),
    [colors.textSecondary, isActive],
  );

  function handleSave(): void {
    setError(null);
    const trimmedName = nameRef.current.trim();
    if (trimmedName === '') {
      setError(FM('quizTemplates.errors.nameRequired'));
      return;
    }

    const basePayload: CreateQuestionerTemplateRequest | UpdateQuestionerTemplateRequest = {
      name: trimmedName,
      description: descriptionRef.current.trim() === '' ? null : descriptionRef.current,
    };
    if (showStatus)
      basePayload.isActive = isActive;

    onSave(basePayload);
  }

  // lift changes
  React.useEffect(() => {
    if (typeof onChange === 'function') onChange({ name, description, isActive });
  }, [description, isActive, name, onChange]);

  return (
    <View>
      <Text style={labelTextStyle}>{nameLabel}</Text>
      <TextInput
        accessibilityHint={FM('quizTemplates.nameInputHint')}
        accessibilityLabel={FM('quizTemplates.nameInputLabel')}
        placeholder={FM('quizTemplates.namePlaceholder')}
        style={nameInputStyle}
        testID={TestIds.TEMPLATE_NAME_INPUT}
        value={name}
        onChangeText={(value) => {
          nameRef.current = value;
          setName(value);
          if (isValueDefined(error)) setError(null);
        }}
      />

      <Text style={[labelTextStyle, layoutStyles.inputSpacing]}>{descriptionLabel}</Text>
      <TextInput
        accessibilityHint={FM('quizTemplates.descriptionInputHint')}
        accessibilityLabel={FM('quizTemplates.descriptionInputLabel')}
        placeholder={FM('quizTemplates.descriptionPlaceholder')}
        style={descriptionInputStyle}
        value={description}
        onChangeText={(value) => {
          descriptionRef.current = value;
          setDescription(value);
        }}
      />

      {showStatus ? (
        <View style={layoutStyles.sectionSpacing}>
          <Text style={labelTextStyle}>{statusLabel}</Text>
          <View style={styles.statusRow}>
            <TouchableOpacity
              accessibilityHint={FM('quizTemplates.activeStatusHint')}
              accessibilityLabel={FM('quizTemplates.activeStatusLabel')}
              accessibilityRole="button"
              style={styles.statusButtonSpacingRight}
              testID={TestIds.TEMPLATE_STATUS_ACTIVE_BUTTON}
              onPress={() => setIsActive(true)}
            >
              <View style={activePillStyle}>
                <Text style={activeTextStyle}>{FM('quizTemplates.status.active')}</Text>
              </View>
            </TouchableOpacity>

            <TouchableOpacity
              accessibilityHint={FM('quizTemplates.inactiveStatusHint')}
              accessibilityLabel={FM('quizTemplates.inactiveStatusLabel')}
              accessibilityRole="button"
              testID={TestIds.TEMPLATE_STATUS_INACTIVE_BUTTON}
              onPress={() => setIsActive(false)}
            >
              <View style={inactivePillStyle}>
                <Text style={inactiveTextStyle}>{FM('quizTemplates.status.inactive')}</Text>
              </View>
            </TouchableOpacity>
          </View>
        </View>
      ) : null}

      {isValueDefined(error) ? <Text style={errorTextStyle}>{error}</Text> : null}

      {!hideActions ? (
        <ActionRow>
          <SaveButton disabled={saving} title={FM('quizTemplates.save')} onPress={handleSave} />
          <CancelButton title={FM('quizTemplates.cancel')} onPress={onCancel} />
        </ActionRow>
      ) : null}
    </View>
  );
};

export default TemplateForm;
