import React, { useMemo } from 'react';

import { View, ActivityIndicator, Text, StyleSheet } from 'react-native';

import { useSelector } from 'react-redux';

import QuizContent from './QuizContent';
import ThankYouOverlay from './ThankYouOverlay';
import PageHeaderWithActions from '../../../src/components/Shared/PageHeaderWithActions';
import { useQuizForm } from '../../../src/hooks/quiz';
import { FM } from '../../../src/localization/helpers';
import { useQuestionerWebCompletedQuestionersCreate } from '../../../src/server/autoGeneratedHooks/questioner/completedquestioners/completedquestioners';
import { useQuestionerWebQuestionerTemplatesGetActiveTemplate } from '../../../src/server/autoGeneratedHooks/questioner/questionertemplates/questionertemplates';
import ThemeMode from '../../../src/shared/enums/ThemeMode';
import { layoutStyles, themePalette, useDynamicFormStyles } from '../../../src/theme/utils/styles';
import { isValueDefined } from '../../../src/utils/is';

import type { RootState } from '../../../src/store/reduxStore';

const screenStyles = StyleSheet.create({
  stateContainer: { padding: 16 },
  loadingTextSpacing: { marginTop: 8 },
});

const QuizActivePage = (): React.ReactElement => {
  const theme = useSelector((s: RootState) => s.ui.theme);
  const colors = theme === ThemeMode.Dark ? themePalette.dark : themePalette.light;
  const styles = useDynamicFormStyles();

  const { data, isLoading, isError, refetch } = useQuestionerWebQuestionerTemplatesGetActiveTemplate();
  const createCompleted = useQuestionerWebCompletedQuestionersCreate();

  const quizForm = useQuizForm(data, createCompleted, refetch, FM);

  const colorStyles = useMemo(
    () => ({
      container: { backgroundColor: colors.background },
      loadingText: { color: colors.subtext },
      errorText: { color: colors.error },
      subtext: { color: colors.subtext },
    }),
    [colors.background, colors.error, colors.subtext],
  );

  const hasFormWithQuestions = isValueDefined(quizForm.form) && quizForm.form.questions.length > 0;
  const hasFormWithEmptyQuestions = isValueDefined(quizForm.form) && quizForm.form.questions.length === 0;
  const shouldShowForm = !isLoading && hasFormWithQuestions;
  const shouldShowEmptyState = !isLoading && hasFormWithEmptyQuestions;

  return (
    <View style={[layoutStyles.container, colorStyles.container]}>
      <PageHeaderWithActions
        refreshing={isLoading}
        refreshLabel={FM('common.refresh')}
        title={FM('quizActive.title')}
        onRefresh={() => {
          refetch().catch(() => {});
        }}
      />

      {isLoading ? (
        <View style={screenStyles.stateContainer}>
          <ActivityIndicator />
          <Text style={[screenStyles.loadingTextSpacing, colorStyles.loadingText]}>
            {FM('quizActive.loading')}
          </Text>
        </View>
      ) : null}

      {!isLoading && isError ? (
        <View style={screenStyles.stateContainer}>
          <Text style={colorStyles.errorText}>{FM('quizActive.loadError')}</Text>
        </View>
      ) : null}

      {shouldShowForm && quizForm.form ? (
        <QuizContent
          currentPage={quizForm.currentPage}
          currentQuestions={quizForm.currentQuestions}
          errors={quizForm.errors}
          form={quizForm.form}
          handleBack={quizForm.handleBack}
          handleNext={quizForm.handleNext}
          pageOpacity={quizForm.pageOpacity}
          scrollRef={quizForm.scrollRef}
          shouldSkip={quizForm.shouldSkip}
          styles={styles}
          submitting={quizForm.submitting}
          t={FM}
          totalPages={quizForm.totalPages}
          updateAnswer={quizForm.updateAnswer}
        />
      ) : null}

      {shouldShowEmptyState ? (
        <View style={screenStyles.stateContainer}>
          <Text style={colorStyles.subtext}>{FM('quizActive.empty')}</Text>
        </View>
      ) : null}

      <ThankYouOverlay
        backgroundColor={String(colors.background)}
        textColor={String(colors.text)}
        thankYouText={FM('quizActive.thankYou')}
        visible={quizForm.showThankYou}
        onAnimationComplete={quizForm.onThankYouComplete}
      />
    </View>
  );
};

export default QuizActivePage;
