# Development Dockerfile for Katalogos (Expo)
FROM node:20-alpine
LABEL org.opencontainers.image.authors="dloizides.com"
LABEL org.opencontainers.image.vendor="dloizides.com"
LABEL org.opencontainers.image.title="Katalogos.Dev"
LABEL built-by="dloizides.com"
WORKDIR /app
COPY . .
RUN npm install --frozen-lockfile
EXPOSE 8084 19000 19001 19002
CMD ["npm", "run", "start"]
