const path = require('path');
const fs = require('fs');
const { getDefaultConfig } = require('expo/metro-config');

const projectRoot = __dirname;
const config = getDefaultConfig(projectRoot);

// `@dloizides/auth-web` was a `file:` workspace package during unified-auth
// Phase 1c — Metro had a watch-folder + extraNodeModules + singleton-resolver
// chain to bundle its source. Phase 5 (2026-05-23) flipped it to the published
// `^1.2.1` npm version, so that whole apparatus was deleted: Metro now resolves
// it from `node_modules` like any other dep. The kefi-web simplification of the
// same day is the reference.

// Exclude build-output directories from Metro's file watcher. On Windows,
// Metro's FallbackWatcher (used when Watchman is absent) follows symlinks
// inside these dirs and produces UNKNOWN lstat errors when
// unstable_enableSymlinks:true causes it to construct self-referential paths.
const blockListPatterns = [
  path.join(projectRoot, 'dist'),
  path.join(projectRoot, 'coverage'),
  path.join(projectRoot, 'lighthouse-reports'),
].map((p) => new RegExp(`^${p.replace(/\\/g, '\\\\').replace(/\//g, '[\\\\/]')}.*`));

// Path to host app's React modules - these must be used by all packages.
const hostReactPath = path.join(projectRoot, 'node_modules', 'react');
const hostReactDomPath = path.join(projectRoot, 'node_modules', 'react-dom');

config.resolver = {
  ...config.resolver,
  unstable_enableSymlinks: true,
  unstable_enablePackageExports: true,
  blockList: blockListPatterns,
  nodeModulesPaths: [
    path.join(projectRoot, 'node_modules'),
  ],
  extraNodeModules: {
    // Local @baseclient/* micro-frontend module packages (still file: deps).
    '@baseclient/core': path.join(projectRoot, 'packages', 'core', 'src'),
    '@baseclient/identity-module': path.join(projectRoot, 'packages', 'identity-module', 'src'),
    '@baseclient/questioner-module': path.join(projectRoot, 'packages', 'questioner-module', 'src'),
    '@baseclient/onlinemenu-module': path.join(projectRoot, 'packages', 'onlinemenu-module', 'src'),
    '@onlinemenu/identity-client': path.join(projectRoot, 'packages', 'identity-client', 'dist'),
  },
  resolveRequest: (context, moduleName, platform) => {
    // Resolve @/ alias to src/ directory.
    if (typeof moduleName === 'string' && moduleName.startsWith('@/')) {
      const subPath = moduleName.slice(2);
      const basePath = path.join(projectRoot, 'src', subPath);
      for (const ext of ['.ts', '.tsx', '.js', '.jsx', '.json', '/index.ts', '/index.tsx', '/index.js']) {
        const filePath = basePath + ext;
        if (fs.existsSync(filePath)) {
          return { filePath, type: 'sourceFile' };
        }
      }
    }
    // Force React imports to the host copy so the local @baseclient/* file:
    // packages don't bundle their own (would break hooks across the boundary).
    if (moduleName === 'react' || moduleName.startsWith('react/')) {
      return {
        filePath: moduleName === 'react'
          ? path.join(hostReactPath, 'index.js')
          : path.join(hostReactPath, moduleName.replace('react/', '') + '.js'),
        type: 'sourceFile',
      };
    }
    if (moduleName === 'react-dom' || moduleName.startsWith('react-dom/')) {
      return {
        filePath: moduleName === 'react-dom'
          ? path.join(hostReactDomPath, 'index.js')
          : path.join(hostReactDomPath, moduleName.replace('react-dom/', '') + '.js'),
        type: 'sourceFile',
      };
    }
    // Case-insensitive matching for autoGeneratedHooks imports — Windows fs is
    // case-insensitive but the bundler isn't.
    if (typeof moduleName === 'string' && moduleName.includes('autoGeneratedHooks')) {
      try {
        const rel = moduleName.replace(/^\.?\/?/, '');
        const absDir = path.resolve(projectRoot, path.dirname(rel));
        const requestedBase = path.basename(rel);
        if (fs.existsSync(absDir)) {
          const children = fs.readdirSync(absDir);
          const match = children.find((c) => c.toLowerCase().startsWith(requestedBase.toLowerCase()));
          if (match) {
            const normalized = path.join(path.dirname(rel), match).replace(/\\/g, '/');
            return context.resolveRequest(context, normalized, platform);
          }
        }
      } catch {
        // ignore and continue
      }
    }
    return context.resolveRequest(context, moduleName, platform);
  },
};

module.exports = config;
