const { defineConfig } = require('orval');
const { defineOrvalConfig } = require('@dloizides/orval-preset');

/**
 * Shared 6-API Orval setup (onlineMenu / identity / questioner / content /
 * payment / notification) lives in `@dloizides/orval-preset`. This app supplies
 * only its own paths:
 *  - `swaggerDir`  : per-app OpenAPI inputs (API versions differ per app).
 *  - `outDir`      : generated client dirs (per-app, gitignored).
 *  - `mutatorPath` : local mutator shims that re-export from the package, so the
 *                    generated hooks keep a stable import path.
 */
module.exports = defineConfig(
  defineOrvalConfig({
    swaggerDir: './src/server/swagger',
    outDir: './src/server/autoGeneratedHooks',
    mutatorPath: './src/server/mutators',
  }),
);
