/**
 * Tests for no-product-imports-in-shared ESLint rule.
 *
 * Run: node --test eslint-plugins/no-product-imports-in-shared.test.mjs
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { RuleTester } from 'eslint';
import plugin from './no-product-imports-in-shared.mjs';

const rule = plugin.rules['no-product-imports-in-shared'];

const ruleTester = new RuleTester({
  languageOptions: {
    ecmaVersion: 2022,
    sourceType: 'module',
  },
});

describe('no-product-imports-in-shared', () => {
  it('passes valid cases and catches invalid cases', () => {
    ruleTester.run('no-product-imports-in-shared', rule, {
      valid: [
        // Allowed: @baseclient/core in src/components/
        {
          code: "import { Button } from '@baseclient/core';",
          filename: '/project/BaseClient/src/components/Shared/MyComponent.tsx',
        },
        // Allowed: @baseclient/identity-client in src/components/
        {
          code: "import { useAuth } from '@baseclient/identity-client';",
          filename: '/project/BaseClient/src/components/Auth/LoginForm.tsx',
        },
        // Allowed: @baseclient/identity-module in src/components/
        {
          code: "import { IDENTITY } from '@baseclient/identity-module';",
          filename: '/project/BaseClient/src/components/Auth/LoginForm.tsx',
        },
        // Allowed: relative import within src/components/
        {
          code: "import { helper } from '../Shared/utils';",
          filename: '/project/BaseClient/src/components/Dashboard/Dashboard.tsx',
        },
        // Allowed: external package
        {
          code: "import React from 'react';",
          filename: '/project/BaseClient/src/components/Shared/MyComponent.tsx',
        },
        // Allowed: product import OUTSIDE src/components/ (in packages/)
        {
          code: "import { X } from '@baseclient/onlinemenu-module';",
          filename: '/project/BaseClient/packages/onlinemenu-module/src/index.ts',
        },
        // Allowed: product import in src/features/
        {
          code: "import { X } from '@baseclient/questioner-module';",
          filename: '/project/BaseClient/src/features/showcase/Demo.tsx',
        },
        // Allowed: identity auto-generated hooks in components
        {
          code: "import { useX } from '../../server/autoGeneratedHooks/identity/users';",
          filename: '/project/BaseClient/src/components/Users/UserList.tsx',
        },
        // Allowed: no source in export declaration
        {
          code: "export const MY_CONST = 42;",
          filename: '/project/BaseClient/src/components/Shared/constants.ts',
        },
      ],

      invalid: [
        // Banned: @baseclient/onlinemenu-module in src/components/
        {
          code: "import { X } from '@baseclient/onlinemenu-module';",
          filename: '/project/BaseClient/src/components/OnlineMenus/Editor.tsx',
          errors: [{ messageId: 'productImportInShared' }],
        },
        // Banned: @baseclient/questioner-module in src/components/
        {
          code: "import { Y } from '@baseclient/questioner-module';",
          filename: '/project/BaseClient/src/components/Dashboard/Dashboard.tsx',
          errors: [{ messageId: 'productImportInShared' }],
        },
        // Banned: named import from product module (type-only uses same AST path)
        {
          code: "import { MenuDto } from '@baseclient/onlinemenu-module';",
          filename: '/project/BaseClient/src/components/OnlineMenus/Editor.tsx',
          errors: [{ messageId: 'productImportInShared' }],
        },
        // Banned: auto-generated hooks for onlinemenu
        {
          code: "import { useMenu } from '../../server/autoGeneratedHooks/onlinemenu/menus';",
          filename: '/project/BaseClient/src/components/OnlineMenus/Editor.tsx',
          errors: [{ messageId: 'productImportInShared' }],
        },
        // Banned: auto-generated hooks for questioner
        {
          code: "import { useTemplate } from '../../../server/autoGeneratedHooks/questioner/templates';",
          filename: '/project/BaseClient/src/components/QuestionerTemplates/List.tsx',
          errors: [{ messageId: 'productImportInShared' }],
        },
        // Banned: auto-generated hooks for content
        {
          code: "import { useContent } from '../../server/autoGeneratedHooks/content/items';",
          filename: '/project/BaseClient/src/components/Content/Page.tsx',
          errors: [{ messageId: 'productImportInShared' }],
        },
        // Banned: auto-generated hooks for notification
        {
          code: "import { useNotif } from '../../server/autoGeneratedHooks/notification/send';",
          filename: '/project/BaseClient/src/components/Notifications/Bell.tsx',
          errors: [{ messageId: 'productImportInShared' }],
        },
        // Banned: tenant-theme-editor-module
        {
          code: "import { X } from '@baseclient/tenant-theme-editor-module';",
          filename: '/project/BaseClient/src/components/TenantThemeEditor/Editor.tsx',
          errors: [{ messageId: 'productImportInShared' }],
        },
        // Banned: export re-exporting from product module
        {
          code: "export { X } from '@baseclient/onlinemenu-module';",
          filename: '/project/BaseClient/src/components/OnlineMenus/index.ts',
          errors: [{ messageId: 'productImportInShared' }],
        },
      ],
    });
  });

  it('does not flag files outside src/components/', () => {
    ruleTester.run('no-product-imports-in-shared (outside components)', rule, {
      valid: [
        {
          code: "import { X } from '@baseclient/onlinemenu-module';",
          filename: '/project/BaseClient/src/store/menuSlice.ts',
        },
        {
          code: "import { Y } from '../../server/autoGeneratedHooks/questioner/templates';",
          filename: '/project/BaseClient/src/hooks/useTemplates.ts',
        },
      ],
      invalid: [],
    });
  });
});

// Run with node:test
console.log('Tests passed');
