/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Content.Web
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  CompleteUploadRequest,
  CompleteUploadResponse,
  ContentDto,
  ContentWebContentListContentParams,
  GetContentUrlResponse,
  GetPublicContentUrlResponse,
  ListContentResponse,
  RequestUploadUrlRequest,
  RequestUploadUrlResponse,
} from '.././models';

import { contentInstance } from '../../../mutators/contentMutator';

/**
 * Notifies the service that the client has finished uploading to the presigned URL
 * @summary Complete an upload
 */
export const contentWebUploadCompleteUpload = (
  completeUploadRequest: CompleteUploadRequest,
  signal?: AbortSignal
) => {
  return contentInstance<CompleteUploadResponse>({
    url: `/api/v1/content/upload-complete`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: completeUploadRequest,
    signal,
  });
};

export const getContentWebUploadCompleteUploadMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contentWebUploadCompleteUpload>>,
    TError,
    { data: CompleteUploadRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof contentWebUploadCompleteUpload>>,
  TError,
  { data: CompleteUploadRequest },
  TContext
> => {
  const mutationKey = ['contentWebUploadCompleteUpload'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof contentWebUploadCompleteUpload>>,
    { data: CompleteUploadRequest }
  > = (props) => {
    const { data } = props ?? {};

    return contentWebUploadCompleteUpload(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ContentWebUploadCompleteUploadMutationResult = NonNullable<
  Awaited<ReturnType<typeof contentWebUploadCompleteUpload>>
>;
export type ContentWebUploadCompleteUploadMutationBody = CompleteUploadRequest;
export type ContentWebUploadCompleteUploadMutationError = void;

/**
 * @summary Complete an upload
 */
export const useContentWebUploadCompleteUpload = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof contentWebUploadCompleteUpload>>,
      TError,
      { data: CompleteUploadRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof contentWebUploadCompleteUpload>>,
  TError,
  { data: CompleteUploadRequest },
  TContext
> => {
  const mutationOptions = getContentWebUploadCompleteUploadMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Returns a presigned URL for direct upload to S3/RustFS storage
 * @summary Request a presigned URL for uploading content
 */
export const contentWebUploadRequestUploadUrl = (
  requestUploadUrlRequest: RequestUploadUrlRequest,
  signal?: AbortSignal
) => {
  return contentInstance<RequestUploadUrlResponse>({
    url: `/api/v1/content/upload-url`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: requestUploadUrlRequest,
    signal,
  });
};

export const getContentWebUploadRequestUploadUrlMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contentWebUploadRequestUploadUrl>>,
    TError,
    { data: RequestUploadUrlRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof contentWebUploadRequestUploadUrl>>,
  TError,
  { data: RequestUploadUrlRequest },
  TContext
> => {
  const mutationKey = ['contentWebUploadRequestUploadUrl'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof contentWebUploadRequestUploadUrl>>,
    { data: RequestUploadUrlRequest }
  > = (props) => {
    const { data } = props ?? {};

    return contentWebUploadRequestUploadUrl(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ContentWebUploadRequestUploadUrlMutationResult = NonNullable<
  Awaited<ReturnType<typeof contentWebUploadRequestUploadUrl>>
>;
export type ContentWebUploadRequestUploadUrlMutationBody = RequestUploadUrlRequest;
export type ContentWebUploadRequestUploadUrlMutationError = void;

/**
 * @summary Request a presigned URL for uploading content
 */
export const useContentWebUploadRequestUploadUrl = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof contentWebUploadRequestUploadUrl>>,
      TError,
      { data: RequestUploadUrlRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof contentWebUploadRequestUploadUrl>>,
  TError,
  { data: RequestUploadUrlRequest },
  TContext
> => {
  const mutationOptions = getContentWebUploadRequestUploadUrlMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Soft deletes a content item
 * @summary Delete content
 */
export const contentWebContentDeleteContent = (id: string) => {
  return contentInstance<void>({ url: `/api/v1/content/${id}`, method: 'DELETE' });
};

export const getContentWebContentDeleteContentMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contentWebContentDeleteContent>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof contentWebContentDeleteContent>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['contentWebContentDeleteContent'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof contentWebContentDeleteContent>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return contentWebContentDeleteContent(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type ContentWebContentDeleteContentMutationResult = NonNullable<
  Awaited<ReturnType<typeof contentWebContentDeleteContent>>
>;

export type ContentWebContentDeleteContentMutationError = void;

/**
 * @summary Delete content
 */
export const useContentWebContentDeleteContent = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof contentWebContentDeleteContent>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof contentWebContentDeleteContent>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getContentWebContentDeleteContentMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Returns metadata for a content item including variants
 * @summary Get content metadata
 */
export const contentWebContentGetContent = (id: string, signal?: AbortSignal) => {
  return contentInstance<ContentDto>({ url: `/api/v1/content/${id}`, method: 'GET', signal });
};

export const getContentWebContentGetContentQueryKey = (id?: string) => {
  return [`/api/v1/content/${id}`] as const;
};

export const getContentWebContentGetContentQueryOptions = <
  TData = Awaited<ReturnType<typeof contentWebContentGetContent>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof contentWebContentGetContent>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getContentWebContentGetContentQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof contentWebContentGetContent>>> = ({
    signal,
  }) => contentWebContentGetContent(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof contentWebContentGetContent>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ContentWebContentGetContentQueryResult = NonNullable<
  Awaited<ReturnType<typeof contentWebContentGetContent>>
>;
export type ContentWebContentGetContentQueryError = void;

export function useContentWebContentGetContent<
  TData = Awaited<ReturnType<typeof contentWebContentGetContent>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof contentWebContentGetContent>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof contentWebContentGetContent>>,
          TError,
          Awaited<ReturnType<typeof contentWebContentGetContent>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useContentWebContentGetContent<
  TData = Awaited<ReturnType<typeof contentWebContentGetContent>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof contentWebContentGetContent>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof contentWebContentGetContent>>,
          TError,
          Awaited<ReturnType<typeof contentWebContentGetContent>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useContentWebContentGetContent<
  TData = Awaited<ReturnType<typeof contentWebContentGetContent>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof contentWebContentGetContent>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get content metadata
 */

export function useContentWebContentGetContent<
  TData = Awaited<ReturnType<typeof contentWebContentGetContent>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof contentWebContentGetContent>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getContentWebContentGetContentQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Returns a direct URL (public) or presigned URL (private) for accessing the content
 * @summary Get content access URL
 */
export const contentWebContentGetContentUrl = (id: string, signal?: AbortSignal) => {
  return contentInstance<GetContentUrlResponse>({
    url: `/api/v1/content/${id}/url`,
    method: 'GET',
    signal,
  });
};

export const getContentWebContentGetContentUrlQueryKey = (id?: string) => {
  return [`/api/v1/content/${id}/url`] as const;
};

export const getContentWebContentGetContentUrlQueryOptions = <
  TData = Awaited<ReturnType<typeof contentWebContentGetContentUrl>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof contentWebContentGetContentUrl>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getContentWebContentGetContentUrlQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof contentWebContentGetContentUrl>>> = ({
    signal,
  }) => contentWebContentGetContentUrl(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof contentWebContentGetContentUrl>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ContentWebContentGetContentUrlQueryResult = NonNullable<
  Awaited<ReturnType<typeof contentWebContentGetContentUrl>>
>;
export type ContentWebContentGetContentUrlQueryError = void;

export function useContentWebContentGetContentUrl<
  TData = Awaited<ReturnType<typeof contentWebContentGetContentUrl>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof contentWebContentGetContentUrl>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof contentWebContentGetContentUrl>>,
          TError,
          Awaited<ReturnType<typeof contentWebContentGetContentUrl>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useContentWebContentGetContentUrl<
  TData = Awaited<ReturnType<typeof contentWebContentGetContentUrl>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof contentWebContentGetContentUrl>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof contentWebContentGetContentUrl>>,
          TError,
          Awaited<ReturnType<typeof contentWebContentGetContentUrl>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useContentWebContentGetContentUrl<
  TData = Awaited<ReturnType<typeof contentWebContentGetContentUrl>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof contentWebContentGetContentUrl>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get content access URL
 */

export function useContentWebContentGetContentUrl<
  TData = Awaited<ReturnType<typeof contentWebContentGetContentUrl>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof contentWebContentGetContentUrl>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getContentWebContentGetContentUrlQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Returns a direct URL for accessing public content. Only works for content marked as public.
 * @summary Get public content URL
 */
export const contentWebContentGetPublicContentUrl = (id: string, signal?: AbortSignal) => {
  return contentInstance<GetPublicContentUrlResponse>({
    url: `/api/v1/content/${id}/public-url`,
    method: 'GET',
    signal,
  });
};

export const getContentWebContentGetPublicContentUrlQueryKey = (id?: string) => {
  return [`/api/v1/content/${id}/public-url`] as const;
};

export const getContentWebContentGetPublicContentUrlQueryOptions = <
  TData = Awaited<ReturnType<typeof contentWebContentGetPublicContentUrl>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof contentWebContentGetPublicContentUrl>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getContentWebContentGetPublicContentUrlQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof contentWebContentGetPublicContentUrl>>
  > = ({ signal }) => contentWebContentGetPublicContentUrl(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof contentWebContentGetPublicContentUrl>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ContentWebContentGetPublicContentUrlQueryResult = NonNullable<
  Awaited<ReturnType<typeof contentWebContentGetPublicContentUrl>>
>;
export type ContentWebContentGetPublicContentUrlQueryError = unknown;

export function useContentWebContentGetPublicContentUrl<
  TData = Awaited<ReturnType<typeof contentWebContentGetPublicContentUrl>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof contentWebContentGetPublicContentUrl>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof contentWebContentGetPublicContentUrl>>,
          TError,
          Awaited<ReturnType<typeof contentWebContentGetPublicContentUrl>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useContentWebContentGetPublicContentUrl<
  TData = Awaited<ReturnType<typeof contentWebContentGetPublicContentUrl>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof contentWebContentGetPublicContentUrl>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof contentWebContentGetPublicContentUrl>>,
          TError,
          Awaited<ReturnType<typeof contentWebContentGetPublicContentUrl>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useContentWebContentGetPublicContentUrl<
  TData = Awaited<ReturnType<typeof contentWebContentGetPublicContentUrl>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof contentWebContentGetPublicContentUrl>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get public content URL
 */

export function useContentWebContentGetPublicContentUrl<
  TData = Awaited<ReturnType<typeof contentWebContentGetPublicContentUrl>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof contentWebContentGetPublicContentUrl>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getContentWebContentGetPublicContentUrlQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Returns a paginated list of content items with optional category filter
 * @summary List content items
 */
export const contentWebContentListContent = (
  params: ContentWebContentListContentParams,
  signal?: AbortSignal
) => {
  return contentInstance<ListContentResponse>({
    url: `/api/v1/content`,
    method: 'GET',
    params,
    signal,
  });
};

export const getContentWebContentListContentQueryKey = (
  params?: ContentWebContentListContentParams
) => {
  return [`/api/v1/content`, ...(params ? [params] : [])] as const;
};

export const getContentWebContentListContentQueryOptions = <
  TData = Awaited<ReturnType<typeof contentWebContentListContent>>,
  TError = void,
>(
  params: ContentWebContentListContentParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof contentWebContentListContent>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getContentWebContentListContentQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof contentWebContentListContent>>> = ({
    signal,
  }) => contentWebContentListContent(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof contentWebContentListContent>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ContentWebContentListContentQueryResult = NonNullable<
  Awaited<ReturnType<typeof contentWebContentListContent>>
>;
export type ContentWebContentListContentQueryError = void;

export function useContentWebContentListContent<
  TData = Awaited<ReturnType<typeof contentWebContentListContent>>,
  TError = void,
>(
  params: ContentWebContentListContentParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof contentWebContentListContent>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof contentWebContentListContent>>,
          TError,
          Awaited<ReturnType<typeof contentWebContentListContent>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useContentWebContentListContent<
  TData = Awaited<ReturnType<typeof contentWebContentListContent>>,
  TError = void,
>(
  params: ContentWebContentListContentParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof contentWebContentListContent>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof contentWebContentListContent>>,
          TError,
          Awaited<ReturnType<typeof contentWebContentListContent>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useContentWebContentListContent<
  TData = Awaited<ReturnType<typeof contentWebContentListContent>>,
  TError = void,
>(
  params: ContentWebContentListContentParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof contentWebContentListContent>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List content items
 */

export function useContentWebContentListContent<
  TData = Awaited<ReturnType<typeof contentWebContentListContent>>,
  TError = void,
>(
  params: ContentWebContentListContentParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof contentWebContentListContent>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getContentWebContentListContentQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
