import { useAuth } from '@/auth/AuthProvider';
import { useIdentityServiceAPITenantsGetTenantById } from '@/server/autoGeneratedHooks/identity/tenants/tenants';

/**
 * Resolves the currently signed-in user's tenant via the IdentityService
 * `GET /api/v1/tenants/:tenantId` endpoint.
 *
 * The Keycloak `tenantId` claim is exposed through `useAuth().userInfo`. The
 * tenant `name` (and other tenant fields) are only available server-side, so
 * this hook fetches them lazily.
 *
 * The autogenerated query uses `enabled: !!tenantId`, so when no tenant is
 * present (logged-out user, super-admin without a tenant assignment) the
 * network call is skipped and `tenantName` is `null`.
 */
interface UseCurrentTenantResult {
  /** Resolved tenant name, or null if unavailable / still loading. */
  tenantName: string | null;
  isLoading: boolean;
}

export function useCurrentTenant(): UseCurrentTenantResult {
  const { userInfo } = useAuth();
  const tenantId = userInfo?.tenantId ?? '';
  const query = useIdentityServiceAPITenantsGetTenantById(tenantId);

  const rawName = query.data?.name;
  const tenantName = typeof rawName === 'string' && rawName.trim() !== '' ? rawName : null;

  return {
    tenantName,
    isLoading: query.isLoading && tenantId !== '',
  };
}
