import { queryClient } from '@/lib/queryClient';
import {
  getIdentityServiceAPIMeGetBusinessProfileQueryOptions,
  getIdentityServiceAPIMeGetPreferencesQueryOptions,
} from '@/server/autoGeneratedHooks/identity/me/me';
import { getOnlineMenuWebMenuListQueryOptions } from '@/server/autoGeneratedHooks/onlinemenu/tenantmenus/tenantmenus';

export function prefetchDashboardData(): void {
  queryClient
    .prefetchQuery(getIdentityServiceAPIMeGetPreferencesQueryOptions())
    .catch(() => undefined);

  queryClient
    .prefetchQuery(getIdentityServiceAPIMeGetBusinessProfileQueryOptions())
    .catch(() => undefined);

  queryClient
    .prefetchQuery(getOnlineMenuWebMenuListQueryOptions())
    .catch(() => undefined);
}
