/**
 * Prefetches dashboard data into the React Query cache.
 *
 * Call this immediately after a successful login (before navigation) so
 * that by the time the dashboard mounts, the critical API responses are
 * already cached and the user sees content instead of spinners.
 *
 * Uses `queryClient.prefetchQuery` which is fire-and-forget -- failures
 * are silently swallowed since the dashboard hooks will retry on mount.
 *
 * Katalogos is the OnlineMenu product. The dashboard never reads
 * questioner data -- prefetching it would (a) make a wasted network call
 * to questioner-api.dloizides.com, and (b) leak the cross-realm wall
 * (the questioner API rejects onlinemenu-realm tokens with 401, which
 * pollutes error monitoring). The questioner prefetch was removed as
 * part of the Phase-3 product feature-strip.
 */
import { queryClient } from '@/lib/queryClient';
import {
  getIdentityServiceAPIMeGetBusinessProfileQueryOptions,
  getIdentityServiceAPIMeGetPreferencesQueryOptions,
} from '@/server/autoGeneratedHooks/identity/me/me';
import { getOnlineMenuWebMenuListQueryOptions } from '@/server/autoGeneratedHooks/onlinemenu/tenantmenus/tenantmenus';

export function prefetchDashboardData(): void {
  // User preferences (needed by welcome wizard + setup checklist)
  queryClient
    .prefetchQuery(getIdentityServiceAPIMeGetPreferencesQueryOptions())
    .catch(() => undefined);

  // Business profile (needed by setup checklist + profile nudge)
  queryClient
    .prefetchQuery(getIdentityServiceAPIMeGetBusinessProfileQueryOptions())
    .catch(() => undefined);

  // Menu list (needed by dashboard cards + setup checklist).
  // Katalogos is the OnlineMenu product, so this prefetch is unconditional.
  queryClient
    .prefetchQuery(getOnlineMenuWebMenuListQueryOptions())
    .catch(() => undefined);
}
