import React from 'react';

import { StyleSheet, Text, TextInput, View } from 'react-native';

import { FM } from '@/localization/helpers';
import type { Answer, QuestionAnswer } from '@/server/autoGeneratedHooks/questioner/models';

interface Props {
  answer?: QuestionAnswer | null;
  onChange: (a?: QuestionAnswer | null) => void;
}

const styles = StyleSheet.create({
  input: {
    padding: 6,
    marginTop: 4,
  },
  labelSpacing: {
    marginTop: 6,
  },
});

function normalizeAnswer(answer: QuestionAnswer | undefined): Answer {
  return answer ?? {};
}

const AnswerEditor = ({ answer, onChange }: Props): React.ReactElement => {

  const normalizedAnswer = normalizeAnswer(answer);
  const stringValue = normalizedAnswer.stringValue ?? '';
  const numericValue = normalizedAnswer.numericValue ?? '';
  const boolValue = normalizedAnswer.boolValue ?? false;
  const multiValues = normalizedAnswer.multiValues ?? [];

  return (
    <View>
      <Text>{FM('quizTemplates.answerString')}</Text>
      <TextInput
        accessibilityHint={FM('quizTemplates.answerStringInputHint')}
        accessibilityLabel={FM('quizTemplates.answerStringInputLabel')}
        style={styles.input}
        value={String(stringValue)}
        onChangeText={(v) => onChange({ ...normalizedAnswer, stringValue: v })}
      />

      <Text style={styles.labelSpacing}>{FM('quizTemplates.answerNumber')}</Text>
      <TextInput
        accessibilityHint={FM('quizTemplates.answerNumberInputHint')}
        accessibilityLabel={FM('quizTemplates.answerNumberInputLabel')}
        style={styles.input}
        value={String(numericValue)}
        onChangeText={(v) => onChange({ ...normalizedAnswer, numericValue: Number(v) })}
      />

      <Text style={styles.labelSpacing}>{FM('quizTemplates.answerBool')}</Text>
      <TextInput
        accessibilityHint={FM('quizTemplates.answerBoolInputHint')}
        accessibilityLabel={FM('quizTemplates.answerBoolInputLabel')}
        editable={false}
        style={styles.input}
        value={String(boolValue)}
      />

      <Text style={styles.labelSpacing}>{FM('quizTemplates.answerMulti')}</Text>
      <TextInput
        accessibilityHint={FM('quizTemplates.answerMultiInputHint')}
        accessibilityLabel={FM('quizTemplates.answerMultiInputLabel')}
        style={styles.input}
        value={multiValues.join(',')}
        onChangeText={(v) =>
          onChange({
            ...normalizedAnswer,
            multiValues: v.split(',').map((s) => s.trim()),
          })}
      />
    </View>
  );
};

export default AnswerEditor;
