import React from 'react';

import { FlatList, StyleSheet, Text, TouchableOpacity, View } from 'react-native';

import { SvgIcon } from '@/components/Icons';
import { FM } from '@/localization/helpers';
import type { Question } from '@/server/autoGeneratedHooks/questioner/models';
import { useTheme } from '@/theme/hooks/useTheme';
import { layoutStyles } from '@/theme/utils/styles';

import QuestionEditor from './QuestionEditor';

const RADIX_BASE_36 = 36;
const RANDOM_SUFFIX_START = 2;
const RANDOM_SUFFIX_END = 7;

const styles = StyleSheet.create({
  reorderRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconButtonSpacingRight: {
    marginRight: 8,
  },
  removeButtonSpacingLeft: {
    marginLeft: 6,
  },
});

interface Props {
  questions?: Question[];
  onChange: (questions: Question[]) => void;
  enableAnswerSection: boolean;
}

function generateQuestionId(): string {
  const suffix = Math.random().toString(RADIX_BASE_36).slice(RANDOM_SUFFIX_START, RANDOM_SUFFIX_END);
  return `q-${Date.now()}-${suffix}`;
}

const QuestionList = ({ questions = [], onChange, enableAnswerSection }: Props): React.ReactElement => {
  const { theme } = useTheme();
  const primary = theme.palette.primary['500'];
  const errorColor = theme.semantic.error['500'];

  function handleAdd(): void {
    const next: Question = {
      id: generateQuestionId(),
      name: FM('quizTemplates.newQuestion'),
      type: 0,
      options: [],
      page: 0,
      isRequired: false,
      order: questions.length + 1,
    };
    onChange([...questions, next]);
  }

  function handleUpdate(idx: number, q: Question): void {
    const copy = [...questions];
    copy[idx] = q;
    onChange(copy);
  }

  function handleRemove(idx: number): void {
    const copy = [...questions];
    copy.splice(idx, 1);
    onChange(copy.map((q, i) => ({ ...q, order: i + 1 })));
  }

  function moveUp(idx: number): void {
    if (idx <= 0) return;
    const copy = [...questions];
    const tmp = copy[idx - 1];
    copy[idx - 1] = copy[idx];
    copy[idx] = tmp;
    onChange(copy.map((q, i) => ({ ...q, order: i + 1 })));
  }

  function moveDown(idx: number): void {
    if (idx >= questions.length - 1) return;
    const copy = [...questions];
    const tmp = copy[idx + 1];
    copy[idx + 1] = copy[idx];
    copy[idx] = tmp;
    onChange(copy.map((q, i) => ({ ...q, order: i + 1 })));
  }

  const controlTextStyle = React.useMemo(() => ({ color: primary }), [primary]);
  const removeTextStyle = React.useMemo(() => ({ color: errorColor }), [errorColor]);

  return (
    <View>
      <FlatList
        data={questions}
        keyExtractor={(it, index) => it.id ?? String(index)}
        renderItem={({ item, index }) => (
          <View style={layoutStyles.itemSpacing}>
            <QuestionEditor enableAnswerSection={enableAnswerSection} question={item} onChange={(q) => handleUpdate(index, q)} />
            <View style={[styles.reorderRow, layoutStyles.itemSpacingSmall]}>
              <TouchableOpacity accessibilityRole="button" style={styles.iconButtonSpacingRight} onPress={() => moveUp(index)}>
                <SvgIcon color={primary} name="arrowUp" size={16} />
              </TouchableOpacity>
              <TouchableOpacity accessibilityRole="button" style={styles.iconButtonSpacingRight} onPress={() => moveDown(index)}>
                <SvgIcon color={primary} name="arrowDown" size={16} />
              </TouchableOpacity>
              <TouchableOpacity accessibilityRole="button" style={styles.removeButtonSpacingLeft} onPress={() => handleRemove(index)}>
                <Text style={removeTextStyle}>{FM('quizTemplates.removeQuestion')}</Text>
              </TouchableOpacity>
            </View>
          </View>
        )}
      />

      <TouchableOpacity accessibilityRole="button" style={layoutStyles.sectionSpacing} onPress={handleAdd}>
        <Text style={controlTextStyle}>{FM('quizTemplates.addQuestion')}</Text>
      </TouchableOpacity>
    </View>
  );
};

export default QuestionList;
