/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * IdentityService API
 * Authentication, User Management, Tenant Management, and API Key Management
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  IdentityServiceAPIAuthGetAuthMethodsResponse,
  IdentityServiceAPIAuthLoginRequest,
  IdentityServiceAPIAuthLoginResponse,
  IdentityServiceAPIAuthLogoutRequest,
  IdentityServiceAPIAuthLogoutResponse,
  IdentityServiceAPIAuthRefreshRequest,
  IdentityServiceAPIAuthRefreshResponse,
  IdentityServiceAPIAuthSendOtpRequest,
  IdentityServiceAPIAuthSendOtpResponse,
  IdentityServiceAPIAuthVerifyOtpRequest,
  IdentityServiceAPIAuthVerifyOtpResponse,
} from '.././models';

import { identityInstance } from '../../../mutators/identityMutator';

export const identityServiceAPIAuthGetAuthMethods = (signal?: AbortSignal) => {
  return identityInstance<IdentityServiceAPIAuthGetAuthMethodsResponse>({
    url: `/api/v1/auth/methods`,
    method: 'GET',
    signal,
  });
};

export const getIdentityServiceAPIAuthGetAuthMethodsQueryKey = () => {
  return [`/api/v1/auth/methods`] as const;
};

export const getIdentityServiceAPIAuthGetAuthMethodsQueryOptions = <
  TData = Awaited<ReturnType<typeof identityServiceAPIAuthGetAuthMethods>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof identityServiceAPIAuthGetAuthMethods>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getIdentityServiceAPIAuthGetAuthMethodsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof identityServiceAPIAuthGetAuthMethods>>
  > = ({ signal }) => identityServiceAPIAuthGetAuthMethods(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof identityServiceAPIAuthGetAuthMethods>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type IdentityServiceAPIAuthGetAuthMethodsQueryResult = NonNullable<
  Awaited<ReturnType<typeof identityServiceAPIAuthGetAuthMethods>>
>;
export type IdentityServiceAPIAuthGetAuthMethodsQueryError = unknown;

export function useIdentityServiceAPIAuthGetAuthMethods<
  TData = Awaited<ReturnType<typeof identityServiceAPIAuthGetAuthMethods>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof identityServiceAPIAuthGetAuthMethods>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof identityServiceAPIAuthGetAuthMethods>>,
          TError,
          Awaited<ReturnType<typeof identityServiceAPIAuthGetAuthMethods>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useIdentityServiceAPIAuthGetAuthMethods<
  TData = Awaited<ReturnType<typeof identityServiceAPIAuthGetAuthMethods>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof identityServiceAPIAuthGetAuthMethods>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof identityServiceAPIAuthGetAuthMethods>>,
          TError,
          Awaited<ReturnType<typeof identityServiceAPIAuthGetAuthMethods>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useIdentityServiceAPIAuthGetAuthMethods<
  TData = Awaited<ReturnType<typeof identityServiceAPIAuthGetAuthMethods>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof identityServiceAPIAuthGetAuthMethods>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useIdentityServiceAPIAuthGetAuthMethods<
  TData = Awaited<ReturnType<typeof identityServiceAPIAuthGetAuthMethods>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof identityServiceAPIAuthGetAuthMethods>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getIdentityServiceAPIAuthGetAuthMethodsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const identityServiceAPIAuthLogin = (
  identityServiceAPIAuthLoginRequest: IdentityServiceAPIAuthLoginRequest,
  signal?: AbortSignal
) => {
  return identityInstance<IdentityServiceAPIAuthLoginResponse>({
    url: `/api/v1/auth/login`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: identityServiceAPIAuthLoginRequest,
    signal,
  });
};

export const getIdentityServiceAPIAuthLoginMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof identityServiceAPIAuthLogin>>,
    TError,
    { data: IdentityServiceAPIAuthLoginRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof identityServiceAPIAuthLogin>>,
  TError,
  { data: IdentityServiceAPIAuthLoginRequest },
  TContext
> => {
  const mutationKey = ['identityServiceAPIAuthLogin'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof identityServiceAPIAuthLogin>>,
    { data: IdentityServiceAPIAuthLoginRequest }
  > = (props) => {
    const { data } = props ?? {};

    return identityServiceAPIAuthLogin(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type IdentityServiceAPIAuthLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof identityServiceAPIAuthLogin>>
>;
export type IdentityServiceAPIAuthLoginMutationBody = IdentityServiceAPIAuthLoginRequest;
export type IdentityServiceAPIAuthLoginMutationError = unknown;

export const useIdentityServiceAPIAuthLogin = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof identityServiceAPIAuthLogin>>,
      TError,
      { data: IdentityServiceAPIAuthLoginRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof identityServiceAPIAuthLogin>>,
  TError,
  { data: IdentityServiceAPIAuthLoginRequest },
  TContext
> => {
  const mutationOptions = getIdentityServiceAPIAuthLoginMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const identityServiceAPIAuthLogout = (
  identityServiceAPIAuthLogoutRequest: IdentityServiceAPIAuthLogoutRequest,
  signal?: AbortSignal
) => {
  return identityInstance<IdentityServiceAPIAuthLogoutResponse>({
    url: `/api/v1/auth/logout`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: identityServiceAPIAuthLogoutRequest,
    signal,
  });
};

export const getIdentityServiceAPIAuthLogoutMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof identityServiceAPIAuthLogout>>,
    TError,
    { data: IdentityServiceAPIAuthLogoutRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof identityServiceAPIAuthLogout>>,
  TError,
  { data: IdentityServiceAPIAuthLogoutRequest },
  TContext
> => {
  const mutationKey = ['identityServiceAPIAuthLogout'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof identityServiceAPIAuthLogout>>,
    { data: IdentityServiceAPIAuthLogoutRequest }
  > = (props) => {
    const { data } = props ?? {};

    return identityServiceAPIAuthLogout(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type IdentityServiceAPIAuthLogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof identityServiceAPIAuthLogout>>
>;
export type IdentityServiceAPIAuthLogoutMutationBody = IdentityServiceAPIAuthLogoutRequest;
export type IdentityServiceAPIAuthLogoutMutationError = unknown;

export const useIdentityServiceAPIAuthLogout = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof identityServiceAPIAuthLogout>>,
      TError,
      { data: IdentityServiceAPIAuthLogoutRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof identityServiceAPIAuthLogout>>,
  TError,
  { data: IdentityServiceAPIAuthLogoutRequest },
  TContext
> => {
  const mutationOptions = getIdentityServiceAPIAuthLogoutMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const identityServiceAPIAuthRefresh = (
  identityServiceAPIAuthRefreshRequest: IdentityServiceAPIAuthRefreshRequest,
  signal?: AbortSignal
) => {
  return identityInstance<IdentityServiceAPIAuthRefreshResponse>({
    url: `/api/v1/auth/refresh`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: identityServiceAPIAuthRefreshRequest,
    signal,
  });
};

export const getIdentityServiceAPIAuthRefreshMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof identityServiceAPIAuthRefresh>>,
    TError,
    { data: IdentityServiceAPIAuthRefreshRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof identityServiceAPIAuthRefresh>>,
  TError,
  { data: IdentityServiceAPIAuthRefreshRequest },
  TContext
> => {
  const mutationKey = ['identityServiceAPIAuthRefresh'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof identityServiceAPIAuthRefresh>>,
    { data: IdentityServiceAPIAuthRefreshRequest }
  > = (props) => {
    const { data } = props ?? {};

    return identityServiceAPIAuthRefresh(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type IdentityServiceAPIAuthRefreshMutationResult = NonNullable<
  Awaited<ReturnType<typeof identityServiceAPIAuthRefresh>>
>;
export type IdentityServiceAPIAuthRefreshMutationBody = IdentityServiceAPIAuthRefreshRequest;
export type IdentityServiceAPIAuthRefreshMutationError = unknown;

export const useIdentityServiceAPIAuthRefresh = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof identityServiceAPIAuthRefresh>>,
      TError,
      { data: IdentityServiceAPIAuthRefreshRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof identityServiceAPIAuthRefresh>>,
  TError,
  { data: IdentityServiceAPIAuthRefreshRequest },
  TContext
> => {
  const mutationOptions = getIdentityServiceAPIAuthRefreshMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const identityServiceAPIAuthSendOtp = (
  identityServiceAPIAuthSendOtpRequest: IdentityServiceAPIAuthSendOtpRequest,
  signal?: AbortSignal
) => {
  return identityInstance<IdentityServiceAPIAuthSendOtpResponse>({
    url: `/api/v1/auth/send-otp`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: identityServiceAPIAuthSendOtpRequest,
    signal,
  });
};

export const getIdentityServiceAPIAuthSendOtpMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof identityServiceAPIAuthSendOtp>>,
    TError,
    { data: IdentityServiceAPIAuthSendOtpRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof identityServiceAPIAuthSendOtp>>,
  TError,
  { data: IdentityServiceAPIAuthSendOtpRequest },
  TContext
> => {
  const mutationKey = ['identityServiceAPIAuthSendOtp'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof identityServiceAPIAuthSendOtp>>,
    { data: IdentityServiceAPIAuthSendOtpRequest }
  > = (props) => {
    const { data } = props ?? {};

    return identityServiceAPIAuthSendOtp(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type IdentityServiceAPIAuthSendOtpMutationResult = NonNullable<
  Awaited<ReturnType<typeof identityServiceAPIAuthSendOtp>>
>;
export type IdentityServiceAPIAuthSendOtpMutationBody = IdentityServiceAPIAuthSendOtpRequest;
export type IdentityServiceAPIAuthSendOtpMutationError = unknown;

export const useIdentityServiceAPIAuthSendOtp = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof identityServiceAPIAuthSendOtp>>,
      TError,
      { data: IdentityServiceAPIAuthSendOtpRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof identityServiceAPIAuthSendOtp>>,
  TError,
  { data: IdentityServiceAPIAuthSendOtpRequest },
  TContext
> => {
  const mutationOptions = getIdentityServiceAPIAuthSendOtpMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const identityServiceAPIAuthVerifyOtp = (
  identityServiceAPIAuthVerifyOtpRequest: IdentityServiceAPIAuthVerifyOtpRequest,
  signal?: AbortSignal
) => {
  return identityInstance<IdentityServiceAPIAuthVerifyOtpResponse>({
    url: `/api/v1/auth/verify-otp`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: identityServiceAPIAuthVerifyOtpRequest,
    signal,
  });
};

export const getIdentityServiceAPIAuthVerifyOtpMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof identityServiceAPIAuthVerifyOtp>>,
    TError,
    { data: IdentityServiceAPIAuthVerifyOtpRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof identityServiceAPIAuthVerifyOtp>>,
  TError,
  { data: IdentityServiceAPIAuthVerifyOtpRequest },
  TContext
> => {
  const mutationKey = ['identityServiceAPIAuthVerifyOtp'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof identityServiceAPIAuthVerifyOtp>>,
    { data: IdentityServiceAPIAuthVerifyOtpRequest }
  > = (props) => {
    const { data } = props ?? {};

    return identityServiceAPIAuthVerifyOtp(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type IdentityServiceAPIAuthVerifyOtpMutationResult = NonNullable<
  Awaited<ReturnType<typeof identityServiceAPIAuthVerifyOtp>>
>;
export type IdentityServiceAPIAuthVerifyOtpMutationBody = IdentityServiceAPIAuthVerifyOtpRequest;
export type IdentityServiceAPIAuthVerifyOtpMutationError = unknown;

export const useIdentityServiceAPIAuthVerifyOtp = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof identityServiceAPIAuthVerifyOtp>>,
      TError,
      { data: IdentityServiceAPIAuthVerifyOtpRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof identityServiceAPIAuthVerifyOtp>>,
  TError,
  { data: IdentityServiceAPIAuthVerifyOtpRequest },
  TContext
> => {
  const mutationOptions = getIdentityServiceAPIAuthVerifyOtpMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
