/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OnlineMenu.Web
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AddCustomDomainRequest,
  CustomDomainDto,
  GetByDomainResponse,
  OnlineMenuWebCustomDomainsCheckDomainParams,
  OnlineMenuWebCustomDomainsGetByDomainParams,
} from '.././models';

import { customInstance } from '../../../mutators/onlineMenuMutator';

/**
 * @summary Adds a custom domain for the current tenant.
 */
export const onlineMenuWebCustomDomainsAdd = (
  addCustomDomainRequest: AddCustomDomainRequest,
  signal?: AbortSignal
) => {
  return customInstance<CustomDomainDto>({
    url: `/api/v1/CustomDomains`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: addCustomDomainRequest,
    signal,
  });
};

export const getOnlineMenuWebCustomDomainsAddMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof onlineMenuWebCustomDomainsAdd>>,
    TError,
    { data: AddCustomDomainRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof onlineMenuWebCustomDomainsAdd>>,
  TError,
  { data: AddCustomDomainRequest },
  TContext
> => {
  const mutationKey = ['onlineMenuWebCustomDomainsAdd'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof onlineMenuWebCustomDomainsAdd>>,
    { data: AddCustomDomainRequest }
  > = (props) => {
    const { data } = props ?? {};

    return onlineMenuWebCustomDomainsAdd(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type OnlineMenuWebCustomDomainsAddMutationResult = NonNullable<
  Awaited<ReturnType<typeof onlineMenuWebCustomDomainsAdd>>
>;
export type OnlineMenuWebCustomDomainsAddMutationBody = AddCustomDomainRequest;
export type OnlineMenuWebCustomDomainsAddMutationError = void;

/**
 * @summary Adds a custom domain for the current tenant.
 */
export const useOnlineMenuWebCustomDomainsAdd = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof onlineMenuWebCustomDomainsAdd>>,
      TError,
      { data: AddCustomDomainRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof onlineMenuWebCustomDomainsAdd>>,
  TError,
  { data: AddCustomDomainRequest },
  TContext
> => {
  const mutationOptions = getOnlineMenuWebCustomDomainsAddMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Gets the custom domain for the current tenant.
Returns the domain configuration or null if no domain is configured.
 */
export const onlineMenuWebCustomDomainsGetByTenant = (signal?: AbortSignal) => {
  return customInstance<CustomDomainDto | void>({
    url: `/api/v1/CustomDomains`,
    method: 'GET',
    signal,
  });
};

export const getOnlineMenuWebCustomDomainsGetByTenantQueryKey = () => {
  return [`/api/v1/CustomDomains`] as const;
};

export const getOnlineMenuWebCustomDomainsGetByTenantQueryOptions = <
  TData = Awaited<ReturnType<typeof onlineMenuWebCustomDomainsGetByTenant>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof onlineMenuWebCustomDomainsGetByTenant>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getOnlineMenuWebCustomDomainsGetByTenantQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof onlineMenuWebCustomDomainsGetByTenant>>
  > = ({ signal }) => onlineMenuWebCustomDomainsGetByTenant(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof onlineMenuWebCustomDomainsGetByTenant>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type OnlineMenuWebCustomDomainsGetByTenantQueryResult = NonNullable<
  Awaited<ReturnType<typeof onlineMenuWebCustomDomainsGetByTenant>>
>;
export type OnlineMenuWebCustomDomainsGetByTenantQueryError = void;

export function useOnlineMenuWebCustomDomainsGetByTenant<
  TData = Awaited<ReturnType<typeof onlineMenuWebCustomDomainsGetByTenant>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof onlineMenuWebCustomDomainsGetByTenant>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof onlineMenuWebCustomDomainsGetByTenant>>,
          TError,
          Awaited<ReturnType<typeof onlineMenuWebCustomDomainsGetByTenant>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useOnlineMenuWebCustomDomainsGetByTenant<
  TData = Awaited<ReturnType<typeof onlineMenuWebCustomDomainsGetByTenant>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof onlineMenuWebCustomDomainsGetByTenant>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof onlineMenuWebCustomDomainsGetByTenant>>,
          TError,
          Awaited<ReturnType<typeof onlineMenuWebCustomDomainsGetByTenant>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useOnlineMenuWebCustomDomainsGetByTenant<
  TData = Awaited<ReturnType<typeof onlineMenuWebCustomDomainsGetByTenant>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof onlineMenuWebCustomDomainsGetByTenant>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Gets the custom domain for the current tenant.
Returns the domain configuration or null if no domain is configured.
 */

export function useOnlineMenuWebCustomDomainsGetByTenant<
  TData = Awaited<ReturnType<typeof onlineMenuWebCustomDomainsGetByTenant>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof onlineMenuWebCustomDomainsGetByTenant>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getOnlineMenuWebCustomDomainsGetByTenantQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Internal endpoint to check if a domain is already claimed.
Returns 200 if the domain is claimed, 404 if available.
No information disclosure — no body returned.
 */
export const onlineMenuWebCustomDomainsCheckDomain = (
  params: OnlineMenuWebCustomDomainsCheckDomainParams,
  signal?: AbortSignal
) => {
  return customInstance<void>({
    url: `/api/v1/internal/domains/check`,
    method: 'GET',
    params,
    signal,
  });
};

export const getOnlineMenuWebCustomDomainsCheckDomainQueryKey = (
  params?: OnlineMenuWebCustomDomainsCheckDomainParams
) => {
  return [`/api/v1/internal/domains/check`, ...(params ? [params] : [])] as const;
};

export const getOnlineMenuWebCustomDomainsCheckDomainQueryOptions = <
  TData = Awaited<ReturnType<typeof onlineMenuWebCustomDomainsCheckDomain>>,
  TError = void,
>(
  params: OnlineMenuWebCustomDomainsCheckDomainParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof onlineMenuWebCustomDomainsCheckDomain>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getOnlineMenuWebCustomDomainsCheckDomainQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof onlineMenuWebCustomDomainsCheckDomain>>
  > = ({ signal }) => onlineMenuWebCustomDomainsCheckDomain(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof onlineMenuWebCustomDomainsCheckDomain>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type OnlineMenuWebCustomDomainsCheckDomainQueryResult = NonNullable<
  Awaited<ReturnType<typeof onlineMenuWebCustomDomainsCheckDomain>>
>;
export type OnlineMenuWebCustomDomainsCheckDomainQueryError = void;

export function useOnlineMenuWebCustomDomainsCheckDomain<
  TData = Awaited<ReturnType<typeof onlineMenuWebCustomDomainsCheckDomain>>,
  TError = void,
>(
  params: OnlineMenuWebCustomDomainsCheckDomainParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof onlineMenuWebCustomDomainsCheckDomain>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof onlineMenuWebCustomDomainsCheckDomain>>,
          TError,
          Awaited<ReturnType<typeof onlineMenuWebCustomDomainsCheckDomain>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useOnlineMenuWebCustomDomainsCheckDomain<
  TData = Awaited<ReturnType<typeof onlineMenuWebCustomDomainsCheckDomain>>,
  TError = void,
>(
  params: OnlineMenuWebCustomDomainsCheckDomainParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof onlineMenuWebCustomDomainsCheckDomain>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof onlineMenuWebCustomDomainsCheckDomain>>,
          TError,
          Awaited<ReturnType<typeof onlineMenuWebCustomDomainsCheckDomain>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useOnlineMenuWebCustomDomainsCheckDomain<
  TData = Awaited<ReturnType<typeof onlineMenuWebCustomDomainsCheckDomain>>,
  TError = void,
>(
  params: OnlineMenuWebCustomDomainsCheckDomainParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof onlineMenuWebCustomDomainsCheckDomain>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Internal endpoint to check if a domain is already claimed.
Returns 200 if the domain is claimed, 404 if available.
No information disclosure — no body returned.
 */

export function useOnlineMenuWebCustomDomainsCheckDomain<
  TData = Awaited<ReturnType<typeof onlineMenuWebCustomDomainsCheckDomain>>,
  TError = void,
>(
  params: OnlineMenuWebCustomDomainsCheckDomainParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof onlineMenuWebCustomDomainsCheckDomain>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getOnlineMenuWebCustomDomainsCheckDomainQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Public endpoint to resolve a custom domain to a menu ExternalId.
Returns 200 with the menu ExternalId, or 404 for unknown/inactive domains.
 */
export const onlineMenuWebCustomDomainsGetByDomain = (
  params: OnlineMenuWebCustomDomainsGetByDomainParams,
  signal?: AbortSignal
) => {
  return customInstance<GetByDomainResponse>({
    url: `/api/v1/public/domains/resolve`,
    method: 'GET',
    params,
    signal,
  });
};

export const getOnlineMenuWebCustomDomainsGetByDomainQueryKey = (
  params?: OnlineMenuWebCustomDomainsGetByDomainParams
) => {
  return [`/api/v1/public/domains/resolve`, ...(params ? [params] : [])] as const;
};

export const getOnlineMenuWebCustomDomainsGetByDomainQueryOptions = <
  TData = Awaited<ReturnType<typeof onlineMenuWebCustomDomainsGetByDomain>>,
  TError = void,
>(
  params: OnlineMenuWebCustomDomainsGetByDomainParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof onlineMenuWebCustomDomainsGetByDomain>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getOnlineMenuWebCustomDomainsGetByDomainQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof onlineMenuWebCustomDomainsGetByDomain>>
  > = ({ signal }) => onlineMenuWebCustomDomainsGetByDomain(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof onlineMenuWebCustomDomainsGetByDomain>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type OnlineMenuWebCustomDomainsGetByDomainQueryResult = NonNullable<
  Awaited<ReturnType<typeof onlineMenuWebCustomDomainsGetByDomain>>
>;
export type OnlineMenuWebCustomDomainsGetByDomainQueryError = void;

export function useOnlineMenuWebCustomDomainsGetByDomain<
  TData = Awaited<ReturnType<typeof onlineMenuWebCustomDomainsGetByDomain>>,
  TError = void,
>(
  params: OnlineMenuWebCustomDomainsGetByDomainParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof onlineMenuWebCustomDomainsGetByDomain>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof onlineMenuWebCustomDomainsGetByDomain>>,
          TError,
          Awaited<ReturnType<typeof onlineMenuWebCustomDomainsGetByDomain>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useOnlineMenuWebCustomDomainsGetByDomain<
  TData = Awaited<ReturnType<typeof onlineMenuWebCustomDomainsGetByDomain>>,
  TError = void,
>(
  params: OnlineMenuWebCustomDomainsGetByDomainParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof onlineMenuWebCustomDomainsGetByDomain>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof onlineMenuWebCustomDomainsGetByDomain>>,
          TError,
          Awaited<ReturnType<typeof onlineMenuWebCustomDomainsGetByDomain>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useOnlineMenuWebCustomDomainsGetByDomain<
  TData = Awaited<ReturnType<typeof onlineMenuWebCustomDomainsGetByDomain>>,
  TError = void,
>(
  params: OnlineMenuWebCustomDomainsGetByDomainParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof onlineMenuWebCustomDomainsGetByDomain>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Public endpoint to resolve a custom domain to a menu ExternalId.
Returns 200 with the menu ExternalId, or 404 for unknown/inactive domains.
 */

export function useOnlineMenuWebCustomDomainsGetByDomain<
  TData = Awaited<ReturnType<typeof onlineMenuWebCustomDomainsGetByDomain>>,
  TError = void,
>(
  params: OnlineMenuWebCustomDomainsGetByDomainParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof onlineMenuWebCustomDomainsGetByDomain>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getOnlineMenuWebCustomDomainsGetByDomainQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Removes (revokes) a custom domain.
 */
export const onlineMenuWebCustomDomainsRemove = (externalId: string) => {
  return customInstance<void>({ url: `/api/v1/CustomDomains/${externalId}`, method: 'DELETE' });
};

export const getOnlineMenuWebCustomDomainsRemoveMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof onlineMenuWebCustomDomainsRemove>>,
    TError,
    { externalId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof onlineMenuWebCustomDomainsRemove>>,
  TError,
  { externalId: string },
  TContext
> => {
  const mutationKey = ['onlineMenuWebCustomDomainsRemove'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof onlineMenuWebCustomDomainsRemove>>,
    { externalId: string }
  > = (props) => {
    const { externalId } = props ?? {};

    return onlineMenuWebCustomDomainsRemove(externalId);
  };

  return { mutationFn, ...mutationOptions };
};

export type OnlineMenuWebCustomDomainsRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof onlineMenuWebCustomDomainsRemove>>
>;

export type OnlineMenuWebCustomDomainsRemoveMutationError = void;

/**
 * @summary Removes (revokes) a custom domain.
 */
export const useOnlineMenuWebCustomDomainsRemove = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof onlineMenuWebCustomDomainsRemove>>,
      TError,
      { externalId: string },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof onlineMenuWebCustomDomainsRemove>>,
  TError,
  { externalId: string },
  TContext
> => {
  const mutationOptions = getOnlineMenuWebCustomDomainsRemoveMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Requests re-verification of a custom domain.
Resets the domain to PendingVerification status.
 */
export const onlineMenuWebCustomDomainsRequestVerification = (
  externalId: string,
  signal?: AbortSignal
) => {
  return customInstance<void>({
    url: `/api/v1/CustomDomains/${externalId}/verify`,
    method: 'POST',
    signal,
  });
};

export const getOnlineMenuWebCustomDomainsRequestVerificationMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof onlineMenuWebCustomDomainsRequestVerification>>,
    TError,
    { externalId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof onlineMenuWebCustomDomainsRequestVerification>>,
  TError,
  { externalId: string },
  TContext
> => {
  const mutationKey = ['onlineMenuWebCustomDomainsRequestVerification'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof onlineMenuWebCustomDomainsRequestVerification>>,
    { externalId: string }
  > = (props) => {
    const { externalId } = props ?? {};

    return onlineMenuWebCustomDomainsRequestVerification(externalId);
  };

  return { mutationFn, ...mutationOptions };
};

export type OnlineMenuWebCustomDomainsRequestVerificationMutationResult = NonNullable<
  Awaited<ReturnType<typeof onlineMenuWebCustomDomainsRequestVerification>>
>;

export type OnlineMenuWebCustomDomainsRequestVerificationMutationError = void;

/**
 * @summary Requests re-verification of a custom domain.
Resets the domain to PendingVerification status.
 */
export const useOnlineMenuWebCustomDomainsRequestVerification = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof onlineMenuWebCustomDomainsRequestVerification>>,
      TError,
      { externalId: string },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof onlineMenuWebCustomDomainsRequestVerification>>,
  TError,
  { externalId: string },
  TContext
> => {
  const mutationOptions = getOnlineMenuWebCustomDomainsRequestVerificationMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
