import { Platform } from 'react-native';

import { type Answer } from '@/server/autoGeneratedHooks/questioner/models/answer';
import { type Question } from '@/server/autoGeneratedHooks/questioner/models/question';
import { QuestionType } from '@/server/autoGeneratedHooks/questioner/models/questionType';
import { type CompletedQuestionerWithUser } from '@/server/customHooks/useCompletedQuestionersWithUsers';
import { isValueDefined } from '@/utils/is';

const NEWLINE = '\n';

interface QuestionHeader {
  key: string;
  label: string;
  repeat: number;
}

function isNonEmptyString(value: unknown): value is string {
  return typeof value === 'string' && value !== '';
}

function quoteCsv(value: string): string {
  return `"${value.replace(/"/g, '""')}"`;
}

function formatAnswer(answer: Answer | null | undefined): string {
  if (!isValueDefined(answer)) return '';

  if (isValueDefined(answer.stringValue)) return String(answer.stringValue ?? '');
  if (isValueDefined(answer.numericValue)) return String(answer.numericValue ?? '');
  if (isValueDefined(answer.boolValue)) return String(Boolean(answer.boolValue));

  const multi = answer.multiValues;
  if (Array.isArray(multi)) return multi.join(';');
  return '';
}

function getQuestionKey(question: Question): string {
  const id = question.id;
  if (isNonEmptyString(id)) return id;
  const name = question.name;
  if (isNonEmptyString(name)) return name;
  return '';
}

function getQuestionLabel(question: Question): string {
  const name = question.name;
  if (isNonEmptyString(name)) return name;
  const id = question.id;
  if (isNonEmptyString(id)) return id;
  return '';
}

function getQuestions(record: CompletedQuestionerWithUser): Question[] {
  const questions = record.contents?.questions;
  return Array.isArray(questions) ? questions : [];
}

function buildQuestionHeaders(records: CompletedQuestionerWithUser[]): QuestionHeader[] {
  const questionByKey = new Map<string, Question>();
  const maxMulti = new Map<string, number>();

  for (const record of records)
    for (const question of getQuestions(record)) {
      const key = getQuestionKey(question);
      if (!isNonEmptyString(key)) continue;
      if (!questionByKey.has(key)) questionByKey.set(key, question);

      let repeat = 1;
      if (question.type === QuestionType.MultipleChoice) {
        const multi = question.answer?.multiValues;
        if (Array.isArray(multi) && multi.length > 0) repeat = multi.length;
      }

      const prev = maxMulti.get(key) ?? 1;
      if (repeat > prev) maxMulti.set(key, repeat);
    }


  return Array.from(questionByKey.entries()).map(([key, question]) => {
    const repeat = maxMulti.get(key) ?? 1;
    return { key, label: getQuestionLabel(question), repeat };
  });
}

function buildHeaders(questionHeaders: QuestionHeader[]): string[] {
  const baseHeaders = [
    'id',
    'name',
    'completedAt',
    'respondentId',
    'respondentUsername',
    'respondentEmail',
    'respondentFirstName',
    'respondentLastName',
  ];

  const questionLabels: string[] = [];
  for (const q of questionHeaders)
    for (let i = 0; i < q.repeat; i++)
      questionLabels.push(q.label);



  return [...baseHeaders, ...questionLabels];
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return isValueDefined(value) && typeof value === 'object';
}

function isRecordWithKey(record: unknown, key: string): record is Record<string, unknown> {
  if (!isRecord(record)) return false;
  return key in record;
}

function getOptionalNonEmptyString(record: CompletedQuestionerWithUser, key: string): string | undefined {
  if (!isRecordWithKey(record, key)) return undefined;
  const val = record[key];
  if (typeof val !== 'string') return undefined;
  return val === '' ? undefined : val;
}

function getQuestionByKey(questions: Question[], key: string): Question | undefined {
  for (const q of questions)
    if (getQuestionKey(q) === key) return q;

  return undefined;
}

function buildQuestionColumns(record: CompletedQuestionerWithUser, headers: QuestionHeader[]): string[] {
  const questions = getQuestions(record);
  const cols: string[] = [];

  for (const header of headers) {
    const question = getQuestionByKey(questions, header.key);
    const repeat = header.repeat;
    const answer = question?.answer;

    const isAnswerMissing = !question || !isValueDefined(answer) || !isValueDefined(answer);
    if (isAnswerMissing) {
      for (let i = 0; i < repeat; i++) cols.push('');
      continue;
    }

    if (question.type === QuestionType.MultipleChoice) {
      const multi = answer.multiValues;
      if (Array.isArray(multi)) {
        for (let i = 0; i < repeat; i++)
          cols.push(multi[i] ?? '');

        continue;
      }
    }

    cols.push(formatAnswer(answer));
    for (let i = 1; i < repeat; i++) cols.push('');
  }

  return cols;
}

function toCsv(records: CompletedQuestionerWithUser[]): string {
  if (!Array.isArray(records) || records.length === 0) return '';

  const questionHeaders = buildQuestionHeaders(records);
  const headers = buildHeaders(questionHeaders);
  const headerRow = headers.map(quoteCsv).join(',');

  const rows = records.map((record) => buildRecordRow(record, questionHeaders));

  return [headerRow, ...rows].join(NEWLINE);
}

// eslint-disable-next-line complexity
function buildRecordRow(record: CompletedQuestionerWithUser, questionHeaders: QuestionHeader[]): string {
  const respondentId = record.userId ?? record.user?.id ?? '';
  const name = record.name ?? '';
  const completedAt =
    getOptionalNonEmptyString(record, 'completedAt') ??
    getOptionalNonEmptyString(record, 'submittedAt') ??
    record.createdDate ??
    record.lastUpdatedDate ??
    '';

  const respondentUsername = record.user?.username ?? '';
  const respondentEmail = record.user?.email ?? '';
  const respondentFirstName = record.user?.firstName ?? '';
  const respondentLastName = record.user?.lastName ?? '';

  const questionCols = buildQuestionColumns(record, questionHeaders);

  return [
    quoteCsv(String(record.externalId ?? '')),
    quoteCsv(String(name)),
    quoteCsv(String(completedAt)),
    quoteCsv(String(respondentId)),
    quoteCsv(String(respondentUsername)),
    quoteCsv(String(respondentEmail)),
    quoteCsv(String(respondentFirstName)),
    quoteCsv(String(respondentLastName)),
    ...questionCols.map((c) => quoteCsv(String(c))),
  ].join(',');
}

export function generateCsvExport(payload: CompletedQuestionerWithUser[]): void {
  const csv = toCsv(payload);
  if (!isNonEmptyString(csv)) return;

  if (Platform.OS === 'web' && typeof window !== 'undefined') {
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'answers_with_users.csv';
    a.click();
    URL.revokeObjectURL(url);
  }
}
