/**
 * Hook for custom domain management.
 * Wraps TanStack Query hooks around the OnlineMenu CustomDomains API.
 *
 * TODO: Replace manual customInstance calls with Orval-generated hooks once
 * the Custom Domains swagger spec is added to the OnlineMenu service.
 * Generated hooks will appear in:
 *   src/server/autoGeneratedHooks/onlinemenu/custom-domains/
 * Follow the wrapper pattern in src/lib/hooks/notification/useNotificationPreferences.ts
 *
 * Endpoints:
 *   GET    /CustomDomains                    -> fetch current domain
 *   POST   /CustomDomains                    -> add a new domain
 *   DELETE  /CustomDomains/{externalId}       -> remove domain
 *   POST   /CustomDomains/{externalId}/verify -> re-trigger verification
 */
import { useCallback, useMemo } from 'react';

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';

import { customInstance } from '../../../../server/httpClient';
import { isValueDefined } from '../../../../utils/is';
import {
  CUSTOM_DOMAIN_QUERY_KEYS,
  VERIFICATION_POLL_INTERVAL_ACTIVE_MS,
  VERIFICATION_POLL_INTERVAL_MS,
} from '../constants';
import CustomDomainStatus from '../enums/CustomDomainStatus';

import type { CustomDomainDto, UseCustomDomainReturn } from '../types';

const CUSTOM_DOMAINS_ENDPOINT = '/CustomDomains';

async function fetchDomain(): Promise<CustomDomainDto | null> {
  return customInstance<CustomDomainDto | null>({
    url: CUSTOM_DOMAINS_ENDPOINT,
    method: 'GET',
  });
}

async function postDomain(domainName: string): Promise<CustomDomainDto> {
  return customInstance<CustomDomainDto>({
    url: CUSTOM_DOMAINS_ENDPOINT,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: { domainName },
  });
}

async function deleteDomain(externalId: string): Promise<undefined> {
  return customInstance<undefined>({
    url: `${CUSTOM_DOMAINS_ENDPOINT}/${externalId}`,
    method: 'DELETE',
  });
}

async function postVerify(externalId: string): Promise<undefined> {
  return customInstance<undefined>({
    url: `${CUSTOM_DOMAINS_ENDPOINT}/${externalId}/verify`,
    method: 'POST',
  });
}

function getRefetchInterval(data: CustomDomainDto | null | undefined): number {
  if (!isValueDefined(data)) return VERIFICATION_POLL_INTERVAL_ACTIVE_MS;

  return data.status === CustomDomainStatus.PendingVerification
    ? VERIFICATION_POLL_INTERVAL_MS
    : VERIFICATION_POLL_INTERVAL_ACTIVE_MS;
}

function extractErrorMessage(error: unknown): string | null {
  if (!isValueDefined(error)) return null;
  if (error instanceof Error) return error.message;
  return String(error);
}

function useInvalidateDomain(): () => void {
  const queryClient = useQueryClient();
  return useCallback(
    () => { queryClient.invalidateQueries({ queryKey: CUSTOM_DOMAIN_QUERY_KEYS.domain }).catch(() => {}); },
    [queryClient],
  );
}

interface DomainMutations {
  addDomain: (domainName: string) => Promise<void>;
  removeDomain: () => Promise<void>;
  requestVerification: () => Promise<void>;
}

function useDomainMutations(invalidate: () => void, currentExternalId: string | undefined): DomainMutations {
  const addMutation = useMutation({ mutationFn: postDomain, onSuccess: invalidate });
  const removeMutation = useMutation({ mutationFn: deleteDomain, onSuccess: invalidate });
  const verifyMutation = useMutation({ mutationFn: postVerify, onSuccess: invalidate });

  const addDomain = useCallback(
    async (domainName: string): Promise<void> => { await addMutation.mutateAsync(domainName); },
    [addMutation],
  );

  const removeDomain = useCallback(
    async (): Promise<void> => {
      if (!isValueDefined(currentExternalId)) return;
      await removeMutation.mutateAsync(currentExternalId);
    },
    [currentExternalId, removeMutation],
  );

  const requestVerification = useCallback(
    async (): Promise<void> => {
      if (!isValueDefined(currentExternalId)) return;
      await verifyMutation.mutateAsync(currentExternalId);
    },
    [currentExternalId, verifyMutation],
  );

  return { addDomain, removeDomain, requestVerification };
}

export function useCustomDomain(): UseCustomDomainReturn {
  const query = useQuery({
    queryKey: CUSTOM_DOMAIN_QUERY_KEYS.domain,
    queryFn: fetchDomain,
    refetchInterval: (queryResult) => getRefetchInterval(queryResult.state.data),
  });

  const invalidateDomain = useInvalidateDomain();
  const currentExternalId = isValueDefined(query.data) ? query.data.externalId : undefined;
  const { addDomain, removeDomain, requestVerification } = useDomainMutations(invalidateDomain, currentExternalId);

  const domain = isValueDefined(query.data) ? query.data : null;
  const error = extractErrorMessage(query.error);

  return useMemo(() => ({
    domain, isLoading: query.isLoading, error, addDomain, removeDomain, requestVerification,
  }), [domain, query.isLoading, error, addDomain, removeDomain, requestVerification]);
}
