/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * IdentityService API
 * Authentication, User Management, Tenant Management, and API Key Management
 * OpenAPI spec version: v1
 */

export interface IdentityServiceAPIPrivacyGetDataExportStatusResponse {
  requestId?: string;
  status?: string;
  requestedAt?: string;
  /** @nullable */
  completedAt?: string | null;
  /** @nullable */
  expiresAt?: string | null;
  /** @nullable */
  downloadUrl?: string | null;
  /** @nullable */
  fileSizeBytes?: number | null;
}
