/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * IdentityService API
 * Authentication, User Management, Tenant Management, and API Key Management
 * OpenAPI spec version: v1
 */

export interface IdentityServiceAPITenantsPublicBusinessProfileResponse {
  name?: string;
  /** @nullable */
  logoUrl?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  website?: string | null;
  /** @nullable */
  addressLine1?: string | null;
  /** @nullable */
  addressLine2?: string | null;
  /** @nullable */
  city?: string | null;
  /** @nullable */
  state?: string | null;
  /** @nullable */
  postalCode?: string | null;
  /** @nullable */
  country?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  cuisineType?: string | null;
  /** @nullable */
  operatingHoursJson?: string | null;
}
