/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * IdentityService API
 * Authentication, User Management, Tenant Management, and API Key Management
 * OpenAPI spec version: v1
 */
import type { IdentityServiceCoreEnumsApiKeyScope } from './identityServiceCoreEnumsApiKeyScope';
import type { IdentityServiceCoreEnumsRateLimitTier } from './identityServiceCoreEnumsRateLimitTier';

export interface IdentityServiceAPIApiKeysCreateApiKeyRequest {
  name?: string;
  scopes?: IdentityServiceCoreEnumsApiKeyScope[];
  rateLimitTier?: IdentityServiceCoreEnumsRateLimitTier;
  /** @nullable */
  expiresAt?: string | null;
}
