/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * IdentityService API
 * Authentication, User Management, Tenant Management, and API Key Management
 * OpenAPI spec version: v1
 */
import type { IdentityAbstractionsModelsUserInfo } from './identityAbstractionsModelsUserInfo';

/**
 * @nullable
 */
export type IdentityServiceAPIAuthVerifyOtpResponseUserInfo =
  IdentityAbstractionsModelsUserInfo | null;
