/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * IdentityService API
 * Authentication, User Management, Tenant Management, and API Key Management
 * OpenAPI spec version: v1
 */

export interface IdentityServiceAPILogIngestionLogEntry {
  /** @nullable */
  level?: string | null;
  message?: string;
  /** @nullable */
  timestamp?: string | null;
  /** @nullable */
  sessionId?: string | null;
  /** @nullable */
  deviceId?: string | null;
  /** @nullable */
  platform?: string | null;
  /** @nullable */
  appVersion?: string | null;
}
