/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * IdentityService API
 * Authentication, User Management, Tenant Management, and API Key Management
 * OpenAPI spec version: v1
 */

export type IdentityServiceCoreEnumsRateLimitTier =
  (typeof IdentityServiceCoreEnumsRateLimitTier)[keyof typeof IdentityServiceCoreEnumsRateLimitTier];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IdentityServiceCoreEnumsRateLimitTier = {
  Standard: 0,
  Premium: 1,
} as const;
