/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * IdentityService API
 * Authentication, User Management, Tenant Management, and API Key Management
 * OpenAPI spec version: v1
 */

export interface IdentityServiceAPIPrivacyConsentItemResponse {
  consentType?: string;
  isGranted?: boolean;
  /** @nullable */
  grantedAt?: string | null;
  /** @nullable */
  revokedAt?: string | null;
}
