/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * IdentityService API
 * Authentication, User Management, Tenant Management, and API Key Management
 * OpenAPI spec version: v1
 */

export interface IdentityServiceUseCasesTeamDTOsTeamInvitationDto {
  id?: number;
  externalId?: string;
  email?: string;
  role?: string;
  status?: string;
  invitedByUserId?: string;
  invitedAt?: string;
  /** @nullable */
  acceptedAt?: string | null;
  /** @nullable */
  expiresAt?: string | null;
}
