/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * IdentityService API
 * Authentication, User Management, Tenant Management, and API Key Management
 * OpenAPI spec version: v1
 */

export interface IdentityServiceAPIAuthLogoutResponse {
  success?: boolean;
  /** @nullable */
  errorMessage?: string | null;
}
