/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * IdentityService API
 * Authentication, User Management, Tenant Management, and API Key Management
 * OpenAPI spec version: v1
 */

export interface IdentityServiceAPIMeUpdateProfileRequest {
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
}
