/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * IdentityService API
 * Authentication, User Management, Tenant Management, and API Key Management
 * OpenAPI spec version: v1
 */

export type IdentityServiceCoreEnumsApiKeyScope =
  (typeof IdentityServiceCoreEnumsApiKeyScope)[keyof typeof IdentityServiceCoreEnumsApiKeyScope];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IdentityServiceCoreEnumsApiKeyScope = {
  MenusRead: 0,
  MenusWrite: 1,
  TenantRead: 2,
} as const;
