/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * IdentityService API
 * Authentication, User Management, Tenant Management, and API Key Management
 * OpenAPI spec version: v1
 */

export type IdentityAbstractionsModelsAuthMethod =
  (typeof IdentityAbstractionsModelsAuthMethod)[keyof typeof IdentityAbstractionsModelsAuthMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IdentityAbstractionsModelsAuthMethod = {
  UsernamePassword: 0,
  PhoneOtp: 1,
  EmailOtp: 2,
  Social: 3,
} as const;
