/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * IdentityService API
 * Authentication, User Management, Tenant Management, and API Key Management
 * OpenAPI spec version: v1
 */

export interface IdentityAbstractionsModelsUserListItem {
  id?: string;
  username?: string;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
  enabled?: boolean;
  /** @nullable */
  createdTimestamp?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  roles?: string[];
  /** @nullable */
  tenantId?: string | null;
}
