/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * IdentityService API
 * Authentication, User Management, Tenant Management, and API Key Management
 * OpenAPI spec version: v1
 */
import type { IdentityServiceAPIAuthVerifyOtpResponseUserInfo } from './identityServiceAPIAuthVerifyOtpResponseUserInfo';

export interface IdentityServiceAPIAuthVerifyOtpResponse {
  /** @nullable */
  accessToken?: string | null;
  /** @nullable */
  refreshToken?: string | null;
  /** @nullable */
  tokenType?: string | null;
  expiresIn?: number;
  /** @nullable */
  userInfo?: IdentityServiceAPIAuthVerifyOtpResponseUserInfo;
  /** @nullable */
  errorMessage?: string | null;
  /** @nullable */
  errorCode?: string | null;
}
