/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * IdentityService API
 * Authentication, User Management, Tenant Management, and API Key Management
 * OpenAPI spec version: v1
 */

export type IdentityServiceCoreEnumsTeamRole =
  (typeof IdentityServiceCoreEnumsTeamRole)[keyof typeof IdentityServiceCoreEnumsTeamRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IdentityServiceCoreEnumsTeamRole = {
  Owner: 0,
  Manager: 1,
  Staff: 2,
} as const;
