/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * IdentityService API
 * Authentication, User Management, Tenant Management, and API Key Management
 * OpenAPI spec version: v1
 */
import type { IdentityServiceCoreEntitiesTenantStatus } from './identityServiceCoreEntitiesTenantStatus';

export interface IdentityServiceAPITenantsUpdateTenantRequest {
  tenantId?: string;
  name?: string;
  tenantStatus?: IdentityServiceCoreEntitiesTenantStatus;
  /** @nullable */
  logoUrl?: string | null;
  /** @nullable */
  primaryColor?: string | null;
  primaryAuthMethod?: number;
  allowPhoneAuth?: boolean;
  allowEmailAuth?: boolean;
  otpCodeLength?: number;
  otpExpiryMinutes?: number;
  /** @nullable */
  smsProvider?: string | null;
  requireSmsVerification?: boolean;
}
