/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * IdentityService API
 * Authentication, User Management, Tenant Management, and API Key Management
 * OpenAPI spec version: v1
 */
import type { IdentityServiceAPITenantsTenantThemeResponseColors } from './identityServiceAPITenantsTenantThemeResponseColors';
import type { IdentityServiceAPITenantsTenantThemeResponseDarkColors } from './identityServiceAPITenantsTenantThemeResponseDarkColors';
import type { IdentityServiceAPITenantsTenantThemeResponseTypography } from './identityServiceAPITenantsTenantThemeResponseTypography';

export interface IdentityServiceAPITenantsTenantThemeResponse {
  /** @nullable */
  presetId?: string | null;
  /** @nullable */
  colors?: IdentityServiceAPITenantsTenantThemeResponseColors;
  /** @nullable */
  darkColors?: IdentityServiceAPITenantsTenantThemeResponseDarkColors;
  /** @nullable */
  typography?: IdentityServiceAPITenantsTenantThemeResponseTypography;
  /** @nullable */
  logoContentId?: string | null;
  /** @nullable */
  faviconContentId?: string | null;
  /** @nullable */
  customLogoUrl?: string | null;
  /** @nullable */
  customFaviconUrl?: string | null;
  /** @nullable */
  customCss?: string | null;
  /** @nullable */
  headerHtml?: string | null;
  /** @nullable */
  footerHtml?: string | null;
  showPoweredBy?: boolean;
  /** @nullable */
  companyName?: string | null;
  /** @nullable */
  supportEmail?: string | null;
}
