/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Questioner.Web
 * OpenAPI spec version: 1.0.0
 */

export interface ActivateTemplateQuestionerTemplateRequest {
  isActive?: boolean;
}
