/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Questioner.Web
 * OpenAPI spec version: 1.0.0
 */
import type { BaseResponseDto } from './baseResponseDto';
import type { QuestionerTemplateDtoAllOf } from './questionerTemplateDtoAllOf';

export type QuestionerTemplateDto = BaseResponseDto & QuestionerTemplateDtoAllOf;
