/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Questioner.Web
 * OpenAPI spec version: 1.0.0
 */

export type QuestionType = (typeof QuestionType)[keyof typeof QuestionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const QuestionType = {
  Text: 0,
  MultipleChoice: 1,
  Checkbox: 2,
  Radio: 3,
  Dropdown: 4,
} as const;
