/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Questioner.Web
 * OpenAPI spec version: 1.0.0
 */
import type { QuestionType } from './questionType';
import type { Option } from './option';
import type { QuestionAnswer } from './questionAnswer';
import type { SkipCondition } from './skipCondition';

export interface Question {
  id?: string;
  name?: string;
  type?: QuestionType;
  /** @nullable */
  options?: Option[] | null;
  page?: number;
  /** @nullable */
  answer?: QuestionAnswer;
  isRequired?: boolean;
  /** @nullable */
  skipConditions?: SkipCondition[] | null;
  order?: number;
}
