/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Questioner.Web
 * OpenAPI spec version: 1.0.0
 */
import type { QuestionerContents } from './questionerContents';

/**
 * @nullable
 */
export type UpdateQuestionerTemplateRequestContents = QuestionerContents | null;
