/**
 * React Query hooks for GDPR data export requests.
 * Wraps generated Orval API functions with app-specific logic.
 */
import { useCallback } from 'react';

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';

import {
  identityServiceAPIPrivacyRequestDataExport,
  identityServiceAPIPrivacyGetDataExportStatus,
} from '../../../../server/autoGeneratedHooks/identity/privacy/privacy';
import { identityInstance } from '../../../../server/mutators/identityMutator';
import ExportStatus from '../enums/ExportStatus';

import type { DataExportRequest } from '../types';

const EXPORT_QUERY_KEY = ['privacy', 'data-export'] as const;

/** Polling interval in ms for active exports. */
const POLL_INTERVAL_MS = 5000;

const EXPORT_STATUS_MAP: Record<string, ExportStatus | undefined> = {
  [ExportStatus.Pending]: ExportStatus.Pending,
  [ExportStatus.Processing]: ExportStatus.Processing,
  [ExportStatus.Completed]: ExportStatus.Completed,
  [ExportStatus.Failed]: ExportStatus.Failed,
  [ExportStatus.Expired]: ExportStatus.Expired,
};

function toExportStatus(value: string | undefined): ExportStatus {
  return EXPORT_STATUS_MAP[value ?? ''] ?? ExportStatus.Pending;
}

async function requestExport(): Promise<DataExportRequest> {
  const response = await identityServiceAPIPrivacyRequestDataExport();
  return {
    requestId: response.requestId ?? '',
    status: toExportStatus(response.status),
  };
}

async function checkExportStatus(requestId: string): Promise<DataExportRequest> {
  const response = await identityServiceAPIPrivacyGetDataExportStatus(requestId);
  return {
    requestId: response.requestId ?? '',
    status: toExportStatus(response.status),
    createdAt: response.requestedAt,
  };
}

/**
 * Downloads a data export as a Blob.
 * Uses identityInstance directly because the generated hook types the response
 * as void (Swagger doesn't model binary file responses correctly).
 */
async function downloadExport(requestId: string): Promise<Blob> {
  return identityInstance<Blob>({
    url: `/api/privacy/data-export/${requestId}/download`,
    method: 'GET',
  });
}

function isActiveExport(status: string): boolean {
  const pending: string = ExportStatus.Pending;
  const processing: string = ExportStatus.Processing;
  return status === pending || status === processing;
}

interface MutationCallbacks {
  onSuccess?: (data: DataExportRequest) => void;
  onError?: (error: Error) => void;
}

interface UseRequestExportResult {
  requestExport: () => void;
  isPending: boolean;
}

export function useRequestDataExport(callbacks?: MutationCallbacks): UseRequestExportResult {
  const queryClient = useQueryClient();

  const mutation = useMutation({
    mutationFn: requestExport,
    onSuccess: (data: DataExportRequest) => {
      queryClient.invalidateQueries({ queryKey: EXPORT_QUERY_KEY }).catch(() => {});
      callbacks?.onSuccess?.(data);
    },
    onError: (error: unknown) => {
      const errorObj = error instanceof Error ? error : new Error('Export request failed');
      callbacks?.onError?.(errorObj);
    },
  });

  const handleRequest = useCallback(() => mutation.mutate(), [mutation]);

  return {
    requestExport: handleRequest,
    isPending: mutation.isPending,
  };
}

interface UseExportStatusResult {
  exportRequest: DataExportRequest | undefined;
  isLoading: boolean;
  isError: boolean;
}

export function useExportStatus(requestId: string | undefined): UseExportStatusResult {
  const hasRequestId = typeof requestId === 'string' && requestId !== '';
  const safeRequestId = hasRequestId ? requestId : '';

  const statusQuery = useQuery({
    queryKey: [...EXPORT_QUERY_KEY, requestId],
    queryFn: async () => checkExportStatus(safeRequestId),
    enabled: hasRequestId,
    refetchInterval: (queryState) => {
      const status = queryState.state.data?.status;
      if (typeof status === 'string' && isActiveExport(status)) return POLL_INTERVAL_MS;
      return false;
    },
  });

  return {
    exportRequest: statusQuery.data,
    isLoading: statusQuery.isLoading,
    isError: statusQuery.isError,
  };
}

interface UseDownloadExportResult {
  download: () => void;
  isPending: boolean;
}

export function useDownloadExport(
  requestId: string | undefined,
  callbacks?: { onError?: (error: Error) => void },
): UseDownloadExportResult {
  const hasRequestId = typeof requestId === 'string' && requestId !== '';
  const safeRequestId = hasRequestId ? requestId : '';

  const mutation = useMutation({
    mutationFn: async () => downloadExport(safeRequestId),
    onSuccess: (blob: Blob) => {
      const url = URL.createObjectURL(blob);
      const anchor = document.createElement('a');
      anchor.href = url;
      anchor.download = 'data-export.zip';
      anchor.click();
      URL.revokeObjectURL(url);
    },
    onError: (error: unknown) => {
      const errorObj = error instanceof Error ? error : new Error('Download failed');
      callbacks?.onError?.(errorObj);
    },
  });

  const handleDownload = useCallback(() => {
    if (hasRequestId) mutation.mutate();
  }, [mutation, hasRequestId]);

  return {
    download: handleDownload,
    isPending: mutation.isPending,
  };
}

export { EXPORT_QUERY_KEY };
