/**
 * React Query hooks for privacy consent management.
 * Wraps generated Orval API functions with app-specific logic.
 */
import { useCallback } from 'react';

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';

import {
  identityServiceAPIPrivacyGetConsent,
  getIdentityServiceAPIPrivacyGetConsentQueryKey,
  identityServiceAPIPrivacyUpdateConsent,
} from '../../../../server/autoGeneratedHooks/identity/privacy/privacy';
import ConsentType from '../enums/ConsentType';

import type { ConsentRecord, UpdateConsentRequest } from '../types';

const CONSENT_QUERY_KEY = getIdentityServiceAPIPrivacyGetConsentQueryKey();

const CONSENT_TYPE_MAP: Record<string, ConsentType | undefined> = {
  [ConsentType.Essential]: ConsentType.Essential,
  [ConsentType.Analytics]: ConsentType.Analytics,
  [ConsentType.Marketing]: ConsentType.Marketing,
};

function toConsentType(value: string | undefined): ConsentType {
  return CONSENT_TYPE_MAP[value ?? ''] ?? ConsentType.Essential;
}

async function fetchConsent(): Promise<ConsentRecord[]> {
  const response = await identityServiceAPIPrivacyGetConsent();
  return (response.consents ?? []).map((item) => ({
    consentType: toConsentType(item.consentType),
    isGranted: item.isGranted ?? false,
  }));
}

async function updateConsent(body: UpdateConsentRequest): Promise<undefined> {
  await identityServiceAPIPrivacyUpdateConsent({
    consents: [{ consentType: body.consentType, isGranted: body.isGranted }],
  });
  return undefined;
}

interface MutationCallbacks {
  onSuccess?: () => void;
  onError?: (error: Error) => void;
}

interface UseGetConsentResult {
  consents: ConsentRecord[];
  isLoading: boolean;
  isError: boolean;
  error: Error | null;
}

export function useGetConsent(): UseGetConsentResult {
  const query = useQuery({
    queryKey: CONSENT_QUERY_KEY,
    queryFn: fetchConsent,
  });

  const queryError: unknown = query.error;

  return {
    consents: query.data ?? [],
    isLoading: query.isLoading,
    isError: query.isError,
    error: queryError instanceof Error ? queryError : null,
  };
}

interface UseUpdateConsentResult {
  updateConsentType: (consentType: ConsentType, isGranted: boolean) => void;
  isPending: boolean;
}

export function useUpdateConsent(callbacks?: MutationCallbacks): UseUpdateConsentResult {
  const queryClient = useQueryClient();

  const mutation = useMutation({
    mutationFn: updateConsent,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: CONSENT_QUERY_KEY }).catch(() => {});
      callbacks?.onSuccess?.();
    },
    onError: (error: unknown) => {
      const errorObj = error instanceof Error ? error : new Error('Update failed');
      callbacks?.onError?.(errorObj);
    },
  });

  const updateConsentType = useCallback(
    (consentType: ConsentType, isGranted: boolean) => {
      mutation.mutate({ consentType, isGranted });
    },
    [mutation],
  );

  return {
    updateConsentType,
    isPending: mutation.isPending,
  };
}

export { CONSENT_QUERY_KEY };
