import React, { useCallback, useEffect, useMemo, useState } from 'react';

import { ActivityIndicator, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';

import { useRouter } from 'expo-router';

import { DevicePinOffer, useBffLoginConfig } from '@dloizides/auth-web';

import { mapAppThemeToAuthTheme } from '@/auth/authThemeMapping';
import { bffAuthClient } from '@/auth/bffClient';
import { BffLoginMethod } from '@/auth/BffLoginMethod';
import { useDevicePinEnrollLabels } from '@/auth/useAuthLabels';
import BusinessProfileNudge from '@/components/Dashboard/components/BusinessProfileNudge';
import WelcomeHeader from '@/components/Dashboard/components/WelcomeHeader';
import { useBusinessProfileNudge } from '@/components/Dashboard/hooks/useBusinessProfileNudge';
import { useDashboardData } from '@/features/dashboard/hooks/useDashboardData';
import { useSetupChecklist } from '@/features/dashboard/hooks/useSetupChecklist';
import type { PreferencesInput } from '@/features/dashboard/hooks/useWelcomeWizard';
import { useWelcomeWizard } from '@/features/dashboard/hooks/useWelcomeWizard';
import { useTooltipTourContext } from '@/features/tooltipTour/components/TooltipProvider';
import { useBreakpoint } from '@/hooks/useBreakpoint';
import { useGetRole } from '@/hooks/useGetRole';
import { FM } from '@/localization/helpers';
import { Routes } from '@/navigation/routes';
import {
  useIdentityServiceAPIMeGetPreferences,
  useIdentityServiceAPIMeUpdatePreferences,
} from '@/server/autoGeneratedHooks/identity/me/me';
import TooltipTourId from '@/shared/enums/TooltipTourId';
import { TestIds } from '@/shared/testIds';
import { useTheme } from '@/theme/hooks/useTheme';
import { layoutStyles } from '@/theme/utils/styles';

import DashboardCards from './DashboardCards';
import SetupChecklist from './SetupChecklist';
import WelcomeWizard from './WelcomeWizard';

const TENANT_SECTION_MARGIN_TOP = 24;
const TENANT_BUTTON_PADDING_VERTICAL = 12;
const TENANT_BUTTON_PADDING_HORIZONTAL = 20;
const TENANT_BUTTON_BORDER_RADIUS = 8;
const TENANT_BUTTON_FONT_SIZE = 15;
const TENANT_TITLE_FONT_SIZE = 16;
const TENANT_TITLE_MARGIN_BOTTOM = 12;
const BORDER_WIDTH = 1;
const SCROLL_CONTENT_PADDING_BOTTOM = 32;
const PHONE_CONTAINER_PADDING = 12;

const PIN_OFFER_MARGIN_TOP = 16;

const styles = StyleSheet.create({
  scrollContent: {
    paddingBottom: SCROLL_CONTENT_PADDING_BOTTOM,
  },
  pinOffer: {
    marginTop: PIN_OFFER_MARGIN_TOP,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tenantSection: {
    marginTop: TENANT_SECTION_MARGIN_TOP,
  },
  tenantTitle: {
    fontSize: TENANT_TITLE_FONT_SIZE,
    fontWeight: '600',
    marginBottom: TENANT_TITLE_MARGIN_BOTTOM,
  },
  tenantButton: {
    paddingVertical: TENANT_BUTTON_PADDING_VERTICAL,
    paddingHorizontal: TENANT_BUTTON_PADDING_HORIZONTAL,
    borderRadius: TENANT_BUTTON_BORDER_RADIUS,
    borderWidth: BORDER_WIDTH,
    alignSelf: 'flex-start',
  },
  tenantButtonText: {
    fontSize: TENANT_BUTTON_FONT_SIZE,
    fontWeight: '600',
  },
});

const phoneContainerStyle = { padding: PHONE_CONTAINER_PADDING };

function usePreferencesInput(): PreferencesInput {
  const preferencesQuery = useIdentityServiceAPIMeGetPreferences();
  const updateMutation = useIdentityServiceAPIMeUpdatePreferences();

  const updatePreferences = useCallback(
    (data: Parameters<PreferencesInput['updatePreferences']>[0]): void => {
      updateMutation.mutate({ data });
    },
    [updateMutation],
  );

  return useMemo(
    () => ({ data: preferencesQuery.data, isLoading: preferencesQuery.isLoading, updatePreferences }),
    [preferencesQuery.data, preferencesQuery.isLoading, updatePreferences],
  );
}

const DashboardPage = (): React.ReactElement => {
  const dashboardData = useDashboardData();
  const preferences = usePreferencesInput();
  const wizard = useWelcomeWizard(dashboardData, preferences);
  const checklist = useSetupChecklist(dashboardData, preferences);
  const showProfileNudge = useBusinessProfileNudge(!dashboardData.isEmpty);
  const { startTour, hasSeenTour } = useTooltipTourContext();

  const router = useRouter();
  const { theme } = useTheme();
  const { colors } = theme;
  const primary = theme.palette.primary['500'];
  const { isPhone } = useBreakpoint();
  const { isSuperAdmin } = useGetRole();

  // Post-login device-PIN offer (unified-login Increment 3 Batch 3): skippable,
  // shown once per visit to a signed-in user when the BFF advertises the
  // pin/passkey method AND this device has no PIN yet. Dismissed (enrolled or
  // skipped) in local state. The shared offer component is react-query-free.
  const authTheme = useMemo(() => mapAppThemeToAuthTheme(theme), [theme]);
  const { config: loginConfig, loading: loginConfigLoading } = useBffLoginConfig(bffAuthClient);
  const devicePinEnrollLabels = useDevicePinEnrollLabels();
  const [pinOfferDismissed, setPinOfferDismissed] = useState<boolean>(false);
  const pinMethodAdvertised =
    loginConfig.methods.includes(BffLoginMethod.Pin)
    || loginConfig.methods.includes(BffLoginMethod.Passkey);
  const showPinOffer =
    !loginConfigLoading
    && pinMethodAdvertised
    && !loginConfig.deviceState.hasPin
    && !pinOfferDismissed;

  useEffect(() => {
    if (dashboardData.isLoading || wizard.isWizardVisible) return;
    if (!hasSeenTour(TooltipTourId.Dashboard)) startTour(TooltipTourId.Dashboard);
  }, [dashboardData.isLoading, wizard.isWizardVisible, hasSeenTour, startTour]);

  const handleTenantPress = useCallback((): void => {
    router.push(Routes.TENANTS);
  }, [router]);

  if (wizard.isWizardVisible)
    return <WelcomeWizard wizard={wizard} />;

  if (dashboardData.isLoading)
    return (
      <View
        style={[layoutStyles.container, { backgroundColor: colors.background }, isPhone && phoneContainerStyle]}
        testID={TestIds.DASHBOARD_PAGE}
      >
        <WelcomeHeader isEmpty />
        <View style={styles.loadingContainer}>
          <ActivityIndicator color={primary} size="large" testID={TestIds.LOADING_INDICATOR} />
        </View>
      </View>
    );

  return (
    <ScrollView
      contentContainerStyle={[layoutStyles.container, styles.scrollContent, isPhone && phoneContainerStyle]}
      style={{ backgroundColor: colors.background }}
      testID={TestIds.DASHBOARD_PAGE}
    >
      <WelcomeHeader isEmpty={dashboardData.isEmpty} />

      {showPinOffer ? (
        <View style={styles.pinOffer}>
          <DevicePinOffer
            client={bffAuthClient}
            labels={devicePinEnrollLabels}
            testIdPrefix="katalogos"
            theme={authTheme}
            onDismiss={(): void => setPinOfferDismissed(true)}
          />
        </View>
      ) : null}

      <DashboardCards dashboardData={dashboardData} />

      <SetupChecklist checklist={checklist} />

      {showProfileNudge ? <BusinessProfileNudge /> : null}

      {isSuperAdmin ? (
        <View style={styles.tenantSection}>
          <Text accessibilityRole="header" style={[styles.tenantTitle, { color: colors.text }]}>
            {FM('dashboard.tenants.title')}
          </Text>
          <TouchableOpacity
            accessibilityHint={FM('dashboard.tenants.ctaHint')}
            accessibilityLabel={FM('dashboard.tenants.cta')}
            accessibilityRole="button"
            style={[styles.tenantButton, { borderColor: primary }]}
            testID={TestIds.DASHBOARD_TENANT_LINK}
            onPress={handleTenantPress}
          >
            <Text style={[styles.tenantButtonText, { color: primary }]}>
              {FM('dashboard.tenants.cta')}
            </Text>
          </TouchableOpacity>
        </View>
      ) : null}
    </ScrollView>
  );
};

export default DashboardPage;
