/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PaymentService API
 * Subscription Billing, Pricing Plans, and Payment Management API
 * OpenAPI spec version: v1
 */
import type { PaymentServiceUseCasesDTOsFeatureLimitDto } from './paymentServiceUseCasesDTOsFeatureLimitDto';

export interface PaymentServiceUseCasesDTOsSubscriptionDto {
  externalId?: string;
  planExternalId?: string;
  planName?: string;
  planTier?: string;
  status?: string;
  billingCycle?: string;
  monthlyPrice?: number;
  annualPrice?: number;
  currentPeriodStart?: string;
  currentPeriodEnd?: string;
  /** @nullable */
  trialEndDate?: string | null;
  /** @nullable */
  cancellationDate?: string | null;
  showWatermark?: boolean;
  features?: PaymentServiceUseCasesDTOsFeatureLimitDto[];
}
