/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PaymentService API
 * Subscription Billing, Pricing Plans, and Payment Management API
 * OpenAPI spec version: v1
 */
import type { PaymentServiceUseCasesDTOsFeatureLimitDto } from './paymentServiceUseCasesDTOsFeatureLimitDto';

export interface PaymentServiceUseCasesDTOsPricingPlanDto {
  externalId?: string;
  name?: string;
  description?: string;
  tier?: string;
  monthlyPriceUsd?: number;
  annualPriceUsd?: number;
  currency?: string;
  displayOrder?: number;
  features?: PaymentServiceUseCasesDTOsFeatureLimitDto[];
}
