/**
 * Account Settings Hub Screen.
 * Displays a user profile summary and navigation cards to each settings sub-section,
 * organized into logical groups: Account, Business, and Advanced.
 */
import React from 'react';

import { ActivityIndicator, ScrollView, StyleSheet, Text, View } from 'react-native';

import SettingsNavCards from './SettingsNavCards';
import { FM } from '../../../../localization/helpers';
import { useIdentityServiceAPIMeGetProfile } from '../../../../server/autoGeneratedHooks/identity/me/me';
import { TestIds } from '../../../../shared/testIds';
import { useTheme } from '../../../../theme/hooks/useTheme';
import Heading from '../../../Shared/Heading';
import Section from '../../../Shared/Section';
import {
  SECTION_SPACING,
  BODY_FONT_SIZE,
  ERROR_TEXT_MARGIN_TOP,
  DESCRIPTION_FONT_SIZE,
  TITLE_GAP,
} from '../../constants';

const SUMMARY_NAME_FONT_SIZE = 18;
const SUMMARY_NAME_FONT_WEIGHT = '600' as const;

const styles = StyleSheet.create({
  container: { flex: 1 },
  scrollContent: { padding: SECTION_SPACING },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  errorText: { fontSize: BODY_FONT_SIZE, textAlign: 'center', marginTop: ERROR_TEXT_MARGIN_TOP },
  summaryName: {
    fontSize: SUMMARY_NAME_FONT_SIZE,
    fontWeight: SUMMARY_NAME_FONT_WEIGHT,
  },
  summaryEmail: {
    fontSize: DESCRIPTION_FONT_SIZE,
    marginTop: TITLE_GAP,
  },
});

const AccountSettingsHubScreen = (): React.ReactElement => {
  const { theme } = useTheme();
  const { colors } = theme;
  const primary = theme.palette.primary['500'];
  const errorColor = theme.semantic.error['500'];

  const { data: profile, isLoading, isError } = useIdentityServiceAPIMeGetProfile();

  if (isLoading)
    return (
      <View style={styles.loadingContainer} testID={TestIds.ACCOUNT_HUB_LOADING}>
        <ActivityIndicator color={primary} size="large" />
        <Text style={[styles.errorText, { color: colors.textSecondary }]}>{FM('loading')}</Text>
      </View>
    );

  if (isError)
    return (
      <View style={styles.loadingContainer} testID={TestIds.ACCOUNT_HUB_ERROR}>
        <Text style={[styles.errorText, { color: errorColor }]}>
          {FM('settings.hub.loadError')}
        </Text>
      </View>
    );

  const displayName = [profile?.firstName, profile?.lastName].filter(Boolean).join(' ');
  const displayEmail = profile?.email ?? '';

  return (
    <View
      style={[styles.container, { backgroundColor: colors.background }]}
      testID={TestIds.ACCOUNT_HUB_SCREEN}
    >
      <ScrollView contentContainerStyle={styles.scrollContent}>
        <Heading>{FM('settings.hub.title')}</Heading>

        <Section>
          <View
            accessibilityHint={FM('settings.hub.profileSummaryHint')}
            accessibilityLabel={displayName}
            testID={TestIds.ACCOUNT_HUB_PROFILE_SUMMARY}
          >
            <Text style={[styles.summaryName, { color: colors.text }]}>{displayName}</Text>
            <Text style={[styles.summaryEmail, { color: colors.textSecondary }]}>
              {displayEmail}
            </Text>
          </View>
        </Section>

        <SettingsNavCards />
      </ScrollView>
    </View>
  );
};

export default AccountSettingsHubScreen;
