/**
 * Tests for useDeleteUser hook.
 * Focus on testing delete confirmation and mutation callbacks.
 */
import './userPageHandlers.setupMocks';

import { Alert } from 'react-native';

import { renderHook, act } from '@testing-library/react-native';

import { useDeleteUser } from './useUserPageHandlers';
import { notify, notifySuccess } from '../lib/notifications';

import type { DeleteUserState } from './userPageHandlers.testTypes';
import type { useIdentityServiceAPIUsersDeleteUser } from '../server/autoGeneratedHooks/identity/users/users';

type DeleteMutation = ReturnType<typeof useIdentityServiceAPIUsersDeleteUser>;

describe('useDeleteUser', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  it('shows confirmation alert before deleting', () => {
    const mockMutate = jest.fn();
    const deleteMutation = { mutate: mockMutate } as unknown as DeleteMutation;
    const refetchUsers = jest.fn();
    const state: DeleteUserState = { setDeletingUserId: jest.fn() };

    const { result } = renderHook(() =>
      useDeleteUser(deleteMutation, refetchUsers, state)
    );

    act(() => {
      result.current('user-123');
    });

    expect(Alert.alert).toHaveBeenCalledWith(
      'users.deleteConfirmTitle',
      'users.deleteConfirmMessage',
      expect.arrayContaining([
        expect.objectContaining({ text: 'users.deleteConfirmCancel', style: 'cancel' }),
        expect.objectContaining({ text: 'users.deleteConfirmButton', style: 'destructive' }),
      ])
    );
  });

  it('calls mutation when delete is confirmed', () => {
    const mockMutate = jest.fn();
    const deleteMutation = { mutate: mockMutate } as unknown as DeleteMutation;
    const refetchUsers = jest.fn();
    const state: DeleteUserState = { setDeletingUserId: jest.fn() };

    (Alert.alert as jest.Mock).mockImplementation((title, message, buttons) => {
      const deleteButton = buttons?.find(
        (b: { text: string }) => b.text === 'users.deleteConfirmButton'
      );
      deleteButton?.onPress?.();
    });

    const { result } = renderHook(() =>
      useDeleteUser(deleteMutation, refetchUsers, state)
    );

    act(() => {
      result.current('user-123');
    });

    expect(state.setDeletingUserId).toHaveBeenCalledWith('user-123');
    expect(mockMutate).toHaveBeenCalledWith(
      { userId: 'user-123' },
      expect.any(Object)
    );
  });

  it('notifies success and resets state on successful delete', () => {
    const mockMutate = jest.fn((_, options) => {
      options.onSuccess();
    });
    const deleteMutation = { mutate: mockMutate } as unknown as DeleteMutation;
    const refetchUsers = jest.fn();
    const state: DeleteUserState = { setDeletingUserId: jest.fn() };

    (Alert.alert as jest.Mock).mockImplementation((title, message, buttons) => {
      const deleteButton = buttons?.find(
        (b: { text: string }) => b.text === 'users.deleteConfirmButton'
      );
      deleteButton?.onPress?.();
    });

    const { result } = renderHook(() =>
      useDeleteUser(deleteMutation, refetchUsers, state)
    );

    act(() => {
      result.current('user-123');
    });

    expect(notifySuccess).toHaveBeenCalledWith('users.messages.deleteSuccess');
    expect(refetchUsers).toHaveBeenCalled();
    expect(state.setDeletingUserId).toHaveBeenCalledWith(null);
  });

  it('notifies error and resets state on delete failure', () => {
    const mockMutate = jest.fn((_, options) => {
      options.onError(new Error('Delete failed'));
    });
    const deleteMutation = { mutate: mockMutate } as unknown as DeleteMutation;
    const refetchUsers = jest.fn();
    const state: DeleteUserState = { setDeletingUserId: jest.fn() };

    (Alert.alert as jest.Mock).mockImplementation((title, message, buttons) => {
      const deleteButton = buttons?.find(
        (b: { text: string }) => b.text === 'users.deleteConfirmButton'
      );
      deleteButton?.onPress?.();
    });

    const { result } = renderHook(() =>
      useDeleteUser(deleteMutation, refetchUsers, state)
    );

    act(() => {
      result.current('user-123');
    });

    expect(notify).toHaveBeenCalledWith('error', {
      message: 'users.errors.deleteFailed:Delete failed',
    });
    expect(state.setDeletingUserId).toHaveBeenCalledWith(null);
  });
});
