/**
 * Tests for useMenuActivateToggle hook.
 * Focus on testing the callback logic, not the underlying mutations.
 */
import { renderHook, act } from '@testing-library/react-native';

import { mockT, createMockMutation } from './menuPageHandlers.testUtils';
import { type useActivateMenu, type useDeactivateMenu } from './useMenuActions';
import { useMenuActivateToggle } from './useMenuPageHandlers';
import { notify, notifySuccess } from '../lib/notifications';
import { logger } from '../utils/logger';

type ActivateMutation = ReturnType<typeof useActivateMenu>;
type DeactivateMutation = ReturnType<typeof useDeactivateMenu>;

// Mock dependencies
jest.mock('../lib/notifications', () => ({
  notify: jest.fn(),
  notifySuccess: jest.fn(),
}));

jest.mock('../utils/logger', () => ({
  logger: {
    error: jest.fn(),
    warn: jest.fn(),
    info: jest.fn(),
  },
}));

jest.mock('react-native', () => ({
  Linking: { openURL: jest.fn() },
  Platform: { OS: 'web' },
}));

jest.mock('../server/autoGeneratedHooks/onlinemenu/tenantmenus/tenantmenus', () => ({
  useOnlineMenuWebMenuList: jest.fn(() => ({ data: [], isLoading: false, refetch: jest.fn() })),
  useOnlineMenuWebMenuUpdate: jest.fn(() => ({ mutate: jest.fn(), isLoading: false })),
  useOnlineMenuWebMenuDelete: jest.fn(() => ({ mutate: jest.fn(), isLoading: false })),
  useOnlineMenuWebTenantMenusCreate: jest.fn(() => ({ mutate: jest.fn(), isLoading: false })),
}));

jest.mock('./useMenuActions', () => ({
  useActivateMenu: jest.fn(() => ({ mutate: jest.fn(), isLoading: false })),
  useDeactivateMenu: jest.fn(() => ({ mutate: jest.fn(), isLoading: false })),
}));

describe('useMenuActivateToggle', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  it('calls deactivate mutation when currently active (boolean true)', () => {
    const mockDeactivate = jest.fn();
    const mockActivate = jest.fn();
    const activateMutation = createMockMutation(mockActivate) as unknown as ActivateMutation;
    const deactivateMutation = createMockMutation(mockDeactivate) as unknown as DeactivateMutation;
    const refetchMenusSoon = jest.fn();

    const { result } = renderHook(() =>
      useMenuActivateToggle({ activateMutation, deactivateMutation, refetchMenusSoon, t: mockT })
    );

    act(() => {
      result.current('menu-123', true);
    });

    expect(mockDeactivate).toHaveBeenCalledWith(
      { externalId: 'menu-123' },
      expect.any(Object)
    );
    expect(mockActivate).not.toHaveBeenCalled();
  });

  it('calls activate mutation when currently inactive (boolean false)', () => {
    const mockDeactivate = jest.fn();
    const mockActivate = jest.fn();
    const activateMutation = createMockMutation(mockActivate) as unknown as ActivateMutation;
    const deactivateMutation = createMockMutation(mockDeactivate) as unknown as DeactivateMutation;
    const refetchMenusSoon = jest.fn();

    const { result } = renderHook(() =>
      useMenuActivateToggle({ activateMutation, deactivateMutation, refetchMenusSoon, t: mockT })
    );

    act(() => {
      result.current('menu-123', false);
    });

    expect(mockActivate).toHaveBeenCalledWith(
      { externalId: 'menu-123' },
      expect.any(Object)
    );
    expect(mockDeactivate).not.toHaveBeenCalled();
  });

  it('calls deactivate mutation when currently active (number 1)', () => {
    const mockDeactivate = jest.fn();
    const mockActivate = jest.fn();
    const activateMutation = createMockMutation(mockActivate) as unknown as ActivateMutation;
    const deactivateMutation = createMockMutation(mockDeactivate) as unknown as DeactivateMutation;
    const refetchMenusSoon = jest.fn();

    const { result } = renderHook(() =>
      useMenuActivateToggle({ activateMutation, deactivateMutation, refetchMenusSoon, t: mockT })
    );

    act(() => {
      result.current('menu-123', 1);
    });

    expect(mockDeactivate).toHaveBeenCalled();
  });

  it('calls activate mutation when currently inactive (number 0)', () => {
    const mockDeactivate = jest.fn();
    const mockActivate = jest.fn();
    const activateMutation = createMockMutation(mockActivate) as unknown as ActivateMutation;
    const deactivateMutation = createMockMutation(mockDeactivate) as unknown as DeactivateMutation;
    const refetchMenusSoon = jest.fn();

    const { result } = renderHook(() =>
      useMenuActivateToggle({ activateMutation, deactivateMutation, refetchMenusSoon, t: mockT })
    );

    act(() => {
      result.current('menu-123', 0);
    });

    expect(mockActivate).toHaveBeenCalled();
  });

  it('notifies success on activation', () => {
    const mockActivate = jest.fn((_params, options) => {
      options.onSuccess();
    });
    const activateMutation = createMockMutation(mockActivate) as unknown as ActivateMutation;
    const deactivateMutation = createMockMutation() as unknown as DeactivateMutation;
    const refetchMenusSoon = jest.fn();

    const { result } = renderHook(() =>
      useMenuActivateToggle({ activateMutation, deactivateMutation, refetchMenusSoon, t: mockT })
    );

    act(() => {
      result.current('menu-123', false);
    });

    expect(notifySuccess).toHaveBeenCalledWith('Menu activated');
    expect(refetchMenusSoon).toHaveBeenCalled();
  });

  it('notifies success on deactivation', () => {
    const mockDeactivate = jest.fn((_params, options) => {
      options.onSuccess();
    });
    const activateMutation = createMockMutation() as unknown as ActivateMutation;
    const deactivateMutation = createMockMutation(mockDeactivate) as unknown as DeactivateMutation;
    const refetchMenusSoon = jest.fn();

    const { result } = renderHook(() =>
      useMenuActivateToggle({ activateMutation, deactivateMutation, refetchMenusSoon, t: mockT })
    );

    act(() => {
      result.current('menu-123', true);
    });

    expect(notifySuccess).toHaveBeenCalledWith('Menu deactivated');
  });

  it('notifies error on failure', () => {
    const mockActivate = jest.fn((_params, options) => {
      options.onError(new Error('Activation failed'));
    });
    const activateMutation = createMockMutation(mockActivate) as unknown as ActivateMutation;
    const deactivateMutation = createMockMutation() as unknown as DeactivateMutation;
    const refetchMenusSoon = jest.fn();

    const { result } = renderHook(() =>
      useMenuActivateToggle({ activateMutation, deactivateMutation, refetchMenusSoon, t: mockT })
    );

    act(() => {
      result.current('menu-123', false);
    });

    expect(notify).toHaveBeenCalledWith('error', 'Failed to activate menu: Activation failed');
    expect(logger.error).toHaveBeenCalled();
  });
});
