import { useMutation, useQueryClient } from '@tanstack/react-query';

import { getOnlineMenuWebMenuListQueryKey, getOnlineMenuWebMenuGetByIdQueryKey } from '../server/autoGeneratedHooks/onlinemenu/tenantmenus/tenantmenus';
import { customInstance } from '../server/httpClient';

import type { UseMutationOptions, UseMutationResult } from '@tanstack/react-query';

/**
 * Activates a tenant menu by externalId.
 * @param externalId - The unique identifier of the menu to activate
 * @returns Promise that resolves when the menu is activated (204 No Content)
 */
export async function activateMenu(externalId: string): Promise<unknown> {
  return customInstance({
    url: `/api/v1/TenantMenus/${externalId}/activate`,
    method: 'PATCH',
  });
}

/**
 * Deactivates a tenant menu by externalId.
 * @param externalId - The unique identifier of the menu to deactivate
 * @returns Promise that resolves when the menu is deactivated (204 No Content)
 */
export async function deactivateMenu(externalId: string): Promise<unknown> {
  return customInstance({
    url: `/api/v1/TenantMenus/${externalId}/deactivate`,
    method: 'PATCH',
  });
}

/**
 * React Query hook for activating a menu.
 * Automatically invalidates relevant queries on success.
 *
 * @example
 * ```tsx
 * const { mutate: activate, isPending } = useActivateMenu({
 *   onSuccess: () => {
 *     showNotification('Menu activated successfully');
 *   },
 * });
 *
 * // Call it
 * activate({ externalId: 'menu-guid-here' });
 * ```
 */
export function useActivateMenu<TError = unknown, TContext = unknown>(
  options?: UseMutationOptions<
    unknown,
    TError,
    { externalId: string },
    TContext
  >
): UseMutationResult<unknown, TError, { externalId: string }, TContext> {
  const queryClient = useQueryClient();
  const { onSuccess: _onSuccess, ...restOptions } = options ?? {};

  return useMutation({
    ...restOptions,
    mutationFn: async ({ externalId }) => activateMenu(externalId),
    onSuccess: (data, variables, onMutateResult, context) => {
      // Invalidate queries to refresh the UI
      queryClient.invalidateQueries({
        queryKey: getOnlineMenuWebMenuListQueryKey(),
      }).catch(() => {
        // Ignore invalidation errors
      });
      queryClient.invalidateQueries({
        queryKey: getOnlineMenuWebMenuGetByIdQueryKey(variables.externalId),
      }).catch(() => {
        // Ignore invalidation errors
      });

      if (options?.onSuccess)
        options.onSuccess(data, variables, onMutateResult, context);

    },
  });
}

/**
 * React Query hook for deactivating a menu.
 * Automatically invalidates relevant queries on success.
 *
 * @example
 * ```tsx
 * const { mutate: deactivate, isPending } = useDeactivateMenu({
 *   onSuccess: () => {
 *     showNotification('Menu deactivated successfully');
 *   },
 * });
 *
 * // Call it
 * deactivate({ externalId: 'menu-guid-here' });
 * ```
 */
export function useDeactivateMenu<TError = unknown, TContext = unknown>(
  options?: UseMutationOptions<
    unknown,
    TError,
    { externalId: string },
    TContext
  >
): UseMutationResult<unknown, TError, { externalId: string }, TContext> {
  const queryClient = useQueryClient();
  const { onSuccess: _onSuccess, ...restOptions } = options ?? {};

  return useMutation({
    ...restOptions,
    mutationFn: async ({ externalId }) => deactivateMenu(externalId),
    onSuccess: (data, variables, onMutateResult, context) => {
      // Invalidate queries to refresh the UI
      queryClient.invalidateQueries({
        queryKey: getOnlineMenuWebMenuListQueryKey(),
      }).catch(() => {
        // Ignore invalidation errors
      });
      queryClient.invalidateQueries({
        queryKey: getOnlineMenuWebMenuGetByIdQueryKey(variables.externalId),
      }).catch(() => {
        // Ignore invalidation errors
      });

      if (options?.onSuccess)
        options.onSuccess(data, variables, onMutateResult, context);

    },
  });
}
