/**
 * Tests for usePasswordSubmit hook.
 * Focus on testing password update callbacks and notifications.
 */
import './userPageHandlers.setupMocks';

import { renderHook, act } from '@testing-library/react-native';

import { usePasswordSubmit } from './useUserPageHandlers';
import { notify, notifySuccess } from '../lib/notifications';

import type { PasswordSubmitState } from './userPageHandlers.testTypes';
import type { useIdentityServiceAPIUsersUpdatePassword } from '../server/autoGeneratedHooks/identity/users/users';

type UpdatePasswordMutation = ReturnType<typeof useIdentityServiceAPIUsersUpdatePassword>;

describe('usePasswordSubmit', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  it('does nothing when passwordResetUserId is null', () => {
    const mockMutate = jest.fn();
    const updatePasswordMutation = { mutate: mockMutate } as unknown as UpdatePasswordMutation;
    const state: PasswordSubmitState = {
      passwordResetUserId: null,
      newPassword: 'newpassword',
      closeModal: jest.fn(),
    };

    const { result } = renderHook(() =>
      usePasswordSubmit(updatePasswordMutation, state)
    );

    act(() => {
      result.current();
    });

    expect(mockMutate).not.toHaveBeenCalled();
  });

  it('does nothing when newPassword is empty', () => {
    const mockMutate = jest.fn();
    const updatePasswordMutation = { mutate: mockMutate } as unknown as UpdatePasswordMutation;
    const state: PasswordSubmitState = {
      passwordResetUserId: 'user-123',
      newPassword: '   ',
      closeModal: jest.fn(),
    };

    const { result } = renderHook(() =>
      usePasswordSubmit(updatePasswordMutation, state)
    );

    act(() => {
      result.current();
    });

    expect(mockMutate).not.toHaveBeenCalled();
  });

  it('calls mutation with correct params', () => {
    const mockMutate = jest.fn();
    const updatePasswordMutation = { mutate: mockMutate } as unknown as UpdatePasswordMutation;
    const state: PasswordSubmitState = {
      passwordResetUserId: 'user-123',
      newPassword: '  newpassword  ',
      closeModal: jest.fn(),
    };

    const { result } = renderHook(() =>
      usePasswordSubmit(updatePasswordMutation, state)
    );

    act(() => {
      result.current();
    });

    expect(mockMutate).toHaveBeenCalledWith(
      {
        userId: 'user-123',
        data: { newPassword: 'newpassword', temporary: false },
      },
      expect.any(Object)
    );
  });

  it('notifies success and closes modal on success', () => {
    const mockMutate = jest.fn((_, options) => {
      options.onSuccess();
    });
    const updatePasswordMutation = { mutate: mockMutate } as unknown as UpdatePasswordMutation;
    const state: PasswordSubmitState = {
      passwordResetUserId: 'user-123',
      newPassword: 'newpassword',
      closeModal: jest.fn(),
    };

    const { result } = renderHook(() =>
      usePasswordSubmit(updatePasswordMutation, state)
    );

    act(() => {
      result.current();
    });

    expect(notifySuccess).toHaveBeenCalledWith('users.messages.passwordUpdateSuccess');
    expect(state.closeModal).toHaveBeenCalled();
  });

  it('notifies error on failure', () => {
    const mockMutate = jest.fn((_, options) => {
      options.onError(new Error('Password update failed'));
    });
    const updatePasswordMutation = { mutate: mockMutate } as unknown as UpdatePasswordMutation;
    const state: PasswordSubmitState = {
      passwordResetUserId: 'user-123',
      newPassword: 'newpassword',
      closeModal: jest.fn(),
    };

    const { result } = renderHook(() =>
      usePasswordSubmit(updatePasswordMutation, state)
    );

    act(() => {
      result.current();
    });

    expect(notify).toHaveBeenCalledWith('error', {
      message: 'users.errors.passwordUpdateFailed:Password update failed',
    });
  });
});
