/**
 * Tests for useUsersList hook.
 * Focus on testing user data mapping and filtering.
 */
import './userPageHandlers.setupMocks';

import { renderHook } from '@testing-library/react-native';

import { useUsersList } from './useUserPageHandlers';

import type { MockUsersQuery } from './userPageHandlers.testTypes';
import type { useIdentityServiceAPIUsersListUsers } from '../server/autoGeneratedHooks/identity/users/users';

type UsersQuery = ReturnType<typeof useIdentityServiceAPIUsersListUsers>;

describe('useUsersList', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  it('returns empty array when usersData is not an array', () => {
    const usersQuery: MockUsersQuery = { data: { users: null } };
    const { result } = renderHook(() => useUsersList(usersQuery as unknown as UsersQuery, null));
    expect(result.current).toEqual([]);
  });

  it('maps user data correctly', () => {
    const usersQuery: MockUsersQuery = {
      data: {
        users: [
          {
            id: 'user-1',
            username: 'john',
            email: 'john@test.com',
            firstName: 'John',
            lastName: 'Doe',
            enabled: true,
            createdTimestamp: 1704067200000,
            roles: ['user'],
            tenantId: 'tenant-1',
          },
        ],
      },
    };

    const { result } = renderHook(() => useUsersList(usersQuery as unknown as UsersQuery, null));

    expect(result.current).toHaveLength(1);
    expect(result.current[0]).toEqual({
      id: 'user-1',
      username: 'john',
      email: 'john@test.com',
      firstName: 'John',
      lastName: 'Doe',
      enabled: true,
      createdTimestamp: 1704067200000,
      roles: ['user'],
      tenantId: 'tenant-1',
    });
  });

  it('handles null values in user data', () => {
    const usersQuery: MockUsersQuery = {
      data: {
        users: [
          {
            id: null,
            username: null,
            email: null,
            firstName: null,
            lastName: null,
            enabled: null,
            createdTimestamp: null,
            roles: undefined,
            tenantId: null,
          },
        ],
      },
    };

    const { result } = renderHook(() => useUsersList(usersQuery as unknown as UsersQuery, null));

    expect(result.current[0]).toEqual({
      id: '',
      username: '',
      email: undefined,
      firstName: undefined,
      lastName: undefined,
      enabled: false,
      createdTimestamp: undefined,
      roles: undefined,
      tenantId: undefined,
    });
  });

  it('filters users by selectedTenantId', () => {
    const usersQuery: MockUsersQuery = {
      data: {
        users: [
          { id: 'user-1', username: 'john', tenantId: 'tenant-1' },
          { id: 'user-2', username: 'jane', tenantId: 'tenant-2' },
          { id: 'user-3', username: 'bob', tenantId: 'tenant-1' },
        ],
      },
    };

    const { result } = renderHook(() => useUsersList(usersQuery as unknown as UsersQuery, 'tenant-1'));

    expect(result.current).toHaveLength(2);
    expect(result.current.map((u) => u.id)).toEqual(['user-1', 'user-3']);
  });

  it('returns all users when selectedTenantId is null', () => {
    const usersQuery: MockUsersQuery = {
      data: {
        users: [
          { id: 'user-1', username: 'john', tenantId: 'tenant-1' },
          { id: 'user-2', username: 'jane', tenantId: 'tenant-2' },
        ],
      },
    };

    const { result } = renderHook(() => useUsersList(usersQuery as unknown as UsersQuery, null));

    expect(result.current).toHaveLength(2);
  });

  it('parses string createdTimestamp', () => {
    const usersQuery: MockUsersQuery = {
      data: {
        users: [
          { id: 'user-1', username: 'john', createdTimestamp: '1704067200000' },
        ],
      },
    };

    const { result } = renderHook(() => useUsersList(usersQuery as unknown as UsersQuery, null));

    expect(result.current[0].createdTimestamp).toBe(1704067200000);
  });

  it('returns undefined for invalid createdTimestamp', () => {
    const usersQuery: MockUsersQuery = {
      data: {
        users: [
          { id: 'user-1', username: 'john', createdTimestamp: 'invalid' },
        ],
      },
    };

    const { result } = renderHook(() => useUsersList(usersQuery as unknown as UsersQuery, null));

    expect(result.current[0].createdTimestamp).toBeUndefined();
  });

  it('returns undefined for empty string createdTimestamp', () => {
    const usersQuery: MockUsersQuery = {
      data: {
        users: [{ id: 'user-1', username: 'john', createdTimestamp: '' }],
      },
    };

    const { result } = renderHook(() => useUsersList(usersQuery as unknown as UsersQuery, null));

    expect(result.current[0].createdTimestamp).toBeUndefined();
  });

  it('returns undefined for non-finite numeric createdTimestamp', () => {
    const usersQuery: MockUsersQuery = {
      data: {
        users: [
          { id: 'user-1', username: 'john', createdTimestamp: Infinity },
        ],
      },
    };

    const { result } = renderHook(() => useUsersList(usersQuery as unknown as UsersQuery, null));

    expect(result.current[0].createdTimestamp).toBeUndefined();
  });
});
