/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OnlineMenu.Web
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  OnlineMenuWebPublicApiListMenusParams,
  PublicApiMenuDetailResponse,
  PublicApiMenuItemResponse,
  PublicApiPaginatedResponseOfPublicApiMenuResponse,
} from '.././models';

import { customInstance } from '../../../mutators/onlineMenuMutator';

/**
 * @summary Public API endpoint to get a menu with full details.
Requires API key authentication via X-Api-Key header.
 */
export const onlineMenuWebPublicApiGetMenuById = (id: string, signal?: AbortSignal) => {
  return customInstance<PublicApiMenuDetailResponse>({
    url: `/api/v1/public-api/menus/${id}`,
    method: 'GET',
    signal,
  });
};

export const getOnlineMenuWebPublicApiGetMenuByIdQueryKey = (id?: string) => {
  return [`/api/v1/public-api/menus/${id}`] as const;
};

export const getOnlineMenuWebPublicApiGetMenuByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof onlineMenuWebPublicApiGetMenuById>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof onlineMenuWebPublicApiGetMenuById>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getOnlineMenuWebPublicApiGetMenuByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof onlineMenuWebPublicApiGetMenuById>>> = ({
    signal,
  }) => onlineMenuWebPublicApiGetMenuById(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof onlineMenuWebPublicApiGetMenuById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type OnlineMenuWebPublicApiGetMenuByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof onlineMenuWebPublicApiGetMenuById>>
>;
export type OnlineMenuWebPublicApiGetMenuByIdQueryError = void;

export function useOnlineMenuWebPublicApiGetMenuById<
  TData = Awaited<ReturnType<typeof onlineMenuWebPublicApiGetMenuById>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof onlineMenuWebPublicApiGetMenuById>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof onlineMenuWebPublicApiGetMenuById>>,
          TError,
          Awaited<ReturnType<typeof onlineMenuWebPublicApiGetMenuById>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useOnlineMenuWebPublicApiGetMenuById<
  TData = Awaited<ReturnType<typeof onlineMenuWebPublicApiGetMenuById>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof onlineMenuWebPublicApiGetMenuById>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof onlineMenuWebPublicApiGetMenuById>>,
          TError,
          Awaited<ReturnType<typeof onlineMenuWebPublicApiGetMenuById>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useOnlineMenuWebPublicApiGetMenuById<
  TData = Awaited<ReturnType<typeof onlineMenuWebPublicApiGetMenuById>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof onlineMenuWebPublicApiGetMenuById>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Public API endpoint to get a menu with full details.
Requires API key authentication via X-Api-Key header.
 */

export function useOnlineMenuWebPublicApiGetMenuById<
  TData = Awaited<ReturnType<typeof onlineMenuWebPublicApiGetMenuById>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof onlineMenuWebPublicApiGetMenuById>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getOnlineMenuWebPublicApiGetMenuByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Public API endpoint to get all items for a specific menu (flattened across categories).
Requires API key authentication via X-Api-Key header.
 */
export const onlineMenuWebPublicApiGetMenuItems = (id: string, signal?: AbortSignal) => {
  return customInstance<PublicApiMenuItemResponse[]>({
    url: `/api/v1/public-api/menus/${id}/items`,
    method: 'GET',
    signal,
  });
};

export const getOnlineMenuWebPublicApiGetMenuItemsQueryKey = (id?: string) => {
  return [`/api/v1/public-api/menus/${id}/items`] as const;
};

export const getOnlineMenuWebPublicApiGetMenuItemsQueryOptions = <
  TData = Awaited<ReturnType<typeof onlineMenuWebPublicApiGetMenuItems>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof onlineMenuWebPublicApiGetMenuItems>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getOnlineMenuWebPublicApiGetMenuItemsQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof onlineMenuWebPublicApiGetMenuItems>>> = ({
    signal,
  }) => onlineMenuWebPublicApiGetMenuItems(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof onlineMenuWebPublicApiGetMenuItems>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type OnlineMenuWebPublicApiGetMenuItemsQueryResult = NonNullable<
  Awaited<ReturnType<typeof onlineMenuWebPublicApiGetMenuItems>>
>;
export type OnlineMenuWebPublicApiGetMenuItemsQueryError = void;

export function useOnlineMenuWebPublicApiGetMenuItems<
  TData = Awaited<ReturnType<typeof onlineMenuWebPublicApiGetMenuItems>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof onlineMenuWebPublicApiGetMenuItems>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof onlineMenuWebPublicApiGetMenuItems>>,
          TError,
          Awaited<ReturnType<typeof onlineMenuWebPublicApiGetMenuItems>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useOnlineMenuWebPublicApiGetMenuItems<
  TData = Awaited<ReturnType<typeof onlineMenuWebPublicApiGetMenuItems>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof onlineMenuWebPublicApiGetMenuItems>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof onlineMenuWebPublicApiGetMenuItems>>,
          TError,
          Awaited<ReturnType<typeof onlineMenuWebPublicApiGetMenuItems>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useOnlineMenuWebPublicApiGetMenuItems<
  TData = Awaited<ReturnType<typeof onlineMenuWebPublicApiGetMenuItems>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof onlineMenuWebPublicApiGetMenuItems>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Public API endpoint to get all items for a specific menu (flattened across categories).
Requires API key authentication via X-Api-Key header.
 */

export function useOnlineMenuWebPublicApiGetMenuItems<
  TData = Awaited<ReturnType<typeof onlineMenuWebPublicApiGetMenuItems>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof onlineMenuWebPublicApiGetMenuItems>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getOnlineMenuWebPublicApiGetMenuItemsQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Public API endpoint to list active menus for the authenticated tenant.
Requires API key authentication via X-Api-Key header.
 */
export const onlineMenuWebPublicApiListMenus = (
  params: OnlineMenuWebPublicApiListMenusParams,
  signal?: AbortSignal
) => {
  return customInstance<PublicApiPaginatedResponseOfPublicApiMenuResponse>({
    url: `/api/v1/public-api/menus`,
    method: 'GET',
    params,
    signal,
  });
};

export const getOnlineMenuWebPublicApiListMenusQueryKey = (
  params?: OnlineMenuWebPublicApiListMenusParams
) => {
  return [`/api/v1/public-api/menus`, ...(params ? [params] : [])] as const;
};

export const getOnlineMenuWebPublicApiListMenusQueryOptions = <
  TData = Awaited<ReturnType<typeof onlineMenuWebPublicApiListMenus>>,
  TError = void,
>(
  params: OnlineMenuWebPublicApiListMenusParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof onlineMenuWebPublicApiListMenus>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getOnlineMenuWebPublicApiListMenusQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof onlineMenuWebPublicApiListMenus>>> = ({
    signal,
  }) => onlineMenuWebPublicApiListMenus(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof onlineMenuWebPublicApiListMenus>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type OnlineMenuWebPublicApiListMenusQueryResult = NonNullable<
  Awaited<ReturnType<typeof onlineMenuWebPublicApiListMenus>>
>;
export type OnlineMenuWebPublicApiListMenusQueryError = void;

export function useOnlineMenuWebPublicApiListMenus<
  TData = Awaited<ReturnType<typeof onlineMenuWebPublicApiListMenus>>,
  TError = void,
>(
  params: OnlineMenuWebPublicApiListMenusParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof onlineMenuWebPublicApiListMenus>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof onlineMenuWebPublicApiListMenus>>,
          TError,
          Awaited<ReturnType<typeof onlineMenuWebPublicApiListMenus>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useOnlineMenuWebPublicApiListMenus<
  TData = Awaited<ReturnType<typeof onlineMenuWebPublicApiListMenus>>,
  TError = void,
>(
  params: OnlineMenuWebPublicApiListMenusParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof onlineMenuWebPublicApiListMenus>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof onlineMenuWebPublicApiListMenus>>,
          TError,
          Awaited<ReturnType<typeof onlineMenuWebPublicApiListMenus>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useOnlineMenuWebPublicApiListMenus<
  TData = Awaited<ReturnType<typeof onlineMenuWebPublicApiListMenus>>,
  TError = void,
>(
  params: OnlineMenuWebPublicApiListMenusParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof onlineMenuWebPublicApiListMenus>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Public API endpoint to list active menus for the authenticated tenant.
Requires API key authentication via X-Api-Key header.
 */

export function useOnlineMenuWebPublicApiListMenus<
  TData = Awaited<ReturnType<typeof onlineMenuWebPublicApiListMenus>>,
  TError = void,
>(
  params: OnlineMenuWebPublicApiListMenusParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof onlineMenuWebPublicApiListMenus>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getOnlineMenuWebPublicApiListMenusQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
