/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Notification Service API
 * OpenAPI spec version: v1
 */

/**
 * Response after creating a webhook subscription.
 */
export interface CreateWebhookResponse {
  id?: string;
  name?: string;
  targetUrl?: string;
  events?: string[];
  status?: string;
  signingSecret?: string;
  createdAt?: string;
}
