/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Notification Service API
 * OpenAPI spec version: v1
 */

/**
 * Request to delete a webhook by its external ID.
 */
export interface DeleteWebhookRequest {
  [key: string]: unknown;
}
