/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Notification Service API
 * OpenAPI spec version: v1
 */
import type { NotificationDto } from './notificationDto';

export interface ListNotificationsResponse {
  notifications?: NotificationDto[];
}
