/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Notification Service API
 * OpenAPI spec version: v1
 */
import type { WebhookSummaryDto } from './webhookSummaryDto';

/**
 * Response containing list of webhook subscriptions.
 */
export interface ListWebhooksResponse {
  subscriptions?: WebhookSummaryDto[];
}
