/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Notification Service API
 * OpenAPI spec version: v1
 */
import type { WebhookDeliveryDto } from './webhookDeliveryDto';

/**
 * Response containing list of webhook deliveries.
 */
export interface ListDeliveriesResponse {
  deliveries?: WebhookDeliveryDto[];
}
