/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Notification Service API
 * OpenAPI spec version: v1
 */

export type NotificationWebNotificationsListParams = {
  skip: number;
  take: number;
  unreadOnly: boolean;
};
