/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Notification Service API
 * OpenAPI spec version: v1
 */

/**
 * Request to update a webhook subscription.
 */
export interface UpdateWebhookRequest {
  /**
   * Updated name (optional).
   * @nullable
   */
  name?: string | null;
  /**
   * Updated target URL (optional).
   * @nullable
   */
  targetUrl?: string | null;
  /**
   * Updated event types list (optional).
   * @nullable
   */
  events?: string[] | null;
}
