/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Notification Service API
 * OpenAPI spec version: v1
 */

/**
 * Detailed DTO for a webhook subscription (does not expose signing secret).
 */
export interface WebhookDetailDto {
  id?: string;
  name?: string;
  targetUrl?: string;
  eventTypes?: string;
  status?: string;
  consecutiveFailures?: number;
  /** @nullable */
  lastDeliveryAt?: string | null;
  /** @nullable */
  lastSuccessAt?: string | null;
  createdAt?: string;
  lastUpdatedAt?: string;
}
