import { useMemo } from 'react';

import type { DashboardData } from '@/components/Dashboard/types';
import { useOnlineMenuWebMenuList } from '@/server/autoGeneratedHooks/onlinemenu/tenantmenus/tenantmenus';

/**
 * Katalogos is the OnlineMenu product. The dashboard never reads
 * questioner data -- calling the questioner template hook here would
 * (a) make a wasted network call to questioner-api.dloizides.com, and
 * (b) leak through the cross-realm wall (the questioner API rejects
 * onlinemenu-realm tokens with 401, polluting error monitoring).
 *
 * The questioner query was removed as part of the Phase-3 product
 * feature-strip. The DashboardData shape is shared with Erevna, so
 * `templateCount` / `hasTemplates` remain in the returned object but
 * are hard-coded to zero/false.
 */
export function useDashboardData(): DashboardData {
  const menuQuery = useOnlineMenuWebMenuList();

  return useMemo((): DashboardData => {
    const menus = menuQuery.data?.menus;
    const menuCount = Array.isArray(menus) ? menus.length : 0;
    const hasMenus = menuCount > 0;

    return {
      menuCount,
      templateCount: 0,
      isLoading: menuQuery.isLoading,
      hasMenus,
      hasTemplates: false,
      isEmpty: !hasMenus,
    };
  }, [menuQuery.data, menuQuery.isLoading]);
}
