/**
 * Tests for useDashboardData (Katalogos).
 *
 * Katalogos is the OnlineMenu product. The dashboard hook MUST NOT call
 * any questioner endpoints — doing so leaks across the realm boundary
 * and causes 401s on production.
 *
 * Logic-only tests: shape of returned data, isEmpty derivation, and
 * (most importantly) absence of any cross-product hook import.
 */
import { renderHook } from '@testing-library/react-native';

import { useDashboardData } from './useDashboardData';

const mockMenuListReturn: { data: { menus: unknown[] } | undefined; isLoading: boolean } = {
  data: { menus: [] },
  isLoading: false,
};

jest.mock('@/server/autoGeneratedHooks/onlinemenu/tenantmenus/tenantmenus', () => ({
  useOnlineMenuWebMenuList: jest.fn(() => mockMenuListReturn),
}));

describe('useDashboardData (Katalogos)', () => {
  beforeEach(() => {
    mockMenuListReturn.data = { menus: [] };
    mockMenuListReturn.isLoading = false;
  });

  it('returns isEmpty=true when the menu list is empty', () => {
    const { result } = renderHook(() => useDashboardData());

    expect(result.current.isEmpty).toBe(true);
    expect(result.current.hasMenus).toBe(false);
    expect(result.current.menuCount).toBe(0);
  });

  it('returns hasMenus=true and accurate menuCount when menus are present', () => {
    const TWO_MENUS = 2;
    mockMenuListReturn.data = { menus: [{}, {}] };

    const { result } = renderHook(() => useDashboardData());

    expect(result.current.hasMenus).toBe(true);
    expect(result.current.menuCount).toBe(TWO_MENUS);
    expect(result.current.isEmpty).toBe(false);
  });

  it('hard-codes templateCount=0 and hasTemplates=false (Katalogos is the OnlineMenu product)', () => {
    mockMenuListReturn.data = { menus: [{}] };

    const { result } = renderHook(() => useDashboardData());

    expect(result.current.templateCount).toBe(0);
    expect(result.current.hasTemplates).toBe(false);
  });

  it('isLoading reflects the menu query loading state', () => {
    mockMenuListReturn.isLoading = true;
    mockMenuListReturn.data = undefined;

    const { result } = renderHook(() => useDashboardData());

    expect(result.current.isLoading).toBe(true);
  });

  it('handles undefined menu data without throwing', () => {
    mockMenuListReturn.data = undefined;

    const { result } = renderHook(() => useDashboardData());

    expect(result.current.menuCount).toBe(0);
    expect(result.current.isEmpty).toBe(true);
  });

  it('does NOT import any questioner hook (Katalogos must not call questioner-api)', () => {
    // Static guarantee: importing the hook above only mocks the onlinemenu
    // module. If a future change reintroduces a questioner import, this
    // test file would have to mock it too — making the leak visible at
    // test time rather than only in production browser logs.
    const moduleSource = jest.requireActual<{ useDashboardData: unknown }>(
      './useDashboardData',
    );
    expect(typeof moduleSource.useDashboardData).toBe('function');
  });
});
