import { useCallback, useMemo, useState } from 'react';

import type { DashboardData } from '@/components/Dashboard/types';
import { featureFlags } from '@/config/featureFlags';
import { useIdentityServiceAPIMeGetBusinessProfile } from '@/server/autoGeneratedHooks/identity/me/me';
import type { ListTenantMenusResponse } from '@/server/autoGeneratedHooks/onlinemenu/models';
import { useOnlineMenuWebMenuList } from '@/server/autoGeneratedHooks/onlinemenu/tenantmenus/tenantmenus';
import SetupChecklistStep from '@/shared/enums/SetupChecklistStep';
import { isValueDefined } from '@/utils/is';

import {
  CHECKLIST_DISMISSED_KEY,
  CHECKLIST_MENU_SHARED_KEY,
  CHECKLIST_QR_GENERATED_KEY,
  TOTAL_CHECKLIST_STEPS,
} from '../utils/setupChecklistConstants';

import type { PreferencesInput } from './useWelcomeWizard';

interface ChecklistItem {
  step: SetupChecklistStep;
  completed: boolean;
}

export interface SetupChecklistState {
  items: ChecklistItem[];
  completedCount: number;
  totalSteps: number;
  allComplete: boolean;
  isVisible: boolean;
  isLoading: boolean;
  handleDismiss: () => void;
}

const QUERY_OPTIONS_DISABLED = { query: { enabled: false } } as const;

function hasMenuItems(menuData: ListTenantMenusResponse | undefined): boolean {
  const menus = menuData?.menus;
  if (!Array.isArray(menus)) return false;

  return menus.some((menu) => {
    const categories = menu.contents?.categories;
    if (!Array.isArray(categories)) return false;
    return categories.some((cat) => Array.isArray(cat.items) && cat.items.length > 0);
  });
}

function readLocalStorageFlag(key: string): boolean {
  return localStorage.getItem(key) === 'true';
}

function isDismissedFromLocalStorage(): boolean {
  return readLocalStorageFlag(CHECKLIST_DISMISSED_KEY);
}

interface ChecklistInputs {
  logoUrl: string | null | undefined;
  hasMenus: boolean;
  menuData: ListTenantMenusResponse | undefined;
}

function buildChecklistItems(inputs: ChecklistInputs): ChecklistItem[] {
  const hasLogo = isValueDefined(inputs.logoUrl) && inputs.logoUrl !== '';
  const hasItems = hasMenuItems(inputs.menuData);
  const qrGenerated = readLocalStorageFlag(CHECKLIST_QR_GENERATED_KEY);
  const menuShared = readLocalStorageFlag(CHECKLIST_MENU_SHARED_KEY);

  return [
    { step: SetupChecklistStep.UploadLogo, completed: hasLogo },
    { step: SetupChecklistStep.CreateMenu, completed: inputs.hasMenus },
    { step: SetupChecklistStep.AddItems, completed: hasItems },
    { step: SetupChecklistStep.GenerateQr, completed: qrGenerated },
    { step: SetupChecklistStep.ShareMenu, completed: menuShared },
  ];
}

export function useSetupChecklist(
  dashboardData: DashboardData,
  preferences: PreferencesInput,
): SetupChecklistState {
  const [localDismissed, setLocalDismissed] = useState(isDismissedFromLocalStorage);

  const serverDismissed = preferences.data?.checklistDismissed ?? false;
  const dismissed = localDismissed || serverDismissed;

  const menuEnabled = featureFlags.onlineMenuModule;
  const menuQueryOptions = menuEnabled ? undefined : QUERY_OPTIONS_DISABLED;
  const menuQuery = useOnlineMenuWebMenuList(menuQueryOptions);
  const profileQuery = useIdentityServiceAPIMeGetBusinessProfile();

  const handleDismiss = useCallback((): void => {
    localStorage.setItem(CHECKLIST_DISMISSED_KEY, 'true');
    setLocalDismissed(true);
    preferences.updatePreferences({ ...preferences.data, checklistDismissed: true });
  }, [preferences]);

  return useMemo((): SetupChecklistState => {
    const items = buildChecklistItems({ logoUrl: profileQuery.data?.logoUrl, hasMenus: dashboardData.hasMenus, menuData: menuQuery.data });
    const completedCount = items.filter((i) => i.completed).length;
    const allComplete = completedCount === TOTAL_CHECKLIST_STEPS;
    const isLoading = profileQuery.isLoading || menuQuery.isLoading;
    const isVisible = !dismissed && !allComplete && !isLoading;

    return { items, completedCount, totalSteps: TOTAL_CHECKLIST_STEPS, allComplete, isVisible, isLoading, handleDismiss };
  }, [profileQuery.data, profileQuery.isLoading, dashboardData.hasMenus, menuQuery.data, menuQuery.isLoading, dismissed, handleDismiss]);
}
