/**
 * Tests for useSetupChecklist hook.
 * Focuses on completion detection logic, visibility, and dismiss behavior.
 */
import { renderHook, act } from '@testing-library/react-native';

import type { DashboardData } from '@/components/Dashboard/types';
import SetupChecklistStep from '@/shared/enums/SetupChecklistStep';

import { useSetupChecklist } from './useSetupChecklist';
import {
  CHECKLIST_DISMISSED_KEY,
  CHECKLIST_MENU_SHARED_KEY,
  CHECKLIST_QR_GENERATED_KEY,
  TOTAL_CHECKLIST_STEPS,
} from '../utils/setupChecklistConstants';

import type { PreferencesInput } from './useWelcomeWizard';

const mockProfileData = { logoUrl: null as string | null };
const mockMenuData = { menus: [] as Array<{ contents?: { categories?: Array<{ items?: unknown[] }> } }> };
const mockUpdatePreferences = jest.fn();

function createMockPreferences(): PreferencesInput {
  return { data: undefined, isLoading: false, updatePreferences: mockUpdatePreferences };
}

jest.mock('@/config/featureFlags', () => ({
  featureFlags: { onlineMenuModule: true },
}));

jest.mock('@/server/autoGeneratedHooks/identity/me/me', () => ({
  useIdentityServiceAPIMeGetBusinessProfile: () => ({
    data: mockProfileData,
    isLoading: false,
  }),
}));

jest.mock('@/server/autoGeneratedHooks/onlinemenu/tenantmenus/tenantmenus', () => ({
  useOnlineMenuWebMenuList: () => ({
    data: mockMenuData,
    isLoading: false,
  }),
}));

const EMPTY_DASHBOARD: DashboardData = {
  menuCount: 0,
  templateCount: 0,
  isLoading: false,
  hasMenus: false,
  hasTemplates: false,
  isEmpty: true,
};

const DASHBOARD_WITH_MENUS: DashboardData = {
  menuCount: 1,
  templateCount: 0,
  isLoading: false,
  hasMenus: true,
  hasTemplates: false,
  isEmpty: false,
};

describe('useSetupChecklist', () => {
  beforeEach(() => {
    localStorage.clear();
    mockProfileData.logoUrl = null;
    mockMenuData.menus = [];
    mockUpdatePreferences.mockClear();
  });

  it('returns 5 checklist items', () => {
    const { result } = renderHook(() => useSetupChecklist(EMPTY_DASHBOARD, createMockPreferences()));
    expect(result.current.items).toHaveLength(TOTAL_CHECKLIST_STEPS);
    expect(result.current.totalSteps).toBe(TOTAL_CHECKLIST_STEPS);
  });

  it('detects logo upload from business profile', () => {
    mockProfileData.logoUrl = 'some-content-id';
    const { result } = renderHook(() => useSetupChecklist(EMPTY_DASHBOARD, createMockPreferences()));
    const logoItem = result.current.items.find((i) => i.step === SetupChecklistStep.UploadLogo);
    expect(logoItem?.completed).toBe(true);
  });

  it('marks logo incomplete when logoUrl is null', () => {
    mockProfileData.logoUrl = null;
    const { result } = renderHook(() => useSetupChecklist(EMPTY_DASHBOARD, createMockPreferences()));
    const logoItem = result.current.items.find((i) => i.step === SetupChecklistStep.UploadLogo);
    expect(logoItem?.completed).toBe(false);
  });

  it('marks logo incomplete when logoUrl is empty string', () => {
    mockProfileData.logoUrl = '';
    const { result } = renderHook(() => useSetupChecklist(EMPTY_DASHBOARD, createMockPreferences()));
    const logoItem = result.current.items.find((i) => i.step === SetupChecklistStep.UploadLogo);
    expect(logoItem?.completed).toBe(false);
  });

  it('detects menu creation from dashboard data', () => {
    const { result } = renderHook(() => useSetupChecklist(DASHBOARD_WITH_MENUS, createMockPreferences()));
    const menuItem = result.current.items.find((i) => i.step === SetupChecklistStep.CreateMenu);
    expect(menuItem?.completed).toBe(true);
  });

  it('marks menu creation incomplete when no menus', () => {
    const { result } = renderHook(() => useSetupChecklist(EMPTY_DASHBOARD, createMockPreferences()));
    const menuItem = result.current.items.find((i) => i.step === SetupChecklistStep.CreateMenu);
    expect(menuItem?.completed).toBe(false);
  });

  it('detects menu items from menu contents', () => {
    mockMenuData.menus = [{ contents: { categories: [{ items: [{ name: 'Pizza' }] }] } }];
    const { result } = renderHook(() => useSetupChecklist(DASHBOARD_WITH_MENUS, createMockPreferences()));
    const addItemsItem = result.current.items.find((i) => i.step === SetupChecklistStep.AddItems);
    expect(addItemsItem?.completed).toBe(true);
  });

  it('marks add items incomplete when categories have no items', () => {
    mockMenuData.menus = [{ contents: { categories: [{ items: [] }] } }];
    const { result } = renderHook(() => useSetupChecklist(DASHBOARD_WITH_MENUS, createMockPreferences()));
    const addItemsItem = result.current.items.find((i) => i.step === SetupChecklistStep.AddItems);
    expect(addItemsItem?.completed).toBe(false);
  });

  it('detects QR generation from localStorage', () => {
    localStorage.setItem(CHECKLIST_QR_GENERATED_KEY, 'true');
    const { result } = renderHook(() => useSetupChecklist(EMPTY_DASHBOARD, createMockPreferences()));
    const qrItem = result.current.items.find((i) => i.step === SetupChecklistStep.GenerateQr);
    expect(qrItem?.completed).toBe(true);
  });

  it('detects menu sharing from localStorage', () => {
    localStorage.setItem(CHECKLIST_MENU_SHARED_KEY, 'true');
    const { result } = renderHook(() => useSetupChecklist(EMPTY_DASHBOARD, createMockPreferences()));
    const shareItem = result.current.items.find((i) => i.step === SetupChecklistStep.ShareMenu);
    expect(shareItem?.completed).toBe(true);
  });

  it('counts completed steps correctly', () => {
    mockProfileData.logoUrl = 'logo-id';
    localStorage.setItem(CHECKLIST_QR_GENERATED_KEY, 'true');
    const { result } = renderHook(() => useSetupChecklist(DASHBOARD_WITH_MENUS, createMockPreferences()));
    const EXPECTED_COMPLETED = 3; // logo + createMenu + QR
    expect(result.current.completedCount).toBe(EXPECTED_COMPLETED);
  });

  it('is visible when not all steps complete and not dismissed', () => {
    const { result } = renderHook(() => useSetupChecklist(EMPTY_DASHBOARD, createMockPreferences()));
    expect(result.current.isVisible).toBe(true);
  });

  it('hides when dismissed via handleDismiss', () => {
    const { result } = renderHook(() => useSetupChecklist(EMPTY_DASHBOARD, createMockPreferences()));
    expect(result.current.isVisible).toBe(true);
    act(() => { result.current.handleDismiss(); });
    expect(result.current.isVisible).toBe(false);
    expect(localStorage.getItem(CHECKLIST_DISMISSED_KEY)).toBe('true');
  });

  it('hides when already dismissed in localStorage', () => {
    localStorage.setItem(CHECKLIST_DISMISSED_KEY, 'true');
    const { result } = renderHook(() => useSetupChecklist(EMPTY_DASHBOARD, createMockPreferences()));
    expect(result.current.isVisible).toBe(false);
  });

  it('hides when all steps are complete', () => {
    mockProfileData.logoUrl = 'logo-id';
    mockMenuData.menus = [{ contents: { categories: [{ items: [{ name: 'Burger' }] }] } }];
    localStorage.setItem(CHECKLIST_QR_GENERATED_KEY, 'true');
    localStorage.setItem(CHECKLIST_MENU_SHARED_KEY, 'true');
    const { result } = renderHook(() => useSetupChecklist(DASHBOARD_WITH_MENUS, createMockPreferences()));
    expect(result.current.allComplete).toBe(true);
    expect(result.current.isVisible).toBe(false);
  });

  it('reports allComplete as false when some steps incomplete', () => {
    mockProfileData.logoUrl = 'logo-id';
    const { result } = renderHook(() => useSetupChecklist(EMPTY_DASHBOARD, createMockPreferences()));
    expect(result.current.allComplete).toBe(false);
  });

  // --- Server-side state tests ---

  it('hides checklist when server preferences say checklistDismissed is true', () => {
    const prefs = createMockPreferences();
    prefs.data = { checklistDismissed: true };
    const { result } = renderHook(() => useSetupChecklist(EMPTY_DASHBOARD, prefs));
    expect(result.current.isVisible).toBe(false);
  });

  it('calls updatePreferences with checklistDismissed on handleDismiss', () => {
    const mockUpdate = jest.fn();
    const prefs: PreferencesInput = {
      data: { language: 'en', timezone: 'UTC' },
      isLoading: false,
      updatePreferences: mockUpdate,
    };
    const { result } = renderHook(() => useSetupChecklist(EMPTY_DASHBOARD, prefs));
    act(() => { result.current.handleDismiss(); });
    expect(mockUpdate).toHaveBeenCalledWith({
      language: 'en',
      timezone: 'UTC',
      checklistDismissed: true,
    });
  });

  it('uses localStorage fast-path even before server responds', () => {
    localStorage.setItem(CHECKLIST_DISMISSED_KEY, 'true');
    const prefs = createMockPreferences();
    prefs.isLoading = true;
    prefs.data = undefined;
    const { result } = renderHook(() => useSetupChecklist(EMPTY_DASHBOARD, prefs));
    expect(result.current.isVisible).toBe(false);
  });

  it('shows checklist when server says not dismissed and localStorage empty', () => {
    const prefs = createMockPreferences();
    prefs.data = { checklistDismissed: false };
    const { result } = renderHook(() => useSetupChecklist(EMPTY_DASHBOARD, prefs));
    expect(result.current.isVisible).toBe(true);
  });
});
