import { useCallback, useEffect, useMemo, useState } from 'react';

import { useAuth } from '@/auth/AuthProvider';
import type { DashboardData } from '@/components/Dashboard/types';
import { useCurrentTenant } from '@/hooks/tenants';
import type {
  IdentityServiceAPIMeUpdatePreferencesRequest,
  IdentityServiceAPIMeUserPreferenceResponse,
} from '@/server/autoGeneratedHooks/identity/models';
import { useIdentityServiceAPITenantsUpdateTenant } from '@/server/autoGeneratedHooks/identity/tenants/tenants';
import type { CreateTenantMenusRequest } from '@/server/autoGeneratedHooks/onlinemenu/models';
import { useOnlineMenuWebTenantMenusCreate } from '@/server/autoGeneratedHooks/onlinemenu/tenantmenus/tenantmenus';
import WizardStep from '@/shared/enums/WizardStep';
import { isValueDefined } from '@/utils/is';

/** Extended request type that includes the optional templateSlug field accepted by the backend. */
interface CreateMenuWithTemplate extends CreateTenantMenusRequest {
  templateSlug?: string;
}

/** Preferences state passed from DashboardPage to avoid duplicate API calls. */
export interface PreferencesInput {
  data: IdentityServiceAPIMeUserPreferenceResponse | undefined;
  isLoading: boolean;
  updatePreferences: (data: IdentityServiceAPIMeUpdatePreferencesRequest) => void;
}

const WIZARD_COMPLETED_KEY = 'menuflow_onboarding_completed';

export interface WelcomeWizardState {
  step: WizardStep;
  businessName: string;
  logoContentId: string | null;
  menuName: string;
  menuDescription: string;
  selectedTemplateSlug: string | null;
  isSubmitting: boolean;
  isWizardVisible: boolean;
  setBusinessName: (value: string) => void;
  setLogoContentId: (value: string | null) => void;
  setMenuName: (value: string) => void;
  setMenuDescription: (value: string) => void;
  setSelectedTemplateSlug: (value: string | null) => void;
  handleContinue: () => void;
  handleSkip: () => void;
  handleComplete: () => void;
}

function isWizardCompleted(): boolean {
  return localStorage.getItem(WIZARD_COMPLETED_KEY) === 'true';
}

function markWizardCompleted(): void {
  localStorage.setItem(WIZARD_COMPLETED_KEY, 'true');
}

function advanceStep(current: WizardStep, setStep: (s: WizardStep) => void): void {
  switch (current) {
    case WizardStep.BusinessName: setStep(WizardStep.Logo); break;
    case WizardStep.Logo: setStep(WizardStep.CreateMenu); break;
    case WizardStep.CreateMenu: setStep(WizardStep.Completed); break;
    case WizardStep.Completed: break;
    default: break;
  }
}

interface ContinueArgs {
  step: WizardStep;
  businessName: string;
  logoContentId: string | null;
  menuName: string;
  menuDescription: string;
  selectedTemplateSlug: string | null;
  tenantId: string | undefined;
  updateTenant: ReturnType<typeof useIdentityServiceAPITenantsUpdateTenant>;
  createMenu: ReturnType<typeof useOnlineMenuWebTenantMenusCreate>;
  advance: (s: WizardStep) => void;
  setStep: (s: WizardStep) => void;
}

function executeContinue(a: ContinueArgs): void {
  switch (a.step) {
    case WizardStep.BusinessName: {
      if (a.businessName.trim() === '' || !isValueDefined(a.tenantId)) {
        a.advance(WizardStep.BusinessName);
        return;
      }
      a.updateTenant.mutate({ data: { tenantId: a.tenantId, name: a.businessName.trim() } }, { onSuccess: () => a.advance(WizardStep.BusinessName) });
      break;
    }
    case WizardStep.Logo: {
      if (!isValueDefined(a.logoContentId) || !isValueDefined(a.tenantId)) {
        a.advance(WizardStep.Logo);
        return;
      }
      a.updateTenant.mutate({ data: { tenantId: a.tenantId, logoUrl: a.logoContentId } }, { onSuccess: () => a.advance(WizardStep.Logo) });
      break;
    }
    case WizardStep.CreateMenu: {
      if (a.menuName.trim() === '') return;
      const desc = a.menuDescription.trim() !== '' ? a.menuDescription.trim() : null;
      const baseRequest: CreateTenantMenusRequest = { name: a.menuName.trim(), description: desc };
      const data: CreateMenuWithTemplate = { ...baseRequest, templateSlug: a.selectedTemplateSlug ?? undefined };
      a.createMenu.mutate({ data }, { onSuccess: () => a.setStep(WizardStep.Completed) });
      break;
    }
    case WizardStep.Completed: break;
    default: break;
  }
}

function useWizardFormState(): {
  step: WizardStep; setStep: (s: WizardStep) => void;
  businessName: string; setBusinessName: (v: string) => void;
  logoContentId: string | null; setLogoContentId: (v: string | null) => void;
  menuName: string; setMenuName: (v: string) => void;
  menuDescription: string; setMenuDescription: (v: string) => void;
  selectedTemplateSlug: string | null; setSelectedTemplateSlug: (v: string | null) => void;
  localWizardDone: boolean; setLocalWizardDone: (v: boolean) => void;
} {
  const [step, setStep] = useState<WizardStep>(WizardStep.BusinessName);
  const [businessName, setBusinessName] = useState('');
  const [logoContentId, setLogoContentId] = useState<string | null>(null);
  const [menuName, setMenuName] = useState('');
  const [menuDescription, setMenuDescription] = useState('');
  const [selectedTemplateSlug, setSelectedTemplateSlug] = useState<string | null>(null);
  const [localWizardDone, setLocalWizardDone] = useState(isWizardCompleted);

  return {
    step, setStep, businessName, setBusinessName, logoContentId, setLogoContentId,
    menuName, setMenuName, menuDescription, setMenuDescription,
    selectedTemplateSlug, setSelectedTemplateSlug, localWizardDone, setLocalWizardDone,
  };
}

function buildWizardResult(
  form: ReturnType<typeof useWizardFormState>,
  isSubmitting: boolean,
  isWizardVisible: boolean,
  callbacks: { handleContinue: () => void; handleSkip: () => void; handleComplete: () => void },
): WelcomeWizardState {
  return {
    step: form.step, businessName: form.businessName, logoContentId: form.logoContentId,
    menuName: form.menuName, menuDescription: form.menuDescription,
    selectedTemplateSlug: form.selectedTemplateSlug, isSubmitting, isWizardVisible,
    setBusinessName: form.setBusinessName, setLogoContentId: form.setLogoContentId,
    setMenuName: form.setMenuName, setMenuDescription: form.setMenuDescription,
    setSelectedTemplateSlug: form.setSelectedTemplateSlug, ...callbacks,
  };
}

/**
 * When the tenant already has a name set on the server (because the user
 * captured it during `/register`), skip the Business Name step. Only advance
 * once: re-running on every render would trap the user — they could never go
 * back to step 1 if they wanted to rename their tenant. We track a one-shot
 * `hasAutoSkippedRef` flag in a useState init guard.
 */
function useAutoSkipBusinessName(
  tenantName: string | null,
  step: WizardStep,
  setStep: (s: WizardStep) => void,
): void {
  const [hasAutoSkipped, setHasAutoSkipped] = useState(false);
  useEffect(() => {
    if (hasAutoSkipped) return;
    if (step !== WizardStep.BusinessName) return;
    if (!isValueDefined(tenantName) || tenantName.trim() === '') return;
    setHasAutoSkipped(true);
    setStep(WizardStep.Logo);
  }, [hasAutoSkipped, tenantName, step, setStep]);
}

interface WizardCallbacks {
  handleContinue: () => void;
  handleSkip: () => void;
  handleComplete: () => void;
}

interface UseCallbacksArgs {
  form: ReturnType<typeof useWizardFormState>;
  preferences: PreferencesInput;
  tenantId: string | undefined;
  updateTenant: ReturnType<typeof useIdentityServiceAPITenantsUpdateTenant>;
  createMenu: ReturnType<typeof useOnlineMenuWebTenantMenusCreate>;
}

function useWizardCallbacks(args: UseCallbacksArgs): WizardCallbacks {
  const { form, preferences, tenantId, updateTenant, createMenu } = args;
  const advance = useCallback((s: WizardStep): void => advanceStep(s, form.setStep), [form.setStep]);

  const handleContinue = useCallback(
    () => executeContinue({ step: form.step, businessName: form.businessName, logoContentId: form.logoContentId, menuName: form.menuName, menuDescription: form.menuDescription, selectedTemplateSlug: form.selectedTemplateSlug, tenantId, updateTenant, createMenu, advance, setStep: form.setStep }),
    [form, tenantId, updateTenant, createMenu, advance],
  );

  const handleSkip = useCallback(
    (): void => { if (form.step !== WizardStep.Completed) advance(form.step); },
    [form.step, advance],
  );

  const handleComplete = useCallback((): void => {
    markWizardCompleted();
    form.setLocalWizardDone(true);
    preferences.updatePreferences({ ...preferences.data, wizardCompleted: true });
  }, [preferences, form]);

  return { handleContinue, handleSkip, handleComplete };
}

export function useWelcomeWizard(
  dashboardData: DashboardData,
  preferences: PreferencesInput,
): WelcomeWizardState {
  const { userInfo } = useAuth();
  const { tenantName } = useCurrentTenant();
  const form = useWizardFormState();
  const updateTenant = useIdentityServiceAPITenantsUpdateTenant();
  const createMenu = useOnlineMenuWebTenantMenusCreate();
  const serverWizardDone = preferences.data?.wizardCompleted ?? false;

  useAutoSkipBusinessName(tenantName, form.step, form.setStep);

  const isWizardVisible = useMemo(
    () => dashboardData.isEmpty && !form.localWizardDone && !serverWizardDone && !preferences.isLoading,
    [dashboardData.isEmpty, form.localWizardDone, serverWizardDone, preferences.isLoading],
  );

  const tenantId = userInfo?.tenantId;
  const cbArgs = useMemo(() => ({ form, preferences, tenantId, updateTenant, createMenu }),
    [form, preferences, tenantId, updateTenant, createMenu]);
  const callbacks = useWizardCallbacks(cbArgs);

  return buildWizardResult(form, updateTenant.isPending || createMenu.isPending, isWizardVisible, callbacks);
}
