/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * IdentityService API
 * Authentication, User Management, Tenant Management, and API Key Management
 * OpenAPI spec version: v1
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import type {
  IdentityServiceAPILogIngestionLogBatchRequest,
  IdentityServiceAPILogIngestionLogBatchResponse,
} from '.././models';

import { identityInstance } from '../../../mutators/identityMutator';

export const ingestLogs = (
  identityServiceAPILogIngestionLogBatchRequest: IdentityServiceAPILogIngestionLogBatchRequest,
  signal?: AbortSignal
) => {
  return identityInstance<IdentityServiceAPILogIngestionLogBatchResponse>({
    url: `/api/v1/logs`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: identityServiceAPILogIngestionLogBatchRequest,
    signal,
  });
};

export const getIngestLogsMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof ingestLogs>>,
    TError,
    { data: IdentityServiceAPILogIngestionLogBatchRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof ingestLogs>>,
  TError,
  { data: IdentityServiceAPILogIngestionLogBatchRequest },
  TContext
> => {
  const mutationKey = ['ingestLogs'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof ingestLogs>>,
    { data: IdentityServiceAPILogIngestionLogBatchRequest }
  > = (props) => {
    const { data } = props ?? {};

    return ingestLogs(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type IngestLogsMutationResult = NonNullable<Awaited<ReturnType<typeof ingestLogs>>>;
export type IngestLogsMutationBody = IdentityServiceAPILogIngestionLogBatchRequest;
export type IngestLogsMutationError = unknown;

export const useIngestLogs = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof ingestLogs>>,
      TError,
      { data: IdentityServiceAPILogIngestionLogBatchRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof ingestLogs>>,
  TError,
  { data: IdentityServiceAPILogIngestionLogBatchRequest },
  TContext
> => {
  const mutationOptions = getIngestLogsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
