import type { IdentityServiceCoreEntitiesTenantStatus } from '../../server/autoGeneratedHooks/identity/models';

export interface TenantFormPayload {
  name: string;
  tenantStatus?: IdentityServiceCoreEntitiesTenantStatus;
  primaryAuthMethod?: number;
  allowPhoneAuth?: boolean;
  allowEmailAuth?: boolean;
  otpCodeLength?: number;
  otpExpiryMinutes?: number;
  smsProvider?: string | null;
  requireSmsVerification?: boolean;
}

export function buildTenantData(payload: TenantFormPayload): TenantFormPayload {
  return {
    name: payload.name,
    tenantStatus: payload.tenantStatus,
    primaryAuthMethod: payload.primaryAuthMethod,
    allowPhoneAuth: payload.allowPhoneAuth,
    allowEmailAuth: payload.allowEmailAuth,
    otpCodeLength: payload.otpCodeLength,
    otpExpiryMinutes: payload.otpExpiryMinutes,
    smsProvider: payload.smsProvider,
    requireSmsVerification: payload.requireSmsVerification,
  };
}
