import React, { useEffect, useMemo } from 'react';

import { ActivityIndicator, FlatList, Text, View } from 'react-native';

import { useRouter } from 'expo-router';

import { useSelector } from 'react-redux';

import { MenuCard, publicMenuListStyles } from '../../../src/components/PublicMenu';
import { notify } from '../../../src/lib/notifications';
import { FM } from '../../../src/localization/helpers';
import { useOnlineMenuWebMenuList } from '../../../src/server/autoGeneratedHooks/onlinemenu/tenantmenus/tenantmenus';
import ThemeMode from '../../../src/shared/enums/ThemeMode';
import { TestIds } from '../../../src/shared/testIds';
import { themePalette } from '../../../src/theme/utils/styles';
import { isActiveMenu } from '../../../src/types/menuTypes';
import { getErrorMessage } from '../../../src/utils/errorMessage';
import { logger } from '../../../src/utils/logger';

import type { RootState } from '../../../src/store/reduxStore';
import type { TenantMenusDto } from '../../../src/types/menuTypes';

const PublicMenuListPage = (): React.ReactElement => {
  const theme = useSelector((s: RootState) => s.ui.theme);
  const colors = theme === ThemeMode.Dark ? themePalette.dark : themePalette.light;
  const router = useRouter();

  // Public pages must always show the latest data. staleTime: 0 ensures React
  // Query refetches on every mount rather than serving a cached snapshot that
  // might not yet reflect a recent activation / deactivation.
  const STALE_TIME_ZERO = 0;
  const listQuery = useOnlineMenuWebMenuList({ query: { staleTime: STALE_TIME_ZERO } });

  // Filter to active menus only
  const activeMenus = useMemo((): TenantMenusDto[] => {
    const source = listQuery.data?.menus ?? [];
    return source
      .filter((menu): menu is TenantMenusDto => isActiveMenu(menu) && menu.isActive === true)
      .sort((a, b) => {
        const aTime = typeof a.createdDate === 'string' ? new Date(a.createdDate).getTime() : 0;
        const bTime = typeof b.createdDate === 'string' ? new Date(b.createdDate).getTime() : 0;
        return bTime - aTime;
      });
  }, [listQuery.data]);

  const handleViewMenu = (menuId: string): void => {
    router.push(`/public/menu/${menuId}`);
  };

  const backgroundColor = String(colors.background);
  const primaryColor = String(colors.primary);
  const textColor = String(colors.text);
  const textSecondary = String(colors.textSecondary);
  const textOnPrimary = String(colors.textOnPrimary);
  const surfaceColor = String(colors.surface);
  const errorColor = String(colors.error);
  const DEFAULT_BORDER_COLOR = '#ccc';
  const borderColor = String(colors.border) !== '' ? String(colors.border) : DEFAULT_BORDER_COLOR;

  useEffect(() => {
    if (listQuery.isError) {
      const errorValue: unknown = listQuery.error;
      const errorMsg = getErrorMessage(errorValue, 'Error loading menus');
      logger.error('PublicMenuListPage', 'Error loading menus:', errorValue);
      notify('error', errorMsg);
    }
  }, [listQuery.isError, listQuery.error]);

  if (listQuery.isLoading)
    return (
      <View style={[publicMenuListStyles.container, { backgroundColor }]} testID={TestIds.PUBLIC_MENU_LIST}>
        <View style={publicMenuListStyles.innerWrapper}>
          <View style={publicMenuListStyles.centerContent}>
            <ActivityIndicator color={primaryColor} size="large" testID={TestIds.LOADING_INDICATOR} />
          </View>
        </View>
      </View>
    );

  if (listQuery.isError)
    return (
      <View style={[publicMenuListStyles.container, { backgroundColor }]} testID={TestIds.PUBLIC_MENU_LIST}>
        <View style={publicMenuListStyles.innerWrapper}>
          <View style={publicMenuListStyles.emptyContainer}>
            <Text style={[publicMenuListStyles.emptyText, { color: errorColor }]}>
              {FM('onlineMenus.errors.loadFailed')}
            </Text>
          </View>
        </View>
      </View>
    );

  return (
    <View style={[publicMenuListStyles.container, { backgroundColor }]} testID={TestIds.PUBLIC_MENU_LIST}>
      <View style={publicMenuListStyles.innerWrapper}>
        <View style={[publicMenuListStyles.header, { borderBottomColor: borderColor }]}>
          <Text style={[publicMenuListStyles.title, { color: textColor }]}>
            {FM('onlineMenus.title')}
          </Text>
          <Text style={[publicMenuListStyles.subtitle, { color: textSecondary }]}>
            {FM('onlineMenus.publicView')}
          </Text>
        </View>

        {activeMenus.length === 0 ? (
          <View style={publicMenuListStyles.emptyContainer}>
            <Text style={[publicMenuListStyles.emptyText, { color: textSecondary }]}>
              {FM('onlineMenus.messages.noActiveMenus')}
            </Text>
          </View>
        ) : (
          <FlatList
            contentContainerStyle={publicMenuListStyles.listContent}
            data={activeMenus}
            keyExtractor={(item) => String(item.externalId)}
            renderItem={({ item }) => (
              <MenuCard
                backgroundColor={surfaceColor}
                defaultMenuTitle={FM('onlineMenus.title')}
                menu={item}
                primaryColor={primaryColor}
                textColor={textColor}
                textOnPrimary={textOnPrimary}
                textSecondary={textSecondary}
                viewButtonLabel={FM('onlineMenus.publicView')}
                onViewMenu={handleViewMenu}
              />
            )}
          />
        )}
      </View>
    </View>
  );
};

export default PublicMenuListPage;
