import { renderHook, act } from '@testing-library/react-native';

import type { useOnlineMenuWebMenuUpdate } from '@/server/autoGeneratedHooks/onlinemenu/tenantmenus/tenantmenus';
import type { MenuContents } from '@/types/menuTypes';

import { AUTO_SAVE_DEBOUNCE_MS, ERROR_CLEAR_DELAY_MS, useAutoSave } from './useAutoSave';

type MutationType = ReturnType<typeof useOnlineMenuWebMenuUpdate>;

function createMockMutation(): MutationType {
  const mutate = jest.fn();
  return { mutate, isLoading: false, isError: false, isSuccess: false } as unknown as MutationType;
}

interface AutoSaveParams {
  externalId: string | undefined;
  name: string;
  description: string;
  menuContents: MenuContents;
  updateMutation: MutationType;
}

function defaultParams(overrides: Partial<AutoSaveParams> = {}): AutoSaveParams {
  return {
    externalId: 'menu-123',
    name: 'Test Menu',
    description: 'A description',
    menuContents: { categories: [] },
    updateMutation: createMockMutation(),
    ...overrides,
  };
}

const TIMER_BUFFER = 100;

/**
 * The hook skips the first data change after mount (changeCount goes 0→1, guard is <= 1).
 * This warm-up rerender simulates that first ignored change so subsequent rerenders trigger auto-save.
 */
function warmUp(rerender: (props: AutoSaveParams) => void, initial: AutoSaveParams): void {
  act(() => { rerender({ ...initial, description: 'warmup' }); });
}

describe('useAutoSave', () => {
  beforeEach(() => { jest.useFakeTimers(); });
  afterEach(() => {
    jest.runOnlyPendingTimers();
    jest.useRealTimers();
  });

  it('starts with idle status and null lastSavedAt', () => {
    const { result } = renderHook(() => useAutoSave(defaultParams()));
    expect(result.current.saveStatus).toBe('idle');
    expect(result.current.lastSavedAt).toBeNull();
  });

  it('does not trigger save when externalId is undefined (create mode)', () => {
    const mutation = createMockMutation();
    const { rerender } = renderHook(
      (props: AutoSaveParams) => useAutoSave(props),
      { initialProps: defaultParams({ externalId: undefined, updateMutation: mutation }) },
    );
    act(() => {
      rerender(defaultParams({ externalId: undefined, name: 'Changed', updateMutation: mutation }));
      jest.advanceTimersByTime(AUTO_SAVE_DEBOUNCE_MS + TIMER_BUFFER);
    });
    expect(mutation.mutate).not.toHaveBeenCalled();
  });

  it('triggers save after debounce delay when data changes', () => {
    const mutation = createMockMutation();
    const initial = defaultParams({ updateMutation: mutation });
    const { rerender } = renderHook((props: AutoSaveParams) => useAutoSave(props), { initialProps: initial });

    warmUp(rerender, initial);
    act(() => { rerender({ ...initial, name: 'Updated Name' }); });
    act(() => { jest.advanceTimersByTime(AUTO_SAVE_DEBOUNCE_MS + TIMER_BUFFER); });
    expect(mutation.mutate).toHaveBeenCalledTimes(1);
  });

  it('sets status to saving while mutation is in flight', () => {
    const mutation = createMockMutation();
    const initial = defaultParams({ updateMutation: mutation });
    const { result, rerender } = renderHook((props: AutoSaveParams) => useAutoSave(props), { initialProps: initial });

    warmUp(rerender, initial);
    act(() => { rerender({ ...initial, name: 'New' }); });
    act(() => { jest.advanceTimersByTime(AUTO_SAVE_DEBOUNCE_MS + TIMER_BUFFER); });
    expect(result.current.saveStatus).toBe('saving');
  });

  it('sets status to saved on success', () => {
    const mutation = createMockMutation();
    (mutation.mutate as jest.Mock).mockImplementation((_data: unknown, opts?: { onSuccess?: () => void }) => { opts?.onSuccess?.(); });

    const initial = defaultParams({ updateMutation: mutation });
    const { result, rerender } = renderHook((props: AutoSaveParams) => useAutoSave(props), { initialProps: initial });

    warmUp(rerender, initial);
    act(() => { rerender({ ...initial, name: 'New' }); });
    act(() => { jest.advanceTimersByTime(AUTO_SAVE_DEBOUNCE_MS + TIMER_BUFFER); });
    expect(result.current.saveStatus).toBe('saved');
    expect(result.current.lastSavedAt).toBeInstanceOf(Date);
  });

  it('sets status to error on failure and clears after delay', () => {
    const mutation = createMockMutation();
    (mutation.mutate as jest.Mock).mockImplementation((_data: unknown, opts?: { onError?: (err: Error) => void }) => { opts?.onError?.(new Error('fail')); });

    const initial = defaultParams({ updateMutation: mutation });
    const { result, rerender } = renderHook((props: AutoSaveParams) => useAutoSave(props), { initialProps: initial });

    warmUp(rerender, initial);
    act(() => { rerender({ ...initial, name: 'Fail' }); });
    act(() => { jest.advanceTimersByTime(AUTO_SAVE_DEBOUNCE_MS + TIMER_BUFFER); });
    expect(result.current.saveStatus).toBe('error');

    act(() => { jest.advanceTimersByTime(ERROR_CLEAR_DELAY_MS + TIMER_BUFFER); });
    expect(result.current.saveStatus).toBe('idle');
  });

  it('does not save when change count has not increased past saved count', () => {
    const mutation = createMockMutation();
    (mutation.mutate as jest.Mock).mockImplementation((_data: unknown, opts?: { onSuccess?: () => void }) => { opts?.onSuccess?.(); });

    const initial = defaultParams({ updateMutation: mutation });
    const { rerender } = renderHook((props: AutoSaveParams) => useAutoSave(props), { initialProps: initial });

    warmUp(rerender, initial);
    act(() => { rerender({ ...initial, name: 'v2' }); });
    act(() => { jest.advanceTimersByTime(AUTO_SAVE_DEBOUNCE_MS + TIMER_BUFFER); });
    expect(mutation.mutate).toHaveBeenCalledTimes(1);

    (mutation.mutate as jest.Mock).mockClear();
    act(() => { jest.advanceTimersByTime(AUTO_SAVE_DEBOUNCE_MS + TIMER_BUFFER); });
    expect(mutation.mutate).not.toHaveBeenCalled();
  });

  it('resets state when externalId changes', () => {
    const mutation = createMockMutation();
    const initial = defaultParams({ updateMutation: mutation });
    const { result, rerender } = renderHook((props: AutoSaveParams) => useAutoSave(props), { initialProps: initial });

    act(() => { rerender({ ...initial, externalId: 'menu-456' }); });
    expect(result.current.saveStatus).toBe('idle');
    expect(result.current.lastSavedAt).toBeNull();
  });

  it('triggerSave calls mutation immediately when data has changed', () => {
    const mutation = createMockMutation();
    const initial = defaultParams({ updateMutation: mutation });
    const { result, rerender } = renderHook((props: AutoSaveParams) => useAutoSave(props), { initialProps: initial });

    act(() => { rerender({ ...initial, name: 'Trigger' }); });
    act(() => { result.current.triggerSave(); });
    expect(mutation.mutate).toHaveBeenCalledTimes(1);
  });

  it('sends correct request data to mutation', () => {
    const mutation = createMockMutation();
    const contents: MenuContents = { categories: [{ name: 'Cat', items: [] }] };
    const initial = defaultParams({ updateMutation: mutation, menuContents: contents });
    const { rerender } = renderHook((props: AutoSaveParams) => useAutoSave(props), { initialProps: initial });

    warmUp(rerender, initial);
    act(() => { rerender({ ...initial, name: 'New Name' }); });
    act(() => { jest.advanceTimersByTime(AUTO_SAVE_DEBOUNCE_MS + TIMER_BUFFER); });

    expect(mutation.mutate).toHaveBeenCalledTimes(1);
    const callArgs = (mutation.mutate as jest.Mock).mock.calls[0][0] as { data: { externalId: string; name: string } };
    expect(callArgs.data.externalId).toBe('menu-123');
    expect(callArgs.data.name).toBe('New Name');
  });
});
