/**
 * Auto-save hook for the Menu Editor.
 * Debounces changes and triggers the update mutation in edit mode only.
 */
import { useCallback, useEffect, useRef, useState } from 'react';

import type { useOnlineMenuWebMenuUpdate } from '@/server/autoGeneratedHooks/onlinemenu/tenantmenus/tenantmenus';
import SaveStatus from '@/shared/enums/SaveStatus';
import type { MenuContents } from '@/types/menuTypes';
import { useDebouncedCallback } from '@/utils/debounce';
import { isValueDefined } from '@/utils/is';

/** How long the "Saved" status displays before resetting to idle (ms). */
const SAVED_DISPLAY_MS = 3000;

/** Delay before auto-save triggers after the last change (ms).
 * Kept short so an upload that completes just before the user navigates away
 * still gets persisted — the previous 1500ms window meant the PUT often hadn't
 * been queued yet when an SPA navigation aborted in-flight requests. */
export const AUTO_SAVE_DEBOUNCE_MS = 250;

/** How long the error status persists before resetting to idle (ms). */
export const ERROR_CLEAR_DELAY_MS = 5000;

interface UseAutoSaveParams {
  externalId: string | undefined;
  name: string;
  description: string;
  menuContents: MenuContents;
  updateMutation: ReturnType<typeof useOnlineMenuWebMenuUpdate>;
}

interface UseAutoSaveReturn {
  saveStatus: SaveStatus;
  lastSavedAt: Date | null;
  triggerSave: () => void;
  /** Drop any pending debounced autoSave without firing it. Use before a manual save to avoid a redundant follow-up PUT that could overwrite with stale state. */
  cancelPendingSave: () => void;
}

function buildRequest(id: string, name: string, desc: string, contents: MenuContents): { data: { externalId: string; name: string; description?: string; contents: MenuContents } } {
  const trimmed = desc.trim();
  return { data: { externalId: id, name, description: trimmed !== '' ? trimmed : undefined, contents } };
}

export function useAutoSave(params: UseAutoSaveParams): UseAutoSaveReturn {
  const { externalId, name, description, menuContents, updateMutation } = params;
  const [saveStatus, setSaveStatus] = useState<SaveStatus>(SaveStatus.Idle);
  const [lastSavedAt, setLastSavedAt] = useState<Date | null>(null);
  const changeCountRef = useRef(0);
  const savedAtCountRef = useRef(0);
  const errorTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const savedTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => () => {
    if (isValueDefined(errorTimerRef.current)) clearTimeout(errorTimerRef.current);
    if (isValueDefined(savedTimerRef.current)) clearTimeout(savedTimerRef.current);
  }, []);

  const performSave = useCallback(() => {
    if (typeof externalId !== 'string') return;
    if (changeCountRef.current <= savedAtCountRef.current) return;
    const countAtSave = changeCountRef.current;
    setSaveStatus(SaveStatus.Saving);
    updateMutation.mutate(buildRequest(externalId, name, description, menuContents), {
      onSuccess: () => {
        savedAtCountRef.current = countAtSave;
        setSaveStatus(SaveStatus.Saved);
        setLastSavedAt(new Date());
        savedTimerRef.current = setTimeout(() => { setSaveStatus(SaveStatus.Idle); }, SAVED_DISPLAY_MS);
      },
      onError: () => {
        setSaveStatus(SaveStatus.Error);
        errorTimerRef.current = setTimeout(() => { setSaveStatus(SaveStatus.Idle); }, ERROR_CLEAR_DELAY_MS);
      },
    });
  }, [externalId, name, description, menuContents, updateMutation]);

  const debouncedSave = useDebouncedCallback(performSave, AUTO_SAVE_DEBOUNCE_MS);

  /* Reset counters when switching menus (externalId change). Must run before the data-change effect. */
  useEffect(() => {
    changeCountRef.current = 0;
    savedAtCountRef.current = 0;
    setSaveStatus(SaveStatus.Idle);
    setLastSavedAt(null);
  }, [externalId]);

  useEffect(() => {
    if (typeof externalId !== 'string') return;
    changeCountRef.current += 1;
    if (changeCountRef.current <= 1) return;
    debouncedSave();
  }, [name, description, menuContents, externalId, debouncedSave]);

  return { saveStatus, lastSavedAt, triggerSave: performSave, cancelPendingSave: debouncedSave.cancel };
}
