/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OnlineMenu.Web
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  CreateLocationRequest,
  CreateLocationResponse,
  LocationDto,
  UpdateLocationRequest,
  UpdateLocationResponse,
} from '.././models';

import { customInstance } from '../../../mutators/onlineMenuMutator';

/**
 * @summary Creates a new location for the current tenant.
 */
export const onlineMenuWebLocationsCreate = (
  createLocationRequest: CreateLocationRequest,
  signal?: AbortSignal
) => {
  return customInstance<CreateLocationResponse>({
    url: `/api/v1/api/v1/locations`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createLocationRequest,
    signal,
  });
};

export const getOnlineMenuWebLocationsCreateMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof onlineMenuWebLocationsCreate>>,
    TError,
    { data: CreateLocationRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof onlineMenuWebLocationsCreate>>,
  TError,
  { data: CreateLocationRequest },
  TContext
> => {
  const mutationKey = ['onlineMenuWebLocationsCreate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof onlineMenuWebLocationsCreate>>,
    { data: CreateLocationRequest }
  > = (props) => {
    const { data } = props ?? {};

    return onlineMenuWebLocationsCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type OnlineMenuWebLocationsCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof onlineMenuWebLocationsCreate>>
>;
export type OnlineMenuWebLocationsCreateMutationBody = CreateLocationRequest;
export type OnlineMenuWebLocationsCreateMutationError = void;

/**
 * @summary Creates a new location for the current tenant.
 */
export const useOnlineMenuWebLocationsCreate = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof onlineMenuWebLocationsCreate>>,
      TError,
      { data: CreateLocationRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof onlineMenuWebLocationsCreate>>,
  TError,
  { data: CreateLocationRequest },
  TContext
> => {
  const mutationOptions = getOnlineMenuWebLocationsCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Lists all locations for the current tenant.
 */
export const onlineMenuWebLocationsList = (signal?: AbortSignal) => {
  return customInstance<LocationDto[]>({ url: `/api/v1/api/v1/locations`, method: 'GET', signal });
};

export const getOnlineMenuWebLocationsListQueryKey = () => {
  return [`/api/v1/api/v1/locations`] as const;
};

export const getOnlineMenuWebLocationsListQueryOptions = <
  TData = Awaited<ReturnType<typeof onlineMenuWebLocationsList>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof onlineMenuWebLocationsList>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getOnlineMenuWebLocationsListQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof onlineMenuWebLocationsList>>> = ({
    signal,
  }) => onlineMenuWebLocationsList(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof onlineMenuWebLocationsList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type OnlineMenuWebLocationsListQueryResult = NonNullable<
  Awaited<ReturnType<typeof onlineMenuWebLocationsList>>
>;
export type OnlineMenuWebLocationsListQueryError = void;

export function useOnlineMenuWebLocationsList<
  TData = Awaited<ReturnType<typeof onlineMenuWebLocationsList>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof onlineMenuWebLocationsList>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof onlineMenuWebLocationsList>>,
          TError,
          Awaited<ReturnType<typeof onlineMenuWebLocationsList>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useOnlineMenuWebLocationsList<
  TData = Awaited<ReturnType<typeof onlineMenuWebLocationsList>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof onlineMenuWebLocationsList>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof onlineMenuWebLocationsList>>,
          TError,
          Awaited<ReturnType<typeof onlineMenuWebLocationsList>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useOnlineMenuWebLocationsList<
  TData = Awaited<ReturnType<typeof onlineMenuWebLocationsList>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof onlineMenuWebLocationsList>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lists all locations for the current tenant.
 */

export function useOnlineMenuWebLocationsList<
  TData = Awaited<ReturnType<typeof onlineMenuWebLocationsList>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof onlineMenuWebLocationsList>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getOnlineMenuWebLocationsListQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Deletes a location.
 */
export const onlineMenuWebLocationsDelete = (externalId: string) => {
  return customInstance<void>({ url: `/api/v1/api/v1/locations/${externalId}`, method: 'DELETE' });
};

export const getOnlineMenuWebLocationsDeleteMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof onlineMenuWebLocationsDelete>>,
    TError,
    { externalId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof onlineMenuWebLocationsDelete>>,
  TError,
  { externalId: string },
  TContext
> => {
  const mutationKey = ['onlineMenuWebLocationsDelete'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof onlineMenuWebLocationsDelete>>,
    { externalId: string }
  > = (props) => {
    const { externalId } = props ?? {};

    return onlineMenuWebLocationsDelete(externalId);
  };

  return { mutationFn, ...mutationOptions };
};

export type OnlineMenuWebLocationsDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof onlineMenuWebLocationsDelete>>
>;

export type OnlineMenuWebLocationsDeleteMutationError = void;

/**
 * @summary Deletes a location.
 */
export const useOnlineMenuWebLocationsDelete = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof onlineMenuWebLocationsDelete>>,
      TError,
      { externalId: string },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof onlineMenuWebLocationsDelete>>,
  TError,
  { externalId: string },
  TContext
> => {
  const mutationOptions = getOnlineMenuWebLocationsDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Gets a single location by its ExternalId.
 */
export const onlineMenuWebLocationsGetById = (externalId: string, signal?: AbortSignal) => {
  return customInstance<LocationDto>({
    url: `/api/v1/api/v1/locations/${externalId}`,
    method: 'GET',
    signal,
  });
};

export const getOnlineMenuWebLocationsGetByIdQueryKey = (externalId?: string) => {
  return [`/api/v1/api/v1/locations/${externalId}`] as const;
};

export const getOnlineMenuWebLocationsGetByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof onlineMenuWebLocationsGetById>>,
  TError = void,
>(
  externalId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof onlineMenuWebLocationsGetById>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getOnlineMenuWebLocationsGetByIdQueryKey(externalId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof onlineMenuWebLocationsGetById>>> = ({
    signal,
  }) => onlineMenuWebLocationsGetById(externalId, signal);

  return { queryKey, queryFn, enabled: !!externalId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof onlineMenuWebLocationsGetById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type OnlineMenuWebLocationsGetByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof onlineMenuWebLocationsGetById>>
>;
export type OnlineMenuWebLocationsGetByIdQueryError = void;

export function useOnlineMenuWebLocationsGetById<
  TData = Awaited<ReturnType<typeof onlineMenuWebLocationsGetById>>,
  TError = void,
>(
  externalId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof onlineMenuWebLocationsGetById>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof onlineMenuWebLocationsGetById>>,
          TError,
          Awaited<ReturnType<typeof onlineMenuWebLocationsGetById>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useOnlineMenuWebLocationsGetById<
  TData = Awaited<ReturnType<typeof onlineMenuWebLocationsGetById>>,
  TError = void,
>(
  externalId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof onlineMenuWebLocationsGetById>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof onlineMenuWebLocationsGetById>>,
          TError,
          Awaited<ReturnType<typeof onlineMenuWebLocationsGetById>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useOnlineMenuWebLocationsGetById<
  TData = Awaited<ReturnType<typeof onlineMenuWebLocationsGetById>>,
  TError = void,
>(
  externalId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof onlineMenuWebLocationsGetById>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Gets a single location by its ExternalId.
 */

export function useOnlineMenuWebLocationsGetById<
  TData = Awaited<ReturnType<typeof onlineMenuWebLocationsGetById>>,
  TError = void,
>(
  externalId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof onlineMenuWebLocationsGetById>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getOnlineMenuWebLocationsGetByIdQueryOptions(externalId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Updates an existing location.
 */
export const onlineMenuWebLocationsUpdate = (
  externalId: string,
  updateLocationRequest: UpdateLocationRequest
) => {
  return customInstance<UpdateLocationResponse>({
    url: `/api/v1/api/v1/locations/${externalId}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: updateLocationRequest,
  });
};

export const getOnlineMenuWebLocationsUpdateMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof onlineMenuWebLocationsUpdate>>,
    TError,
    { externalId: string; data: UpdateLocationRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof onlineMenuWebLocationsUpdate>>,
  TError,
  { externalId: string; data: UpdateLocationRequest },
  TContext
> => {
  const mutationKey = ['onlineMenuWebLocationsUpdate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof onlineMenuWebLocationsUpdate>>,
    { externalId: string; data: UpdateLocationRequest }
  > = (props) => {
    const { externalId, data } = props ?? {};

    return onlineMenuWebLocationsUpdate(externalId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type OnlineMenuWebLocationsUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof onlineMenuWebLocationsUpdate>>
>;
export type OnlineMenuWebLocationsUpdateMutationBody = UpdateLocationRequest;
export type OnlineMenuWebLocationsUpdateMutationError = void;

/**
 * @summary Updates an existing location.
 */
export const useOnlineMenuWebLocationsUpdate = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof onlineMenuWebLocationsUpdate>>,
      TError,
      { externalId: string; data: UpdateLocationRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof onlineMenuWebLocationsUpdate>>,
  TError,
  { externalId: string; data: UpdateLocationRequest },
  TContext
> => {
  const mutationOptions = getOnlineMenuWebLocationsUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
