import { useCallback, useMemo } from 'react';

import { useIdentityServiceAPIUsersListUsers } from '../autoGeneratedHooks/identity/users/users';
import { useQuestionerWebCompletedQuestionersList } from '../autoGeneratedHooks/questioner/completedquestioners/completedquestioners';

import type { IdentityAbstractionsModelsUserListItem } from '../autoGeneratedHooks/identity/models';
import type { CompletedQuestionerDto } from '../autoGeneratedHooks/questioner/models';

export interface CompletedQuestionerWithUser extends CompletedQuestionerDto {
  user?: IdentityAbstractionsModelsUserListItem | null;
}

/** Build a map of users by ID for efficient lookup */
function buildUserMap(users: IdentityAbstractionsModelsUserListItem[]): Map<string, IdentityAbstractionsModelsUserListItem> {
  const map = new Map<string, IdentityAbstractionsModelsUserListItem>();
  for (const u of users) 
    if (typeof u.id === 'string' && u.id.length > 0) map.set(u.id, u);
  
  return map;
}

/** Merge questioners with user data */
function mergeWithUsers(
  items: CompletedQuestionerDto[],
  userMap: Map<string, IdentityAbstractionsModelsUserListItem>,
): CompletedQuestionerWithUser[] {
  return items.map((it) => {
    const user = typeof it.userId === 'string' && it.userId.length > 0 ? userMap.get(it.userId) : undefined;
    const merged: CompletedQuestionerWithUser = { ...it, user };
    return merged;
  });
}

export function useCompletedQuestionersWithUsers(): {
  data: CompletedQuestionerWithUser[];
  isLoading: boolean;
  isError: boolean;
  refetch: () => void;
  listQuery: ReturnType<typeof useQuestionerWebCompletedQuestionersList>;
  usersQuery: ReturnType<typeof useIdentityServiceAPIUsersListUsers>;
} {
  const listQuery = useQuestionerWebCompletedQuestionersList();
  const usersQuery = useIdentityServiceAPIUsersListUsers();

  const combined = useMemo(() => {
    const items = listQuery.data?.completedQuestioners ?? [];
    const users = usersQuery.data?.users ?? [];
    return mergeWithUsers(items, buildUserMap(users));
  }, [listQuery.data, usersQuery.data]);

  const refetch = useCallback(() => {
    listQuery.refetch().catch(() => {});
    usersQuery.refetch().catch(() => {});
  }, [listQuery, usersQuery]);

  return {
    data: combined,
    isLoading: listQuery.isLoading || usersQuery.isLoading,
    isError: listQuery.isError || usersQuery.isError,
    refetch,
    listQuery,
    usersQuery,
  };
}

export default useCompletedQuestionersWithUsers;
