/**
 * Unit tests for useCancelSubscription hook.
 * Tests mutation callbacks, cache invalidation, and error handling.
 */
import { useQueryClient } from '@tanstack/react-query';
import { renderHook, waitFor } from '@testing-library/react-native';

import { useCancelSubscription } from './useCancelSubscription';

jest.mock('../../../../server/autoGeneratedHooks/payment/subscriptions/subscriptions', () => ({
  usePaymentServiceAPISubscriptionsCancelSubscription: jest.fn(),
  getPaymentServiceAPISubscriptionsGetCurrentSubscriptionQueryKey: jest.fn(() => ['/api/subscriptions/current']),
}));

jest.mock('@tanstack/react-query', () => ({
  ...jest.requireActual('@tanstack/react-query'),
  useQueryClient: jest.fn(),
}));

const { usePaymentServiceAPISubscriptionsCancelSubscription } = jest.requireMock(
  '../../../../server/autoGeneratedHooks/payment/subscriptions/subscriptions',
);

const mockUseQueryClient = useQueryClient as jest.Mock;
const mockOrvalHook = usePaymentServiceAPISubscriptionsCancelSubscription as jest.Mock;

interface HookOptions {
  mutation: {
    onSuccess?: () => void;
    onError?: (error: unknown) => void;
  };
}

describe('useCancelSubscription', () => {
  const mockInvalidateQueries = jest.fn().mockResolvedValue(undefined);
  const mockMutate = jest.fn();

  beforeEach(() => {
    jest.clearAllMocks();
    mockUseQueryClient.mockReturnValue({ invalidateQueries: mockInvalidateQueries });
  });

  it('calls mutate when cancelSubscription is invoked', () => {
    mockOrvalHook.mockReturnValue({ mutate: mockMutate, isPending: false, isError: false, error: null });
    const { result } = renderHook(() => useCancelSubscription());
    result.current.cancelSubscription();
    expect(mockMutate).toHaveBeenCalled();
  });

  it('returns isPending from mutation state', () => {
    mockOrvalHook.mockReturnValue({ mutate: mockMutate, isPending: true, isError: false, error: null });
    const { result } = renderHook(() => useCancelSubscription());
    expect(result.current.isPending).toBe(true);
  });

  it('returns isError from mutation state', () => {
    mockOrvalHook.mockReturnValue({ mutate: mockMutate, isPending: false, isError: true, error: new Error('fail') });
    const { result } = renderHook(() => useCancelSubscription());
    expect(result.current.isError).toBe(true);
  });

  it('returns Error object when mutation has error', () => {
    const testError = new Error('Network error');
    mockOrvalHook.mockReturnValue({ mutate: mockMutate, isPending: false, isError: true, error: testError });
    const { result } = renderHook(() => useCancelSubscription());
    expect(result.current.error).toBe(testError);
  });

  it('returns null error for non-Error objects', () => {
    mockOrvalHook.mockReturnValue({ mutate: mockMutate, isPending: false, isError: true, error: 'string error' });
    const { result } = renderHook(() => useCancelSubscription());
    expect(result.current.error).toBeNull();
  });

  it('calls onSuccess and invalidates queries on success', async () => {
    let successCallback: (() => void) | undefined;
    mockOrvalHook.mockImplementation((options: HookOptions) => {
      successCallback = options.mutation.onSuccess;
      return { mutate: mockMutate, isPending: false, isError: false, error: null };
    });
    const onSuccess = jest.fn();
    renderHook(() => useCancelSubscription({ onSuccess }));
    if (successCallback) successCallback();
    await waitFor(() => {
      expect(mockInvalidateQueries).toHaveBeenCalled();
      expect(onSuccess).toHaveBeenCalled();
    });
  });

  it('calls onError with Error when mutation fails', async () => {
    const testError = new Error('Cancel failed');
    let errorCallback: ((error: unknown) => void) | undefined;
    mockOrvalHook.mockImplementation((options: HookOptions) => {
      errorCallback = options.mutation.onError;
      return { mutate: mockMutate, isPending: false, isError: false, error: null };
    });
    const onError = jest.fn();
    renderHook(() => useCancelSubscription({ onError }));
    if (errorCallback) errorCallback(testError);
    await waitFor(() => expect(onError).toHaveBeenCalledWith(testError));
  });

  it('wraps non-Error objects in Error on failure', async () => {
    let errorCallback: ((error: unknown) => void) | undefined;
    mockOrvalHook.mockImplementation((options: HookOptions) => {
      errorCallback = options.mutation.onError;
      return { mutate: mockMutate, isPending: false, isError: false, error: null };
    });
    const onError = jest.fn();
    renderHook(() => useCancelSubscription({ onError }));
    if (errorCallback) errorCallback('string error');
    await waitFor(() => {
      expect(onError).toHaveBeenCalledWith(expect.any(Error));
    });
  });
});
