/**
 * Unit tests for useCreateSubscription hook.
 * Tests mutation callbacks, cache invalidation, and request mapping.
 */
import { useQueryClient } from '@tanstack/react-query';
import { renderHook, waitFor } from '@testing-library/react-native';

import { useCreateSubscription } from './useCreateSubscription';
import BillingCycle from '../enums/BillingCycle';

jest.mock('../../../../server/autoGeneratedHooks/payment/subscriptions/subscriptions', () => ({
  usePaymentServiceAPISubscriptionsCreateSubscription: jest.fn(),
  getPaymentServiceAPISubscriptionsGetCurrentSubscriptionQueryKey: jest.fn(() => ['/api/subscriptions/current']),
}));

jest.mock('@tanstack/react-query', () => ({
  ...jest.requireActual('@tanstack/react-query'),
  useQueryClient: jest.fn(),
}));

const { usePaymentServiceAPISubscriptionsCreateSubscription } = jest.requireMock(
  '../../../../server/autoGeneratedHooks/payment/subscriptions/subscriptions',
);

const mockUseQueryClient = useQueryClient as jest.Mock;
const mockOrvalHook = usePaymentServiceAPISubscriptionsCreateSubscription as jest.Mock;

interface HookOptions {
  mutation: {
    onSuccess?: () => void;
    onError?: (error: unknown) => void;
  };
}

describe('useCreateSubscription', () => {
  const mockInvalidateQueries = jest.fn().mockResolvedValue(undefined);
  const mockMutate = jest.fn();

  beforeEach(() => {
    jest.clearAllMocks();
    mockUseQueryClient.mockReturnValue({ invalidateQueries: mockInvalidateQueries });
  });

  it('calls mutate with mapped subscription request', () => {
    mockOrvalHook.mockReturnValue({ mutate: mockMutate, isPending: false, isError: false, error: null });
    const { result } = renderHook(() => useCreateSubscription());
    const request = { planId: 'plan-123', billingCycle: BillingCycle.Monthly };
    result.current.createSubscription(request);
    expect(mockMutate).toHaveBeenCalledWith({
      data: { planExternalId: 'plan-123', billingCycle: BillingCycle.Monthly },
    });
  });

  it('returns isPending from mutation state', () => {
    mockOrvalHook.mockReturnValue({ mutate: mockMutate, isPending: true, isError: false, error: null });
    const { result } = renderHook(() => useCreateSubscription());
    expect(result.current.isPending).toBe(true);
  });

  it('invalidates subscription query on success', async () => {
    let successCallback: (() => void) | undefined;
    mockOrvalHook.mockImplementation((options: HookOptions) => {
      successCallback = options.mutation.onSuccess;
      return { mutate: mockMutate, isPending: false, isError: false, error: null };
    });
    const onSuccess = jest.fn();
    renderHook(() => useCreateSubscription({ onSuccess }));
    if (successCallback) successCallback();
    await waitFor(() => {
      expect(mockInvalidateQueries).toHaveBeenCalled();
      expect(onSuccess).toHaveBeenCalledWith({ planName: '' });
    });
  });

  it('calls onError callback when mutation fails', async () => {
    const testError = new Error('Subscribe failed');
    let errorCallback: ((error: unknown) => void) | undefined;
    mockOrvalHook.mockImplementation((options: HookOptions) => {
      errorCallback = options.mutation.onError;
      return { mutate: mockMutate, isPending: false, isError: false, error: null };
    });
    const onError = jest.fn();
    renderHook(() => useCreateSubscription({ onError }));
    if (errorCallback) errorCallback(testError);
    await waitFor(() => expect(onError).toHaveBeenCalledWith(testError));
  });

  it('returns null error when mutation error is not an Error', () => {
    mockOrvalHook.mockReturnValue({ mutate: mockMutate, isPending: false, isError: false, error: 42 });
    const { result } = renderHook(() => useCreateSubscription());
    expect(result.current.error).toBeNull();
  });
});
