/**
 * Hook to create a Stripe billing portal session.
 * Wraps the Orval-generated mutation.
 */
import { useCallback, useMemo } from 'react';

import { usePaymentServiceAPIBillingCreatePortalSession } from '../../../../server/autoGeneratedHooks/payment/billing/billing';

import type { PaymentServiceAPIBillingCreatePortalSessionResponse } from '../../../../server/autoGeneratedHooks/payment/models';
import type { PortalSessionResponse } from '../types';

interface MutationCallbacks {
  onSuccess?: (data: PortalSessionResponse) => void;
  onError?: (error: Error) => void;
}

interface UseCreatePortalSessionResult {
  createPortalSession: (returnUrl: string) => void;
  isPending: boolean;
  isError: boolean;
  error: Error | null;
}

function toError(error: unknown): Error {
  return error instanceof Error ? error : new Error('Portal session creation failed');
}

export function useCreatePortalSession(callbacks?: MutationCallbacks): UseCreatePortalSessionResult {
  const hookOptions = useMemo(() => ({
    mutation: {
      onSuccess: (data: PaymentServiceAPIBillingCreatePortalSessionResponse) => {
        callbacks?.onSuccess?.({ url: data.url ?? '' });
      },
      onError: (error: unknown) => callbacks?.onError?.(toError(error)),
    },
  }), [callbacks]);

  const mutation = usePaymentServiceAPIBillingCreatePortalSession(hookOptions);
  const mutationError: unknown = mutation.error;

  const createPortalSession = useCallback(
    (returnUrl: string) => mutation.mutate({ data: { returnUrl } }),
    [mutation],
  );

  return {
    createPortalSession,
    isPending: mutation.isPending,
    isError: mutation.isError,
    error: mutationError instanceof Error ? mutationError : null,
  };
}
