/**
 * Hook to create a new subscription.
 * Wraps the Orval-generated mutation and handles cache invalidation.
 */
import { useCallback, useMemo } from 'react';

import { useQueryClient } from '@tanstack/react-query';

import { SUBSCRIPTION_QUERY_KEY } from './useGetCurrentSubscription';
import { usePaymentServiceAPISubscriptionsCreateSubscription } from '../../../../server/autoGeneratedHooks/payment/subscriptions/subscriptions';

import type { CreateSubscriptionRequest } from '../types';

interface MutationCallbacks {
  onSuccess?: (data: { planName: string }) => void;
  onError?: (error: Error) => void;
}

interface UseCreateSubscriptionResult {
  createSubscription: (request: CreateSubscriptionRequest) => void;
  isPending: boolean;
  isError: boolean;
  error: Error | null;
}

function toError(error: unknown): Error {
  return error instanceof Error ? error : new Error('Subscription creation failed');
}

export function useCreateSubscription(callbacks?: MutationCallbacks): UseCreateSubscriptionResult {
  const queryClient = useQueryClient();

  const hookOptions = useMemo(() => ({
    mutation: {
      onSuccess: () => {
        queryClient.invalidateQueries({ queryKey: SUBSCRIPTION_QUERY_KEY }).catch(() => {});
        callbacks?.onSuccess?.({ planName: '' });
      },
      onError: (error: unknown) => callbacks?.onError?.(toError(error)),
    },
  }), [queryClient, callbacks]);

  const mutation = usePaymentServiceAPISubscriptionsCreateSubscription(hookOptions);
  const mutationError: unknown = mutation.error;

  const createSubscription = useCallback(
    (request: CreateSubscriptionRequest) =>
      mutation.mutate({ data: { planExternalId: request.planId, billingCycle: request.billingCycle } }),
    [mutation],
  );

  return {
    createSubscription,
    isPending: mutation.isPending,
    isError: mutation.isError,
    error: mutationError instanceof Error ? mutationError : null,
  };
}
