/**
 * Maps Orval-generated API DTOs to frontend billing types.
 *
 * Generated DTOs use API naming conventions (externalId, planTier, etc.)
 * while the frontend uses simpler names (id, tier, etc.).
 */
import BillingCycle from '../enums/BillingCycle';
import SubscriptionStatus from '../enums/SubscriptionStatus';

import type { PaymentServiceUseCasesDTOsSubscriptionDto , PaymentServiceUseCasesDTOsPricingPlanDto , PaymentServiceUseCasesDTOsBillingHistoryDto , PaymentServiceUseCasesDTOsPaymentDto , PaymentServiceUseCasesDTOsFeatureLimitDto , PaymentServiceCoreInterfacesFeatureAccessResult } from '../../../../server/autoGeneratedHooks/payment/models';
import type {
  Subscription,
  PricingPlan,
  PlanFeature,
  FeatureLimit,
  BillingHistoryItem,
  BillingHistoryResponse,
  FeatureAccessResult,
} from '../types';

const POPULAR_TIER = 'Pro';
const UNKNOWN_PLAN = 'Unknown';

/** Map a feature limit DTO to a frontend FeatureLimit. */
function mapFeatureLimit(dto: PaymentServiceUseCasesDTOsFeatureLimitDto): FeatureLimit {
  return {
    featureCode: dto.featureCode ?? '',
    limitType: dto.limitType ?? '',
    limitValue: dto.limitValue ?? null,
    isEnabled: dto.isEnabled ?? false,
  };
}

/** Map a feature limit DTO to a display-facing PlanFeature. */
function mapPlanFeature(dto: PaymentServiceUseCasesDTOsFeatureLimitDto): PlanFeature {
  return {
    code: dto.featureCode ?? '',
    name: dto.featureCode ?? '',
    limit: dto.limitValue ?? null,
  };
}

/** Parse a string subscription status to the enum value. */
function parseStatus(value: string | undefined): SubscriptionStatus {
  const statusMap: Record<string, SubscriptionStatus> = {
    Trial: SubscriptionStatus.Trial,
    Active: SubscriptionStatus.Active,
    PastDue: SubscriptionStatus.PastDue,
    Canceled: SubscriptionStatus.Canceled,
    Expired: SubscriptionStatus.Expired,
    Suspended: SubscriptionStatus.Suspended,
  };

  return statusMap[value ?? ''] ?? SubscriptionStatus.Expired;
}

/** Parse a string billing cycle to the enum value. */
function parseBillingCycle(value: string | undefined): BillingCycle {
  if (value === 'Annual') return BillingCycle.Annual;
  return BillingCycle.Monthly;
}

/** Map a subscription DTO to the frontend Subscription type. */
export function mapSubscription(dto: PaymentServiceUseCasesDTOsSubscriptionDto): Subscription {
  const features = dto.features ?? [];

  return {
    id: dto.externalId ?? '',
    planId: dto.planExternalId ?? '',
    planName: dto.planName ?? UNKNOWN_PLAN,
    planTier: dto.planTier ?? '',
    status: parseStatus(dto.status),
    billingCycle: parseBillingCycle(dto.billingCycle),
    currentPeriodStart: dto.currentPeriodStart ?? '',
    currentPeriodEnd: dto.currentPeriodEnd ?? '',
    trialEndsAt: dto.trialEndDate ?? null,
    canceledAt: dto.cancellationDate ?? null,
    showWatermark: dto.showWatermark ?? false,
    featureLimits: features.map(mapFeatureLimit),
  };
}

/** Map a pricing plan DTO to the frontend PricingPlan type. */
export function mapPricingPlan(dto: PaymentServiceUseCasesDTOsPricingPlanDto): PricingPlan {
  const features = dto.features ?? [];

  return {
    id: dto.externalId ?? '',
    name: dto.name ?? UNKNOWN_PLAN,
    description: dto.description ?? '',
    tier: dto.tier ?? '',
    monthlyPrice: dto.monthlyPriceUsd ?? 0,
    annualPrice: dto.annualPriceUsd ?? 0,
    currency: dto.currency ?? 'USD',
    features: features.map(mapPlanFeature),
    featureLimits: features.map(mapFeatureLimit),
    isPopular: dto.tier === POPULAR_TIER,
    sortOrder: dto.displayOrder ?? 0,
  };
}

/** Map a payment DTO to a BillingHistoryItem. */
function mapPayment(dto: PaymentServiceUseCasesDTOsPaymentDto): BillingHistoryItem {
  return {
    id: dto.externalId ?? '',
    date: dto.processedDate ?? '',
    description: '',
    amount: dto.amount ?? 0,
    currency: dto.currency ?? 'USD',
    status: dto.status ?? '',
    invoiceUrl: dto.invoiceUrl ?? null,
  };
}

/** Map a billing history DTO to the frontend response type. */
export function mapBillingHistory(
  dto: PaymentServiceUseCasesDTOsBillingHistoryDto,
  page: number,
  pageSize: number,
): BillingHistoryResponse {
  const payments = dto.payments ?? [];

  return {
    items: payments.map(mapPayment),
    totalCount: dto.totalCount ?? 0,
    page,
    pageSize,
  };
}

/** Map a feature access result DTO to the frontend type. */
export function mapFeatureAccess(
  dto: PaymentServiceCoreInterfacesFeatureAccessResult,
): FeatureAccessResult {
  return {
    canAccess: dto.canAccess ?? false,
    limit: dto.limit ?? null,
    isUnlimited: dto.isUnlimited ?? false,
    requiredPlan: dto.requiredPlan ?? null,
    currentPlan: dto.currentPlan ?? null,
  };
}
