import { useMemo } from 'react';

import { useIdentityServiceAPIMeGetBusinessProfile } from '../../../server/autoGeneratedHooks/identity/me/me';
import { isValueDefined } from '../../../utils/is';

/** Determines whether to show the "Complete your business profile" nudge. */
export function useBusinessProfileNudge(hasContent: boolean): boolean {
  const { data: profile, isLoading, isError } = useIdentityServiceAPIMeGetBusinessProfile({
    query: { enabled: hasContent },
  });

  return useMemo((): boolean => {
    if (!hasContent) return false;
    if (isLoading || isError) return false;
    if (!isValueDefined(profile)) return false;

    const hasPhone = isNonEmpty(profile.phone);
    const hasAddress = isNonEmpty(profile.addressLine1);

    return !hasPhone || !hasAddress;
  }, [hasContent, isLoading, isError, profile]);
}

function isNonEmpty(value: string | null | undefined): boolean {
  return isValueDefined(value) && value !== '';
}
