/**
 * Custom hook for TenantForm state management.
 */
import { useMemo, useState } from 'react';

import { FM } from '@/localization/helpers';

import {
  IdentityServiceCoreEntitiesTenantStatus as TenantStatus,
  type IdentityServiceCoreEntitiesTenantStatus,
} from '../../server/autoGeneratedHooks/identity/models/identityServiceCoreEntitiesTenantStatus';
import { OTP } from '../../shared/constants';
import { TenantStatusEnum } from '../../shared/enums/TenantStatus';
import { isValueDefined } from '../../utils/is';

export interface TenantFormPayload {
  name: string;
  tenantStatus?: IdentityServiceCoreEntitiesTenantStatus;
  primaryAuthMethod?: number;
  allowPhoneAuth?: boolean;
  allowEmailAuth?: boolean;
  otpCodeLength?: number;
  otpExpiryMinutes?: number;
  smsProvider?: string | null;
  requireSmsVerification?: boolean;
}

interface AuthConfigPayload {
  primaryAuthMethod: number;
  allowPhoneAuth: boolean;
  allowEmailAuth: boolean;
  otpCodeLength: number;
  otpExpiryMinutes: number;
  smsProvider: string | null;
  requireSmsVerification: boolean;
}

export interface TenantFormAuthState {
  primaryAuthMethod: number;
  setPrimaryAuthMethod: (v: number) => void;
  allowPhoneAuth: boolean;
  setAllowPhoneAuth: (v: boolean) => void;
  allowEmailAuth: boolean;
  setAllowEmailAuth: (v: boolean) => void;
  otpCodeLength: string;
  setOtpCodeLength: (v: string) => void;
  otpExpiryMinutes: string;
  setOtpExpiryMinutes: (v: string) => void;
  smsProvider: string;
  setSmsProvider: (v: string) => void;
  requireSmsVerification: boolean;
  setRequireSmsVerification: (v: boolean) => void;
}

interface AuthStateInitialValues {
  primaryAuthMethod: number;
  allowPhoneAuth: boolean;
  allowEmailAuth: boolean;
  otpCodeLength: number;
  otpExpiryMinutes: number;
  smsProvider: string | null;
  requireSmsVerification: boolean;
}

function useAuthState(initial: AuthStateInitialValues): TenantFormAuthState {
  const [primaryAuthMethod, setPrimaryAuthMethod] = useState<number>(initial.primaryAuthMethod);
  const [allowPhoneAuth, setAllowPhoneAuth] = useState<boolean>(initial.allowPhoneAuth);
  const [allowEmailAuth, setAllowEmailAuth] = useState<boolean>(initial.allowEmailAuth);
  const [otpCodeLength, setOtpCodeLength] = useState<string>(String(initial.otpCodeLength));
  const [otpExpiryMinutes, setOtpExpiryMinutes] = useState<string>(String(initial.otpExpiryMinutes));
  const [smsProvider, setSmsProvider] = useState<string>(initial.smsProvider ?? '');
  const [requireSmsVerification, setRequireSmsVerification] = useState<boolean>(initial.requireSmsVerification);

  return {
    primaryAuthMethod,
    setPrimaryAuthMethod,
    allowPhoneAuth,
    setAllowPhoneAuth,
    allowEmailAuth,
    setAllowEmailAuth,
    otpCodeLength,
    setOtpCodeLength,
    otpExpiryMinutes,
    setOtpExpiryMinutes,
    smsProvider,
    setSmsProvider,
    requireSmsVerification,
    setRequireSmsVerification,
  };
}

function buildAuthConfig(authState: TenantFormAuthState, otpLength: number, otpExpiry: number): AuthConfigPayload {
  const smsProviderTrimmed = authState.smsProvider.trim();
  return {
    primaryAuthMethod: authState.primaryAuthMethod,
    allowPhoneAuth: authState.allowPhoneAuth,
    allowEmailAuth: authState.allowEmailAuth,
    otpCodeLength: otpLength,
    otpExpiryMinutes: otpExpiry,
    smsProvider: smsProviderTrimmed.length > 0 ? smsProviderTrimmed : null,
    requireSmsVerification: authState.requireSmsVerification,
  };
}

function validateForm(trimmedName: string, otpLength: number, otpExpiry: number, showAuthConfig: boolean): string | null {
  if (trimmedName.length === 0) return 'Name is required';
  const isOtpLengthInvalid = isNaN(otpLength) || otpLength < OTP.MIN_LENGTH || otpLength > OTP.MAX_LENGTH;
  if (showAuthConfig && isOtpLengthInvalid) return `OTP code length must be between ${OTP.MIN_LENGTH} and ${OTP.MAX_LENGTH}`;
  const isOtpExpiryInvalid = isNaN(otpExpiry) || otpExpiry < 1;
  if (showAuthConfig && isOtpExpiryInvalid) return 'OTP expiry minutes must be at least 1';
  return null;
}

interface HandleSaveParams {
  name: string;
  status: TenantStatusEnum;
  authState: TenantFormAuthState;
  showAuthConfig: boolean;
  setError: (e: string | null) => void;
  onSave: (payload: TenantFormPayload) => void;
}

function createHandleSave(params: HandleSaveParams): () => void {
  return (): void => {
    params.setError(null);
    const trimmedName = params.name.trim();
    const otpLength = parseInt(params.authState.otpCodeLength, 10);
    const otpExpiry = parseInt(params.authState.otpExpiryMinutes, 10);
    const validationError = validateForm(trimmedName, otpLength, otpExpiry, params.showAuthConfig);
    if (isValueDefined(validationError)) {
      params.setError(validationError);
      return;
    }
    const tenantStatus = params.status === TenantStatusEnum.Disabled ? TenantStatus.Disabled : TenantStatus.Enabled;
    const authConfig = params.showAuthConfig ? buildAuthConfig(params.authState, otpLength, otpExpiry) : {};
    params.onSave({ name: trimmedName, tenantStatus, ...authConfig });
  };
}

interface UseTenantFormStateParams {
  initialName: string;
  initialStatus: number;
  initialPrimaryAuthMethod: number;
  initialAllowPhoneAuth: boolean;
  initialAllowEmailAuth: boolean;
  initialOtpCodeLength: number;
  initialOtpExpiryMinutes: number;
  initialSmsProvider: string | null;
  initialRequireSmsVerification: boolean;
  showAuthConfig: boolean;
  onSave: (payload: TenantFormPayload) => void;
}

export interface TenantFormState {
  name: string;
  setName: (name: string) => void;
  status: TenantStatusEnum;
  setStatus: (status: TenantStatusEnum) => void;
  error: string | null;
  nameError: string | undefined;
  handleSave: () => void;
  translatedStatusOptions: Array<{ value: TenantStatusEnum; label: string }>;
  authState: TenantFormAuthState;
}

export function useTenantFormState(params: UseTenantFormStateParams): TenantFormState {

  const [name, setName] = useState(params.initialName);
  const normalizedInitialStatus = params.initialStatus === 0 ? TenantStatusEnum.Disabled : TenantStatusEnum.Enabled;
  const [status, setStatus] = useState<TenantStatusEnum>(normalizedInitialStatus);
  const [error, setError] = useState<string | null>(null);

  const authStateInitial = useMemo(() => ({
    primaryAuthMethod: params.initialPrimaryAuthMethod,
    allowPhoneAuth: params.initialAllowPhoneAuth,
    allowEmailAuth: params.initialAllowEmailAuth,
    otpCodeLength: params.initialOtpCodeLength,
    otpExpiryMinutes: params.initialOtpExpiryMinutes,
    smsProvider: params.initialSmsProvider,
    requireSmsVerification: params.initialRequireSmsVerification,
  }), [params.initialPrimaryAuthMethod, params.initialAllowPhoneAuth, params.initialAllowEmailAuth, params.initialOtpCodeLength, params.initialOtpExpiryMinutes, params.initialSmsProvider, params.initialRequireSmsVerification]);
  const authState = useAuthState(authStateInitial);

  const translatedStatusOptions = useMemo(
    () => [
      { value: TenantStatusEnum.Enabled, label: FM('tenants.status.enabled') },
      { value: TenantStatusEnum.Disabled, label: FM('tenants.status.disabled') },
    ],
    [],
  );

  const handleSave = createHandleSave({ name, status, authState, showAuthConfig: params.showAuthConfig, setError, onSave: params.onSave });
  const trimmedName = name.trim();
  const nameError = isValueDefined(error) && trimmedName.length === 0 ? error : undefined;

  return { name, setName, status, setStatus, error, nameError, handleSave, translatedStatusOptions, authState };
}
