/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PaymentService API
 * Subscription Billing, Pricing Plans, and Payment Management API
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  PaymentServiceAPIBillingCreatePortalSessionRequest,
  PaymentServiceAPIBillingCreatePortalSessionResponse,
  PaymentServiceAPIBillingGetBillingHistoryParams,
  PaymentServiceUseCasesDTOsBillingHistoryDto,
} from '.././models';

import { paymentInstance } from '../../../mutators/paymentMutator';

export const paymentServiceAPIBillingCreatePortalSession = (
  paymentServiceAPIBillingCreatePortalSessionRequest: PaymentServiceAPIBillingCreatePortalSessionRequest,
  signal?: AbortSignal
) => {
  return paymentInstance<PaymentServiceAPIBillingCreatePortalSessionResponse>({
    url: `/api/v1/billing/portal-session`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: paymentServiceAPIBillingCreatePortalSessionRequest,
    signal,
  });
};

export const getPaymentServiceAPIBillingCreatePortalSessionMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof paymentServiceAPIBillingCreatePortalSession>>,
    TError,
    { data: PaymentServiceAPIBillingCreatePortalSessionRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof paymentServiceAPIBillingCreatePortalSession>>,
  TError,
  { data: PaymentServiceAPIBillingCreatePortalSessionRequest },
  TContext
> => {
  const mutationKey = ['paymentServiceAPIBillingCreatePortalSession'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof paymentServiceAPIBillingCreatePortalSession>>,
    { data: PaymentServiceAPIBillingCreatePortalSessionRequest }
  > = (props) => {
    const { data } = props ?? {};

    return paymentServiceAPIBillingCreatePortalSession(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PaymentServiceAPIBillingCreatePortalSessionMutationResult = NonNullable<
  Awaited<ReturnType<typeof paymentServiceAPIBillingCreatePortalSession>>
>;
export type PaymentServiceAPIBillingCreatePortalSessionMutationBody =
  PaymentServiceAPIBillingCreatePortalSessionRequest;
export type PaymentServiceAPIBillingCreatePortalSessionMutationError = void;

export const usePaymentServiceAPIBillingCreatePortalSession = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof paymentServiceAPIBillingCreatePortalSession>>,
      TError,
      { data: PaymentServiceAPIBillingCreatePortalSessionRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof paymentServiceAPIBillingCreatePortalSession>>,
  TError,
  { data: PaymentServiceAPIBillingCreatePortalSessionRequest },
  TContext
> => {
  const mutationOptions = getPaymentServiceAPIBillingCreatePortalSessionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const paymentServiceAPIBillingGetBillingHistory = (
  params: PaymentServiceAPIBillingGetBillingHistoryParams,
  signal?: AbortSignal
) => {
  return paymentInstance<PaymentServiceUseCasesDTOsBillingHistoryDto>({
    url: `/api/v1/billing/history`,
    method: 'GET',
    params,
    signal,
  });
};

export const getPaymentServiceAPIBillingGetBillingHistoryQueryKey = (
  params?: PaymentServiceAPIBillingGetBillingHistoryParams
) => {
  return [`/api/v1/billing/history`, ...(params ? [params] : [])] as const;
};

export const getPaymentServiceAPIBillingGetBillingHistoryQueryOptions = <
  TData = Awaited<ReturnType<typeof paymentServiceAPIBillingGetBillingHistory>>,
  TError = void,
>(
  params: PaymentServiceAPIBillingGetBillingHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof paymentServiceAPIBillingGetBillingHistory>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPaymentServiceAPIBillingGetBillingHistoryQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof paymentServiceAPIBillingGetBillingHistory>>
  > = ({ signal }) => paymentServiceAPIBillingGetBillingHistory(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof paymentServiceAPIBillingGetBillingHistory>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PaymentServiceAPIBillingGetBillingHistoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof paymentServiceAPIBillingGetBillingHistory>>
>;
export type PaymentServiceAPIBillingGetBillingHistoryQueryError = void;

export function usePaymentServiceAPIBillingGetBillingHistory<
  TData = Awaited<ReturnType<typeof paymentServiceAPIBillingGetBillingHistory>>,
  TError = void,
>(
  params: PaymentServiceAPIBillingGetBillingHistoryParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof paymentServiceAPIBillingGetBillingHistory>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentServiceAPIBillingGetBillingHistory>>,
          TError,
          Awaited<ReturnType<typeof paymentServiceAPIBillingGetBillingHistory>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePaymentServiceAPIBillingGetBillingHistory<
  TData = Awaited<ReturnType<typeof paymentServiceAPIBillingGetBillingHistory>>,
  TError = void,
>(
  params: PaymentServiceAPIBillingGetBillingHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof paymentServiceAPIBillingGetBillingHistory>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof paymentServiceAPIBillingGetBillingHistory>>,
          TError,
          Awaited<ReturnType<typeof paymentServiceAPIBillingGetBillingHistory>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePaymentServiceAPIBillingGetBillingHistory<
  TData = Awaited<ReturnType<typeof paymentServiceAPIBillingGetBillingHistory>>,
  TError = void,
>(
  params: PaymentServiceAPIBillingGetBillingHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof paymentServiceAPIBillingGetBillingHistory>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function usePaymentServiceAPIBillingGetBillingHistory<
  TData = Awaited<ReturnType<typeof paymentServiceAPIBillingGetBillingHistory>>,
  TError = void,
>(
  params: PaymentServiceAPIBillingGetBillingHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof paymentServiceAPIBillingGetBillingHistory>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPaymentServiceAPIBillingGetBillingHistoryQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
