/**
 * Profile Settings Screen.
 * Displays user profile info with editable fields for name, email, phone.
 * Read-only display for role and tenant. Wired to profile API via Orval hooks.
 */
import React, { useCallback, useEffect, useState } from 'react';

import { ActivityIndicator, ScrollView, StyleSheet, Text, View } from 'react-native';

import { useQueryClient } from '@tanstack/react-query';

import AccountInfoSection from './AccountInfoSection';
import PersonalInfoSection from './PersonalInfoSection';
import { notifyError, notifySuccess } from '../../../../lib/notifications';
import { FM } from '../../../../localization/helpers';
import {
  getIdentityServiceAPIMeGetProfileQueryKey,
  useIdentityServiceAPIMeGetProfile,
  useIdentityServiceAPIMeUpdateProfile,
} from '../../../../server/autoGeneratedHooks/identity/me/me';
import { TestIds } from '../../../../shared/testIds';
import { useTheme } from '../../../../theme/hooks/useTheme';
import { isValueDefined } from '../../../../utils/is';
import { Button } from '../../../core/Button';
import ButtonVariant from '../../../core/Button/utils/ButtonVariant';
import Breadcrumb from '../../../Shared/Breadcrumb';
import Heading from '../../../Shared/Heading';
import { SECTION_SPACING, BODY_FONT_SIZE, ERROR_TEXT_MARGIN_TOP } from '../constants';

const styles = StyleSheet.create({
  container: { flex: 1 },
  scrollContent: { padding: SECTION_SPACING },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  errorText: { fontSize: BODY_FONT_SIZE, textAlign: 'center', marginTop: ERROR_TEXT_MARGIN_TOP },
  buttonSpacing: { marginTop: SECTION_SPACING },
});

const ProfileSettingsScreen = (): React.ReactElement => {
  const { theme } = useTheme();
  const { colors } = theme;
  const primary = theme.palette.primary['500'];
  const errorColor = theme.semantic.error['500'];

  const { data: profile, isLoading, isError } = useIdentityServiceAPIMeGetProfile();
  const updateProfile = useIdentityServiceAPIMeUpdateProfile();
  const queryClient = useQueryClient();

  const [firstName, setFirstName] = useState('');
  const [lastName, setLastName] = useState('');
  const [email, setEmail] = useState('');
  const [phone, setPhone] = useState('');

  useEffect(() => {
    if (isValueDefined(profile)) {
      setFirstName(profile.firstName ?? '');
      setLastName(profile.lastName ?? '');
      setEmail(profile.email ?? '');
      setPhone(profile.phoneNumber ?? '');
    }
  }, [profile]);

  const roleName = profile?.roles?.[0] ?? '';
  const tenantId = profile?.tenantId ?? '';

  const handleSave = useCallback(() => {
    updateProfile.mutate(
      { data: { firstName, lastName, email, phoneNumber: phone } },
      {
        onSuccess: () => {
          queryClient.invalidateQueries({
            queryKey: getIdentityServiceAPIMeGetProfileQueryKey(),
          }).catch(() => {
            // Ignore invalidation errors
          });
          notifySuccess(FM('settings.profile.messages.saveSuccess'));
        },
        onError: () => {
          notifyError(FM('settings.profile.messages.saveError'));
        },
      },
    );
  }, [firstName, lastName, email, phone, updateProfile, queryClient]);

  if (isLoading)
    return (
      <View style={styles.loadingContainer} testID={TestIds.PROFILE_SETTINGS_LOADING}>
        <ActivityIndicator color={primary} size="large" />
        <Text style={[styles.errorText, { color: colors.textSecondary }]}>{FM('loading')}</Text>
      </View>
    );

  if (isError)
    return (
      <View style={styles.loadingContainer} testID={TestIds.PROFILE_SETTINGS_ERROR}>
        <Text style={[styles.errorText, { color: errorColor }]}>
          {FM('settings.profile.messages.loadError')}
        </Text>
      </View>
    );

  const isSaving = updateProfile.isPending;
  const saveLabel = isSaving ? FM('common.saving') : FM('settings.profile.save');

  return (
    <View
      style={[styles.container, { backgroundColor: colors.background }]}
      testID={TestIds.PROFILE_SETTINGS_SCREEN}
    >
      <ScrollView contentContainerStyle={styles.scrollContent}>
        <Breadcrumb />
        <Heading>{FM('settings.profile.title')}</Heading>

        <PersonalInfoSection
          email={email}
          firstName={firstName}
          lastName={lastName}
          phone={phone}
          onEmailChange={setEmail}
          onFirstNameChange={setFirstName}
          onLastNameChange={setLastName}
          onPhoneChange={setPhone}
        />

        <AccountInfoSection roleName={roleName} tenantId={tenantId} />

        <View style={styles.buttonSpacing}>
          <Button
            accessibilityHint={FM('settings.profile.saveHint')}
            accessibilityLabel={FM('settings.profile.save')}
            disabled={isSaving}
            label={saveLabel}
            testID={TestIds.PROFILE_SAVE_BUTTON}
            variant={ButtonVariant.Primary}
            onPress={handleSave}
          />
        </View>
      </ScrollView>
    </View>
  );
};

export default ProfileSettingsScreen;
