/**
 * Unit tests for ProfileSettingsScreen logic.
 * Tests handleSave mutation call shape, success/error notifications,
 * query invalidation, and derived state (isSaving/saveLabel).
 */

// ---------------------------------------------------------------------------
// Mocks
// ---------------------------------------------------------------------------

jest.mock('../../../../localization/helpers', () => ({
  FM: (key: string) => key,
}));

jest.mock('../../../../theme/hooks/useTheme', () => ({
  useTheme: jest.fn(),
}));

jest.mock('../../../../utils/is', () => ({
  isValueDefined: (v: unknown) => v !== null && v !== undefined,
}));

const mockNotifySuccess = jest.fn();
const mockNotifyError = jest.fn();
jest.mock('../../../../lib/notifications', () => ({
  notifySuccess: (...args: unknown[]) => mockNotifySuccess(...args),
  notifyError: (...args: unknown[]) => mockNotifyError(...args),
}));

const mockInvalidateQueries = jest.fn().mockResolvedValue(undefined);
jest.mock('@tanstack/react-query', () => ({
  useQueryClient: () => ({
    invalidateQueries: mockInvalidateQueries,
  }),
}));

jest.mock('../../../../server/autoGeneratedHooks/identity/me/me', () => ({
  useIdentityServiceAPIMeGetProfile: jest.fn(),
  useIdentityServiceAPIMeUpdateProfile: jest.fn(),
  getIdentityServiceAPIMeGetProfileQueryKey: () => ['me', 'profile'],
}));

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const TEST_FIRST_NAME = 'John';
const TEST_LAST_NAME = 'Doe';
const TEST_EMAIL = 'john.doe@example.com';
const TEST_PHONE = '+1234567890';
const PROFILE_QUERY_KEY = ['me', 'profile'];

// ---------------------------------------------------------------------------
// Tests: handleSave mutation logic (simulated)
// ---------------------------------------------------------------------------

describe('ProfileSettingsScreen - handleSave logic', () => {
  const mockMutate = jest.fn();

  beforeEach(() => {
    jest.clearAllMocks();
  });

  /**
   * Simulates the handleSave callback from the component.
   */
  function simulateHandleSave(
    firstName: string,
    lastName: string,
    email: string,
    phone: string,
  ): void {
    const { FM } = require('../../../../localization/helpers');
    const { notifySuccess, notifyError } = require('../../../../lib/notifications');

    mockMutate(
      { data: { firstName, lastName, email, phoneNumber: phone } },
      {
        onSuccess: () => {
          mockInvalidateQueries({ queryKey: PROFILE_QUERY_KEY }).catch(() => {
            // Ignore invalidation errors
          });
          notifySuccess(FM('settings.profile.messages.saveSuccess'));
        },
        onError: () => {
          notifyError(FM('settings.profile.messages.saveError'));
        },
      },
    );
  }

  it('calls mutate with correct data shape', () => {
    simulateHandleSave(TEST_FIRST_NAME, TEST_LAST_NAME, TEST_EMAIL, TEST_PHONE);

    expect(mockMutate).toHaveBeenCalledWith(
      {
        data: {
          firstName: TEST_FIRST_NAME,
          lastName: TEST_LAST_NAME,
          email: TEST_EMAIL,
          phoneNumber: TEST_PHONE,
        },
      },
      expect.objectContaining({
        onSuccess: expect.any(Function),
        onError: expect.any(Function),
      }),
    );
  });

  it('payload includes firstName, lastName, email, and phoneNumber', () => {
    simulateHandleSave(TEST_FIRST_NAME, TEST_LAST_NAME, TEST_EMAIL, TEST_PHONE);

    const payload = mockMutate.mock.calls[0] as [{ data: Record<string, unknown> }];
    const dataKeys = Object.keys(payload[0].data);
    expect(dataKeys).toEqual(['firstName', 'lastName', 'email', 'phoneNumber']);
  });

  it('invalidates profile query on success', () => {
    simulateHandleSave(TEST_FIRST_NAME, TEST_LAST_NAME, TEST_EMAIL, TEST_PHONE);

    const callArgs = mockMutate.mock.calls[0] as [unknown, { onSuccess: () => void }];
    callArgs[1].onSuccess();

    expect(mockInvalidateQueries).toHaveBeenCalledWith({
      queryKey: PROFILE_QUERY_KEY,
    });
  });

  it('notifies success on mutation success', () => {
    simulateHandleSave(TEST_FIRST_NAME, TEST_LAST_NAME, TEST_EMAIL, TEST_PHONE);

    const callArgs = mockMutate.mock.calls[0] as [unknown, { onSuccess: () => void }];
    callArgs[1].onSuccess();

    expect(mockNotifySuccess).toHaveBeenCalledWith('settings.profile.messages.saveSuccess');
  });

  it('notifies error on mutation error', () => {
    simulateHandleSave(TEST_FIRST_NAME, TEST_LAST_NAME, TEST_EMAIL, TEST_PHONE);

    const callArgs = mockMutate.mock.calls[0] as [unknown, { onError: () => void }];
    callArgs[1].onError();

    expect(mockNotifyError).toHaveBeenCalledWith('settings.profile.messages.saveError');
  });

  it('does not notify error on success path', () => {
    simulateHandleSave(TEST_FIRST_NAME, TEST_LAST_NAME, TEST_EMAIL, TEST_PHONE);

    const callArgs = mockMutate.mock.calls[0] as [unknown, { onSuccess: () => void }];
    callArgs[1].onSuccess();

    expect(mockNotifyError).not.toHaveBeenCalled();
  });
});

// ---------------------------------------------------------------------------
// Tests: derived state (isSaving / saveLabel)
// ---------------------------------------------------------------------------

describe('ProfileSettingsScreen - derived state', () => {
  const { FM } = require('../../../../localization/helpers');

  /**
   * Simulates the saveLabel derivation from the component.
   */
  function deriveSaveLabel(isPending: boolean): string {
    return isPending ? FM('common.saving') : FM('settings.profile.save');
  }

  it('returns saving label when mutation is pending', () => {
    expect(deriveSaveLabel(true)).toBe('common.saving');
  });

  it('returns save label when mutation is not pending', () => {
    expect(deriveSaveLabel(false)).toBe('settings.profile.save');
  });
});

// ---------------------------------------------------------------------------
// Tests: profile data defaults
// ---------------------------------------------------------------------------

describe('ProfileSettingsScreen - profile data defaults', () => {
  /**
   * Simulates the default value extraction from profile response.
   */
  function extractDefaults(profile: {
    firstName?: string | null;
    lastName?: string | null;
    email?: string | null;
    phoneNumber?: string | null;
    roles?: string[] | null;
    tenantId?: string | null;
  }): {
    firstName: string;
    lastName: string;
    email: string;
    phone: string;
    roleName: string;
    tenantId: string;
  } {
    return {
      firstName: profile.firstName ?? '',
      lastName: profile.lastName ?? '',
      email: profile.email ?? '',
      phone: profile.phoneNumber ?? '',
      roleName: profile.roles?.[0] ?? '',
      tenantId: profile.tenantId ?? '',
    };
  }

  it('extracts all fields when profile is fully populated', () => {
    const profile = {
      firstName: 'Jane',
      lastName: 'Smith',
      email: 'jane@example.com',
      phoneNumber: '+1555000111',
      roles: ['Admin', 'User'],
      tenantId: 'tenant-123',
    };

    const defaults = extractDefaults(profile);

    expect(defaults.firstName).toBe('Jane');
    expect(defaults.lastName).toBe('Smith');
    expect(defaults.email).toBe('jane@example.com');
    expect(defaults.phone).toBe('+1555000111');
    expect(defaults.roleName).toBe('Admin');
    expect(defaults.tenantId).toBe('tenant-123');
  });

  it('falls back to empty strings when fields are null', () => {
    const profile = {
      firstName: null,
      lastName: null,
      email: null,
      phoneNumber: null,
      roles: null,
      tenantId: null,
    };

    const defaults = extractDefaults(profile);

    expect(defaults.firstName).toBe('');
    expect(defaults.lastName).toBe('');
    expect(defaults.email).toBe('');
    expect(defaults.phone).toBe('');
    expect(defaults.roleName).toBe('');
    expect(defaults.tenantId).toBe('');
  });

  it('falls back to empty strings when fields are undefined', () => {
    const defaults = extractDefaults({});

    expect(defaults.firstName).toBe('');
    expect(defaults.lastName).toBe('');
    expect(defaults.email).toBe('');
    expect(defaults.phone).toBe('');
    expect(defaults.roleName).toBe('');
    expect(defaults.tenantId).toBe('');
  });

  it('takes the first role from the roles array', () => {
    const profile = { roles: ['Manager', 'User', 'Viewer'] };

    const defaults = extractDefaults(profile);
    expect(defaults.roleName).toBe('Manager');
  });

  it('returns empty roleName when roles array is empty', () => {
    const profile = { roles: [] as string[] };

    const defaults = extractDefaults(profile);
    expect(defaults.roleName).toBe('');
  });
});
