/**
 * Helpers for building the business profile update request payload.
 */
import type { IdentityServiceAPIMeUpdateBusinessProfileRequest } from '../../../../server/autoGeneratedHooks/identity/models';

/** Convert empty strings to null for optional fields. */
function emptyToNull(value: string): string | null {
  return value !== '' ? value : null;
}

/** Build the request payload from form state. */
export function buildRequestData(
  fields: Record<string, string>,
  hoursJson: string | null,
): IdentityServiceAPIMeUpdateBusinessProfileRequest {
  return {
    name: fields.name,
    description: emptyToNull(fields.description),
    cuisineType: emptyToNull(fields.cuisineType),
    phone: emptyToNull(fields.phone),
    email: emptyToNull(fields.email),
    website: emptyToNull(fields.website),
    addressLine1: emptyToNull(fields.addressLine1),
    addressLine2: emptyToNull(fields.addressLine2),
    city: emptyToNull(fields.city),
    state: emptyToNull(fields.state),
    postalCode: emptyToNull(fields.postalCode),
    country: emptyToNull(fields.country),
    operatingHoursJson: hoursJson,
  };
}
