<#
Create lowercase copies of generated autoGeneratedHooks files so Metro can resolve imports
that use lowercase names. This is a pragmatic workaround for casing mismatches on Windows.
#>

$root = Split-Path -Parent $MyInvocation.MyCommand.Definition
$hooksDir = Join-Path $root '..\src\server\autoGeneratedHooks' | Resolve-Path -ErrorAction SilentlyContinue
if (-not $hooksDir) {
    Write-Host "autoGeneratedHooks directory not found"
    exit 0
}
$hooksDir = $hooksDir.Path

Get-ChildItem -Path $hooksDir -Recurse -File -Include *.ts,*.tsx | ForEach-Object {
    $file = $_.FullName
    $dir = Split-Path $file -Parent
    $name = Split-Path $file -Leaf
    $lower = Join-Path $dir ($name.ToLower())
    if ($file -ieq $lower) { return }
    if (-not (Test-Path $lower)) {
        Write-Host "Creating lowercase copy: $lower"
        Copy-Item -Path $file -Destination $lower -Force
    }
}

Write-Host "fix-hook-case: done"
