/**
 * User password mutation handlers.
 */
import { useCallback } from 'react';

import { notify, notifySuccess } from '../../lib/notifications';
import { FM } from '../../localization/helpers';
import { type useIdentityServiceAPIUsersUpdatePassword } from '../../server/autoGeneratedHooks/identity/users/users';
import { isValueDefined } from '../../utils/is';

function getErrorMsg(err: unknown): string {
  return err instanceof Error ? err.message : String(err ?? '');
}

interface PasswordResetState {
  passwordResetUserId: string | null;
  newPassword: string;
  closeModal: () => void;
}

export function usePasswordSubmit(
  updatePasswordMutation: ReturnType<typeof useIdentityServiceAPIUsersUpdatePassword>,
  state: PasswordResetState,
): () => void {
  return useCallback((): void => {
    const trimmed = state.newPassword.trim();
    if (!isValueDefined(state.passwordResetUserId) || trimmed.length === 0) return;

    updatePasswordMutation.mutate(
      {
        userId: state.passwordResetUserId,
        data: { newPassword: trimmed, temporary: false },
      },
      {
        onSuccess: () => {
          state.closeModal();
          notifySuccess(FM('users.messages.passwordUpdateSuccess'));
        },
        onError: (err: unknown) => {
          notify('error', { message: FM('users.errors.passwordUpdateFailed', getErrorMsg(err)) });
        },
      },
    );
  }, [updatePasswordMutation, state]);
}
