/**
 * Tests for useQuizForm hook - covers BUG-QUIZ-001, BUG-QUIZ-004, BUG-QUIZ-008 fixes.
 * Verifies that handleSubmit, handleNext, handleBack use refs (no stale closures)
 * and are wrapped in useCallback (stable references).
 */
import { Alert } from 'react-native';

import { renderHook, act } from '@testing-library/react-native';

import { useQuizForm } from './useQuizForm';
import { QuestionType } from '../../../server/autoGeneratedHooks/questioner/models/questionType';

import type { Question as ApiQuestionModel } from '../../../server/autoGeneratedHooks/questioner/models';

function createTemplateData(questions: ApiQuestionModel[] = []): {
  externalId: string;
  name: string;
  description: string;
  contents: { questions: ApiQuestionModel[] };
} {
  return { externalId: 'tpl-1', name: 'Test Quiz', description: 'desc', contents: { questions } };
}

const mockT = jest.fn((key: string, defaultValue?: string) => defaultValue ?? key);
const mockRefetch = jest.fn(async () => Promise.resolve(undefined));

function createMockMutation(): { mutateAsync: jest.Mock } {
  return { mutateAsync: jest.fn(async () => Promise.resolve({})) };
}

describe('useQuizForm', () => {
  let alertSpy: jest.SpyInstance;

  beforeEach(() => {
    jest.clearAllMocks();
    alertSpy = jest.spyOn(Alert, 'alert').mockImplementation(() => {});
  });

  afterEach(() => { alertSpy.mockRestore(); });

  describe('BUG-QUIZ-001/008: callbacks use useCallback', () => {
    it('handleSubmit uses latest form data for submission payload', async () => {
      const data = createTemplateData([
        { id: 'q1', name: 'Q1', type: QuestionType.Text, page: 1, order: 1, isRequired: true },
      ]);
      const mutation = createMockMutation();
      const { result } = renderHook(() => useQuizForm(data, mutation, mockRefetch, mockT));

      // Update answer then submit -- the latest answer should be in the payload
      act(() => { result.current.updateAnswer('q1', 'latest-answer'); });
      await act(async () => { await result.current.handleSubmit(); });

      expect(mutation.mutateAsync).toHaveBeenCalledTimes(1);
      const payload = mutation.mutateAsync.mock.calls[0]?.[0]?.data;
      const submittedAnswer = payload?.contents?.questions?.find((q: { id: string }) => q.id === 'q1')?.answer;
      expect(submittedAnswer).toEqual({ stringValue: 'latest-answer' });
    });
  });

  describe('BUG-QUIZ-004: handleSubmit uses validateAllPages', () => {
    it('shows validation error when required fields on any page are empty', async () => {
      const data = createTemplateData([
        { id: 'q1', name: 'Q1', type: QuestionType.Text, page: 1, order: 1, isRequired: true },
        { id: 'q2', name: 'Q2', type: QuestionType.Text, page: 2, order: 2, isRequired: true },
      ]);
      const mutation = createMockMutation();
      const { result } = renderHook(() => useQuizForm(data, mutation, mockRefetch, mockT));

      act(() => { result.current.updateAnswer('q2', 'answered'); });

      await act(async () => { await result.current.handleSubmit(); });
      expect(mutation.mutateAsync).not.toHaveBeenCalled();
      expect(alertSpy).toHaveBeenCalledWith('Validation Error', 'Please fill in all required fields.');
    });

    it('submits successfully when all required fields are answered', async () => {
      const data = createTemplateData([
        { id: 'q1', name: 'Q1', type: QuestionType.Text, page: 1, order: 1, isRequired: true },
      ]);
      const mutation = createMockMutation();
      const { result } = renderHook(() => useQuizForm(data, mutation, mockRefetch, mockT));

      act(() => { result.current.updateAnswer('q1', 'answered'); });

      await act(async () => { await result.current.handleSubmit(); });
      expect(mutation.mutateAsync).toHaveBeenCalledTimes(1);
      expect(result.current.showThankYou).toBe(true);
    });
  });

  describe('submission error handling', () => {
    it('shows error alert when submission fails', async () => {
      const data = createTemplateData([
        { id: 'q1', name: 'Q1', type: QuestionType.Text, page: 1, order: 1, isRequired: false },
      ]);
      const mutation = { mutateAsync: jest.fn(async () => Promise.reject(new Error('Network error'))) };
      const { result } = renderHook(() => useQuizForm(data, mutation, mockRefetch, mockT));

      await act(async () => { await result.current.handleSubmit(); });
      expect(alertSpy).toHaveBeenCalledWith('Error', 'Something went wrong during submission.');
      expect(result.current.submitting).toBe(false);
    });
  });

  describe('resetQuiz', () => {
    it('clears all answers and resets page', () => {
      const data = createTemplateData([
        { id: 'q1', name: 'Q1', type: QuestionType.Text, page: 1, order: 1, isRequired: false },
      ]);
      const mutation = createMockMutation();
      const { result } = renderHook(() => useQuizForm(data, mutation, mockRefetch, mockT));

      act(() => { result.current.updateAnswer('q1', 'test'); });
      expect(result.current.form?.questions[0]?.answer).toBe('test');

      act(() => { result.current.resetQuiz(); });
      expect(result.current.form?.questions[0]?.answer).toBeUndefined();
      expect(result.current.currentPage).toBe(1);
    });
  });
});
