


/**
 * useQuizForm - Custom hook for managing quiz form state and submission.
 */
import { useCallback, useMemo, useRef, useState } from 'react';

import { Alert } from 'react-native';
import type { ScrollView, Animated } from 'react-native';

import { useQuizFormState } from './useQuizFormState';
import { isValueDefined } from '../../../utils/is';
import { findPageInDirection, buildSubmissionPayload } from '../utils/quizHelpers';

import type { DynamicQuiz, Answer, Question as UiQuestion } from '../../../components/DynamicForm';
import type { CreateCompletedQuestionerRequest, Question as ApiQuestionModel } from '../../../server/autoGeneratedHooks/questioner/models';

const ANIMATION_OFF = false;

interface TemplateData { externalId?: string | null; name?: string | null; description?: string | null; contents?: { questions?: ApiQuestionModel[] } | null; }
interface UseQuizFormReturn {
  form: DynamicQuiz | null; errors: Record<string, string>; currentPage: number; totalPages: number; currentQuestions: UiQuestion[];
  submitting: boolean; showThankYou: boolean; scrollRef: React.RefObject<ScrollView | null>; pageOpacity: Animated.Value;
  shouldSkip: (q: UiQuestion) => boolean; updateAnswer: (id: string, v: Answer) => void; validatePage: (p: number) => boolean;
  handleNext: () => void; handleBack: () => void; handleSubmit: () => Promise<void>; resetQuiz: () => void; onThankYouComplete: () => void;
}

interface MutationArg { mutateAsync: (variables: { data: CreateCompletedQuestionerRequest }) => Promise<unknown> }

interface SubmitDeps {
  s: ReturnType<typeof useQuizFormState>;
  createCompleted: MutationArg;
  formRef: React.RefObject<DynamicQuiz | null>;
  dataRef: React.RefObject<TemplateData | undefined>;
  tRef: React.RefObject<(k: string, d?: string) => string>;
  setSubmitting: (v: boolean) => void;
  setShowThankYou: (v: boolean) => void;
}

interface ResetDeps { s: ReturnType<typeof useQuizFormState>; formRef: React.RefObject<DynamicQuiz | null>; refetch: () => Promise<unknown> }

export function useQuizForm(data: TemplateData | undefined, createCompleted: MutationArg, refetch: () => Promise<unknown>, t: (k: string, d?: string) => string): UseQuizFormReturn {
  const s = useQuizFormState(data, t);
  const [submitting, setSubmitting] = useState(false);
  const [showThankYou, setShowThankYou] = useState(false);
  const formRef = useRef(s.form); formRef.current = s.form;
  const pageRef = useRef(s.currentPage); pageRef.current = s.currentPage;
  const dataRef = useRef(data); dataRef.current = data;
  const tRef = useRef(t); tRef.current = t;
  const submitDeps = useMemo(() => ({ s, createCompleted, formRef, dataRef, tRef, setSubmitting, setShowThankYou }), [s, createCompleted]);
  const handleSubmit = useSubmit(submitDeps);
  const resetDeps = useMemo(() => ({ s, formRef, refetch }), [s, refetch]);
  const resetQuiz = useReset(resetDeps);
  const handleNext = useCallback((): void => {
    const form = formRef.current; const page = pageRef.current;
    if (!isValueDefined(form) || !s.validatePage(page)) return;
    const target = findPageInDirection(form, page, 1);
    if (isValueDefined(target)) s.navigation.navigateToPage(target, page, { animate: ANIMATION_OFF });
    else handleSubmit().catch(() => {});
  }, [s, handleSubmit]);
  const handleBack = useCallback((): void => {
    const form = formRef.current; const page = pageRef.current;
    if (!isValueDefined(form)) return;
    const target = findPageInDirection(form, page, -1);
    if (isValueDefined(target)) s.navigation.navigateToPage(target, page, { animate: ANIMATION_OFF });
  }, [s]);
  const onThankYouComplete = useCallback((): void => { setShowThankYou(false); resetQuiz(); }, [resetQuiz]);
  return { form: s.form, errors: s.errors, currentPage: s.currentPage, totalPages: s.totalPages, currentQuestions: s.currentQuestions, submitting, showThankYou, scrollRef: s.scrollRef, pageOpacity: s.pageOpacity, shouldSkip: s.shouldSkip, updateAnswer: s.updateAnswer, validatePage: s.validatePage, handleNext, handleBack, handleSubmit, resetQuiz, onThankYouComplete };
}

function useSubmit({ s, createCompleted, formRef, dataRef, tRef, setSubmitting, setShowThankYou }: SubmitDeps): () => Promise<void> {
  return useCallback(async (): Promise<void> => {
    const form = formRef.current; const currentData = dataRef.current;
    if (!isValueDefined(form) || !isValueDefined(currentData)) return;
    if (!s.validateAllPages()) { Alert.alert(tRef.current('Validation Error'), tRef.current('Please fill in all required fields.')); return; }
    try { setSubmitting(true); await createCompleted.mutateAsync({ data: buildSubmissionPayload(form, currentData) }); setShowThankYou(true); }
    catch (_) { Alert.alert(tRef.current('Error'), tRef.current('Something went wrong during submission.')); }
    finally { setSubmitting(false); }
  }, [s, createCompleted, formRef, dataRef, tRef, setSubmitting, setShowThankYou]);
}

function useReset({ s, formRef, refetch }: ResetDeps): () => void {
  return useCallback((): void => {
    const form = formRef.current;
    if (!isValueDefined(form)) return;
    s.setForm({ ...form, questions: form.questions.map((q) => ({ ...q, answer: undefined })) });
    s.setCurrentPage(1); s.setErrors({}); s.navigation.resetPageOpacity(); s.navigation.scrollToTop(); refetch().catch(() => {});
  }, [s, refetch, formRef]);
}
