/**
 * Menu mutation handlers for delete, toggle, and external link operations.
 */
import { useCallback } from 'react';

import { Linking, Platform } from 'react-native';

import { notify, notifySuccess } from '../../lib/notifications';
import { type useOnlineMenuWebMenuDelete } from '../../server/autoGeneratedHooks/onlinemenu/tenantmenus/tenantmenus';
import AnalyticsEventName from '../../shared/enums/AnalyticsEventName';
import { logger } from '../../utils/logger';
import { type useActivateMenu, type useDeactivateMenu } from '../useMenuActions';
import { getErrorMessage } from './menuErrorUtils';

import type { AnalyticsTrackFn } from '../../lib/analytics';
import type { TranslateFn } from '../../localization/types';
import type { TenantMenusDto } from '../../types/menuTypes';

interface UseMenuDeleteArgs {
  deleteMutation: ReturnType<typeof useOnlineMenuWebMenuDelete>;
  refetchMenusSoon: () => void;
  t: TranslateFn;
  analyticsTrack?: AnalyticsTrackFn;
}

export function useMenuDelete(args: UseMenuDeleteArgs): (item: TenantMenusDto) => void {
  const { deleteMutation, refetchMenusSoon, t, analyticsTrack } = args;
  return useCallback(
    (item: TenantMenusDto) => {
      const externalId = item.externalId;
      if (typeof externalId !== 'string' || externalId.length === 0) {
        notify('error', t('onlineMenus.errors.deleteFailed'));
        return;
      }

      deleteMutation.mutate(
        { externalId },
        {
          onSuccess: () => {
            notifySuccess(t('onlineMenus.messages.deleteSuccess'));
            refetchMenusSoon();
            analyticsTrack?.(AnalyticsEventName.MenuDeleted, { menuId: externalId });
          },
          onError: (err: unknown) => {
            const message = getErrorMessage(err);
            notify('error', `${t('onlineMenus.errors.deleteFailed')}: ${message}`);
            logger.error('OnlineMenusPage', 'Delete error:', err);
          },
        },
      );
    },
    [deleteMutation, refetchMenusSoon, t, analyticsTrack],
  );
}

interface UseMenuActivateToggleArgs {
  activateMutation: ReturnType<typeof useActivateMenu>;
  deactivateMutation: ReturnType<typeof useDeactivateMenu>;
  refetchMenusSoon: () => void;
  t: TranslateFn;
  analyticsTrack?: AnalyticsTrackFn;
}

interface ToggleConfig {
  isActive: boolean;
  mutation: ReturnType<typeof useActivateMenu>;
}

function resolveToggleConfig(
  currentStatus: boolean | number | undefined,
  activateMutation: ReturnType<typeof useActivateMenu>,
  deactivateMutation: ReturnType<typeof useDeactivateMenu>,
): ToggleConfig {
  const isActive = typeof currentStatus === 'boolean' ? currentStatus : currentStatus === 1;
  return { isActive, mutation: isActive ? deactivateMutation : activateMutation };
}

interface ExecuteToggleArgs {
  id: string;
  isActive: boolean;
  mutation: ReturnType<typeof useActivateMenu>;
  successKey: string;
  errorKey: string;
  analyticsEvent: AnalyticsEventName;
  refetchMenusSoon: () => void;
  t: TranslateFn;
  analyticsTrack?: AnalyticsTrackFn;
}

function executeToggleMutation(args: ExecuteToggleArgs): void {
  const { id, mutation, successKey, errorKey, analyticsEvent, refetchMenusSoon, t, analyticsTrack } = args;
  mutation.mutate(
    { externalId: id },
    {
      onSuccess: () => {
        notifySuccess(t(`onlineMenus.messages.${successKey}`));
        refetchMenusSoon();
        analyticsTrack?.(analyticsEvent, { menuId: id });
      },
      onError: (err: unknown) => {
        const message = getErrorMessage(err);
        notify('error', `${t(`onlineMenus.errors.${errorKey}`)}: ${message}`);
        logger.error('OnlineMenusPage', `${successKey} error:`, err);
      },
    },
  );
}

export function useMenuActivateToggle(
  args: UseMenuActivateToggleArgs,
): (id: string, currentStatus?: boolean | number) => void {
  const { activateMutation, deactivateMutation, refetchMenusSoon, t, analyticsTrack } = args;
  return useCallback(
    (id: string, currentStatus?: boolean | number) => {
      const { isActive, mutation } = resolveToggleConfig(currentStatus, activateMutation, deactivateMutation);
      executeToggleMutation({
        id, isActive, mutation,
        successKey: isActive ? 'deactivateSuccess' : 'activateSuccess',
        errorKey: isActive ? 'deactivateFailed' : 'activateFailed',
        analyticsEvent: isActive ? AnalyticsEventName.MenuDeactivated : AnalyticsEventName.MenuActivated,
        refetchMenusSoon, t, analyticsTrack,
      });
    },
    [activateMutation, deactivateMutation, refetchMenusSoon, t, analyticsTrack],
  );
}

export function useMenuOpenExternal(t: TranslateFn): (externalId: string) => void {
  return useCallback(
    (externalId: string) => {
      const baseUrl = Platform.OS === 'web' ? window.location.origin : '';
      const publicUrl = `${baseUrl}/public/menu/${externalId}`;

      Linking.openURL(publicUrl).catch((err: unknown) => {
        const message = getErrorMessage(err);
        notify('error', `${t('onlineMenus.errors.openExternalFailed')}: ${message}`);
        logger.error('OnlineMenusPage', 'Open external link error:', err);
      });
    },
    [t],
  );
}
