/**
 * Menu query hooks for fetching and managing menu data.
 */
import { useCallback, useRef } from 'react';

import {
  useOnlineMenuWebMenuDelete,
  useOnlineMenuWebMenuList,
  useOnlineMenuWebMenuUpdate,
 useOnlineMenuWebTenantMenusCreate } from '../../server/autoGeneratedHooks/onlinemenu/tenantmenus/tenantmenus';
import { useActivateMenu, useDeactivateMenu } from '../useMenuActions';

/** Delay in ms before second refetch to ensure cache refresh */
const REFETCH_DELAY_MS = 250;

interface MenuQueries {
  listQuery: ReturnType<typeof useOnlineMenuWebMenuList>;
  createMutation: ReturnType<typeof useOnlineMenuWebTenantMenusCreate>;
  updateMutation: ReturnType<typeof useOnlineMenuWebMenuUpdate>;
  deleteMutation: ReturnType<typeof useOnlineMenuWebMenuDelete>;
  activateMutation: ReturnType<typeof useActivateMenu>;
  deactivateMutation: ReturnType<typeof useDeactivateMenu>;
  refetchMenusSoon: () => void;
}

export function useMenuQueries(): MenuQueries {
  const listQuery = useOnlineMenuWebMenuList();
  const createMutation = useOnlineMenuWebTenantMenusCreate();
  const updateMutation = useOnlineMenuWebMenuUpdate();
  const deleteMutation = useOnlineMenuWebMenuDelete();
  const activateMutation = useActivateMenu();
  const deactivateMutation = useDeactivateMenu();

  const refetchRef = useRef(listQuery.refetch);
  refetchRef.current = listQuery.refetch;

  const refetchMenusSoon = useCallback((): void => {
    refetchRef.current().catch(() => {});
    if (typeof setTimeout === 'function')
      setTimeout(() => {
        refetchRef.current().catch(() => {});
      }, REFETCH_DELAY_MS);

  }, []);

  return {
    listQuery,
    createMutation,
    updateMutation,
    deleteMutation,
    activateMutation,
    deactivateMutation,
    refetchMenusSoon,
  };
}
