export const AnalyticsTestIds = {
  ANALYTICS_SCREEN: 'analytics-screen',
  ANALYTICS_STAT_TOTAL_MENUS: 'analytics-stat-total-menus',
  ANALYTICS_STAT_ACTIVE_MENUS: 'analytics-stat-active-menus',
  ANALYTICS_STAT_SCANS_TODAY: 'analytics-stat-scans-today',
  ANALYTICS_STAT_SCANS_TOTAL: 'analytics-stat-scans-total',
  ANALYTICS_TOP_MENUS_LIST: 'analytics-top-menus-list',
  ANALYTICS_TOP_MENU_ITEM: 'analytics-top-menu-item',
  ANALYTICS_LOADING: 'analytics-loading',
  ANALYTICS_ERROR: 'analytics-error',
  ANALYTICS_RETRY_BUTTON: 'analytics-retry-button',
  ANALYTICS_EMPTY_STATE: 'analytics-empty-state',
  NAV_ANALYTICS: 'nav-analytics',

  // Menu Analytics Detail
  MENU_ANALYTICS_SCREEN: 'menu-analytics-screen',
  MENU_ANALYTICS_LOADING: 'menu-analytics-loading',
  MENU_ANALYTICS_ERROR: 'menu-analytics-error',
  MENU_ANALYTICS_RETRY_BUTTON: 'menu-analytics-retry-button',
  MENU_ANALYTICS_TIME_RANGE: 'menu-analytics-time-range',
  MENU_ANALYTICS_STAT_TOTAL_VIEWS: 'menu-analytics-stat-total-views',
  MENU_ANALYTICS_STAT_UNIQUE_VISITORS: 'menu-analytics-stat-unique-visitors',
  MENU_ANALYTICS_STAT_AVG_DURATION: 'menu-analytics-stat-avg-duration',
  MENU_ANALYTICS_VIEWS_CHART: 'menu-analytics-views-chart',
  MENU_ANALYTICS_DEVICE_CHART: 'menu-analytics-device-chart',
  MENU_ANALYTICS_TOP_ITEMS_LIST: 'menu-analytics-top-items-list',
  MENU_ANALYTICS_TOP_ITEM: 'menu-analytics-top-item',

  // Popular Items
  POPULAR_ITEMS_CARD: 'popular-items-card',
  POPULAR_ITEMS_LOADING: 'popular-items-loading',
  POPULAR_ITEMS_ERROR: 'popular-items-error',
  POPULAR_ITEMS_EMPTY: 'popular-items-empty',
  POPULAR_ITEMS_RETRY_BUTTON: 'popular-items-retry-button',
  POPULAR_ITEMS_ROW: 'popular-items-row',
  POPULAR_ITEMS_TIME_SELECTOR: 'popular-items-time-selector',
  POPULAR_ITEMS_TIME_BUTTON: 'popular-items-time-button',
  ITEM_POPULARITY_BADGE: 'item-popularity-badge',
} as const;
