/** Test IDs for the Location Settings screens. */
export const LocationSettingsTestIds = {
  LOCATION_SETTINGS_SCREEN: 'location-settings-screen',
  LOCATION_SETTINGS_LOADING: 'location-settings-loading',
  LOCATION_SETTINGS_ERROR: 'location-settings-error',
  LOCATION_ADD_BUTTON: 'location-add-button',
  LOCATION_LIST: 'location-list',
  LOCATION_CARD: 'location-card',
  LOCATION_CARD_NAME: 'location-card-name',
  LOCATION_CARD_CITY: 'location-card-city',
  LOCATION_CARD_HQ_BADGE: 'location-card-hq-badge',
  LOCATION_CARD_STATUS_BADGE: 'location-card-status-badge',
  LOCATION_CARD_EDIT_BUTTON: 'location-card-edit-button',
  LOCATION_CARD_DELETE_BUTTON: 'location-card-delete-button',
  LOCATION_FORM_MODAL: 'location-form-modal',
  LOCATION_FORM_NAME_INPUT: 'location-form-name-input',
  LOCATION_FORM_ADDRESS1_INPUT: 'location-form-address1-input',
  LOCATION_FORM_ADDRESS2_INPUT: 'location-form-address2-input',
  LOCATION_FORM_CITY_INPUT: 'location-form-city-input',
  LOCATION_FORM_STATE_INPUT: 'location-form-state-input',
  LOCATION_FORM_POSTAL_INPUT: 'location-form-postal-input',
  LOCATION_FORM_COUNTRY_INPUT: 'location-form-country-input',
  LOCATION_FORM_PHONE_INPUT: 'location-form-phone-input',
  LOCATION_FORM_EMAIL_INPUT: 'location-form-email-input',
  LOCATION_FORM_TIMEZONE_INPUT: 'location-form-timezone-input',
  LOCATION_FORM_HQ_TOGGLE: 'location-form-hq-toggle',
  LOCATION_FORM_SAVE_BUTTON: 'location-form-save-button',
  LOCATION_FORM_CANCEL_BUTTON: 'location-form-cancel-button',
  LOCATION_EMPTY_STATE: 'location-empty-state',
  LOCATION_UPGRADE_PROMPT: 'location-upgrade-prompt',
} as const;
