/** Test IDs for Online Menu management, editor, categories, items, display. */
export const MenuTestIds = {
  MENU_LIST: 'menu-list',
  MENU_LIST_CREATE_BUTTON: 'menu-list-create-button',
  MENU_LIST_REFRESH_BUTTON: 'menu-list-refresh-button',
  MENU_TAB_ALL: 'menu-tab-all',
  MENU_TAB_ACTIVE: 'menu-tab-active',
  MENU_CARD: 'menu-card',
  MENU_CARD_ID: 'menu-card-id',
  MENU_CARD_NAME: 'menu-card-name',
  MENU_CARD_DESCRIPTION: 'menu-card-description',
  MENU_CARD_STATUS_BADGE: 'menu-card-status-badge',
  MENU_CARD_EDIT_BUTTON: 'menu-card-edit-button',
  MENU_CARD_DELETE_BUTTON: 'menu-card-delete-button',
  MENU_CARD_ACTIVATE_BUTTON: 'menu-card-activate-button',
  MENU_CARD_DEACTIVATE_BUTTON: 'menu-card-deactivate-button',
  MENU_CARD_PREVIEW_BUTTON: 'menu-card-preview-button',
  MENU_CARD_OPEN_EXTERNAL_BUTTON: 'menu-card-open-external-button',
  MENU_PREVIEW_MODAL: 'menu-preview-modal',
  // Menu Editor
  MENU_TAB_METADATA: 'menu-tab-metadata',
  MENU_TAB_CONTENT: 'menu-tab-content',
  MENU_TAB_PREVIEW: 'menu-tab-preview',
  MENU_EDITOR: 'menu-editor',
  MENU_EDITOR_NAME_INPUT: 'menu-editor-name-input',
  MENU_EDITOR_DESCRIPTION_INPUT: 'menu-editor-description-input',
  MENU_EDITOR_SAVE_BUTTON: 'menu-editor-save-button',
  MENU_EDITOR_CANCEL_BUTTON: 'menu-editor-cancel-button',
  MENU_EDITOR_THEME_SELECTOR: 'menu-editor-theme-selector',
  MENU_EDITOR_TITLE_FONT_INPUT: 'menu-editor-title-font-input',
  MENU_EDITOR_TITLE_FONT_SIZE_INPUT: 'menu-editor-title-font-size-input',
  MENU_EDITOR_BG_COLOR_PICKER: 'menu-editor-bg-color-picker',
  MENU_EDITOR_TEXT_COLOR_PICKER: 'menu-editor-text-color-picker',

  // Category Management
  CATEGORY_LIST: 'category-list',
  CATEGORY_ADD_BUTTON: 'category-add-button',
  CATEGORY_ITEM: 'category-item',
  CATEGORY_TOGGLE_BUTTON: 'category-toggle-button',
  CATEGORY_NAME_INPUT: 'category-name-input',
  CATEGORY_NAME_FULL_INPUT: 'category-name-full-input',
  CATEGORY_DESCRIPTION_INPUT: 'category-description-input',
  CATEGORY_EDIT_BUTTON: 'category-edit-button',
  CATEGORY_DELETE_BUTTON: 'category-delete-button',
  CATEGORY_DRAG_HANDLE: 'category-drag-handle',
  CATEGORY_MOVE_UP_BUTTON: 'category-move-up-button',
  CATEGORY_MOVE_DOWN_BUTTON: 'category-move-down-button',
  CATEGORY_IMAGE_PICKER: 'category-image-picker',
  CATEGORY_VIDEO_PICKER: 'category-video-picker',

  // Menu Item Management
  MENU_ITEM_LIST: 'menu-item-list',
  MENU_ITEM_ADD_BUTTON: 'menu-item-add-button',
  MENU_ITEM: 'menu-item',
  MENU_ITEM_NAME_INPUT: 'menu-item-name-input',
  MENU_ITEM_NAME_FULL_INPUT: 'menu-item-name-full-input',
  MENU_ITEM_DESCRIPTION_INPUT: 'menu-item-description-input',
  MENU_ITEM_PRICE_INPUT: 'menu-item-price-input',
  MENU_ITEM_AVAILABLE_TOGGLE: 'menu-item-available-toggle',
  MENU_ITEM_EDIT_BUTTON: 'menu-item-edit-button',
  MENU_ITEM_DELETE_BUTTON: 'menu-item-delete-button',
  MENU_ITEM_DRAG_HANDLE: 'menu-item-drag-handle',
  MENU_ITEM_MOVE_UP_BUTTON: 'menu-item-move-up-button',
  MENU_ITEM_MOVE_DOWN_BUTTON: 'menu-item-move-down-button',
  MENU_ITEM_IMAGE_PICKER: 'menu-item-image-picker',
  MENU_ITEM_VIDEO_PICKER: 'menu-item-video-picker',
  MENU_ITEM_DOCUMENT_PICKER: 'menu-item-document-picker',
  MENU_ITEM_AI_GENERATE_BUTTON: 'menu-item-ai-generate-button',
  MENU_ITEM_AI_LOADING: 'menu-item-ai-loading',
  MENU_ITEM_AI_ERROR: 'menu-item-ai-error',

  // Live Preview
  LIVE_PREVIEW_PANEL: 'live-preview-panel',
  LIVE_PREVIEW_VIEWPORT_TOGGLE: 'live-preview-viewport-toggle',
  LIVE_PREVIEW_MOBILE: 'live-preview-mobile',
  LIVE_PREVIEW_TABLET: 'live-preview-tablet',
  LIVE_PREVIEW_DESKTOP: 'live-preview-desktop',

  // Menu Content View (Display)
  MENU_CONTENT_VIEW: 'menu-content-view',
  MENU_CONTENT_VIEW_HEADER: 'menu-content-view-header',
  MENU_CONTENT_VIEW_BANNER: 'menu-content-view-banner',
  MENU_CONTENT_VIEW_LOGO: 'menu-content-view-logo',
  MENU_CONTENT_VIEW_TITLE: 'menu-content-view-title',
  MENU_CONTENT_VIEW_DESCRIPTION: 'menu-content-view-description',
  MENU_CONTENT_VIEW_CATEGORIES: 'menu-content-view-categories',
  MENU_CONTENT_VIEW_EMPTY: 'menu-content-view-empty',
  MENU_CONTENT_VIEW_CATEGORY_SECTION: 'menu-content-view-category-section',
  MENU_CONTENT_VIEW_MENU_ITEM: 'menu-content-view-menu-item',

  // Import/Export Configuration
  IMPORT_EXPORT_CONTAINER: 'import-export-container',
  EXPORT_CONFIG_BUTTON: 'export-config-button',
  IMPORT_CONFIG_BUTTON: 'import-config-button',
  IMPORT_FILE_INPUT: 'import-file-input',
  IMPORT_PREVIEW_MODAL: 'import-preview-modal',
  IMPORT_PREVIEW_CONTENT: 'import-preview-content',
  IMPORT_CONFIRM_BUTTON: 'import-confirm-button',
  IMPORT_CANCEL_BUTTON: 'import-cancel-button',
  IMPORT_ERROR_MESSAGE: 'import-error-message',

  // Category Emoji Picker
  CATEGORY_EMOJI_BUTTON: 'category-emoji-button',
  CATEGORY_EMOJI_CLEAR_BUTTON: 'category-emoji-clear-button',
  CATEGORY_EMOJI_PICKER: 'category-emoji-picker',
  CATEGORY_EMOJI_GRID_ITEM: 'category-emoji-grid-item',

  // Category Styling Section
  CATEGORY_STYLING_SECTION: 'category-styling-section',
  CATEGORY_STYLING_TOGGLE: 'category-styling-toggle',
  CATEGORY_STYLING_CONTENT: 'category-styling-content',
  CATEGORY_STYLING_BOX_EDITOR: 'category-styling-box-editor',
  CATEGORY_STYLING_MEDIA_EDITOR: 'category-styling-media-editor',

  // Item Styling Section
  ITEM_STYLING_SECTION: 'item-styling-section',
  ITEM_STYLING_HEADER: 'item-styling-header',
  ITEM_STYLING_CONTENT: 'item-styling-content',

  // QR Code
  MENU_CARD_QR_CODE_BUTTON: 'menu-card-qr-code-button',
  QR_CODE_MODAL: 'qr-code-modal',
  QR_CODE_DISPLAY: 'qr-code-display',
  QR_CODE_URL_TEXT: 'qr-code-url-text',
  QR_CODE_MENU_NAME: 'qr-code-menu-name',
  QR_CODE_DOWNLOAD_PNG_BUTTON: 'qr-code-download-png-button',
  QR_CODE_DOWNLOAD_SVG_BUTTON: 'qr-code-download-svg-button',
  QR_CODE_COPY_LINK_BUTTON: 'qr-code-copy-link-button',
  QR_CODE_CLOSE_BUTTON: 'qr-code-close-button',
  QR_CODE_FG_COLOR_INPUT: 'qr-code-fg-color-input',
  QR_CODE_BG_COLOR_INPUT: 'qr-code-bg-color-input',

  // Embed Widget
  MENU_CARD_EMBED_BUTTON: 'menu-card-embed-button',
  EMBED_WIDGET_MODAL: 'embed-widget-modal',
  EMBED_WIDGET_CLOSE_BUTTON: 'embed-widget-close-button',
  EMBED_WIDGET_TAB_IFRAME: 'embed-widget-tab-iframe',
  EMBED_WIDGET_TAB_JS: 'embed-widget-tab-js',
  EMBED_WIDGET_WIDTH_INPUT: 'embed-widget-width-input',
  EMBED_WIDGET_HEIGHT_INPUT: 'embed-widget-height-input',
  EMBED_WIDGET_THEME_SELECT: 'embed-widget-theme-select',
  EMBED_WIDGET_ACCENT_COLOR_INPUT: 'embed-widget-accent-color-input',
  EMBED_WIDGET_CODE_PREVIEW: 'embed-widget-code-preview',
  EMBED_WIDGET_COPY_BUTTON: 'embed-widget-copy-button',
  EMBED_WIDGET_PRESET_FULL: 'embed-widget-preset-full',
  EMBED_WIDGET_PRESET_FIXED: 'embed-widget-preset-fixed',

  // QR Code Designer
  QR_DESIGNER_MODAL: 'qr-designer-modal',
  QR_DESIGNER_CLOSE_BUTTON: 'qr-designer-close-button',
  QR_DESIGNER_PREVIEW: 'qr-designer-preview',
  QR_DESIGNER_TEMPLATE_TENT: 'qr-designer-template-tent',
  QR_DESIGNER_TEMPLATE_STICKER: 'qr-designer-template-sticker',
  QR_DESIGNER_TEMPLATE_POSTER: 'qr-designer-template-poster',
  QR_DESIGNER_NAME_INPUT: 'qr-designer-name-input',
  QR_DESIGNER_TAGLINE_INPUT: 'qr-designer-tagline-input',
  QR_DESIGNER_CTA_INPUT: 'qr-designer-cta-input',
  QR_DESIGNER_FG_COLOR_INPUT: 'qr-designer-fg-color-input',
  QR_DESIGNER_BG_COLOR_INPUT: 'qr-designer-bg-color-input',
  QR_DESIGNER_ACCENT_INPUT: 'qr-designer-accent-input',
  QR_DESIGNER_DOWNLOAD_PNG: 'qr-designer-download-png',
  QR_DESIGNER_DOWNLOAD_SVG: 'qr-designer-download-svg',
  QR_DESIGNER_DOWNLOAD_PDF: 'qr-designer-download-pdf',
  MENU_CARD_DESIGN_QR_BUTTON: 'menu-card-design-qr-button',

  // Variant Groups
  VARIANT_GROUP_SECTION: 'variant-group-section',
  VARIANT_GROUP_ADD_BUTTON: 'variant-group-add-button',
  VARIANT_GROUP_NAME_INPUT: 'variant-group-name-input',
  VARIANT_GROUP_DELETE_BUTTON: 'variant-group-delete-button',
  VARIANT_GROUP_REQUIRED_TOGGLE: 'variant-group-required-toggle',
  VARIANT_ADD_BUTTON: 'variant-add-button',
  VARIANT_NAME_INPUT: 'variant-name-input',
  VARIANT_PRICE_INPUT: 'variant-price-input',
  VARIANT_DELETE_BUTTON: 'variant-delete-button',
  VARIANT_AVAILABLE_TOGGLE: 'variant-available-toggle',

  // Dietary Tags
  DIETARY_TAG_SELECTOR: 'dietary-tag-selector',
  DIETARY_TAG_SELECTOR_CHIP: 'dietary-tag-selector-chip',
  DIETARY_TAG_BADGE: 'dietary-tag-badge',
  DIETARY_TAG_FILTER: 'dietary-tag-filter',
  DIETARY_TAG_FILTER_CHIP: 'dietary-tag-filter-chip',
  DIETARY_TAG_FILTER_CLEAR: 'dietary-tag-filter-clear',
} as const;
