/**
 * Test IDs for styling editors (color scheme, typography, price style,
 * media position, box style, header, spacing), notifications, content upload,
 * and native forms showcase.
 * Split from testIds.ts to keep file sizes under 200 lines.
 */

export const StylingTestIds = {
  // Notifications
  NOTIFICATION_BELL: 'notification-bell',
  NOTIFICATION_BELL_BADGE: 'notification-bell-badge',
  NOTIFICATION_SCREEN: 'notification-screen',
  NOTIFICATION_LIST: 'notification-list',
  NOTIFICATION_ITEM: 'notification-item',
  NOTIFICATION_MARK_ALL_READ: 'notification-mark-all-read',
  NOTIFICATION_EMPTY_STATE: 'notification-empty-state',
  NOTIFICATION_CONNECTION_STATUS: 'notification-connection-status',
  NOTIFICATION_TOAST_CONTAINER: 'notification-toast-container',
  NOTIFICATION_TOAST: 'notification-toast',
  NOTIFICATION_TOAST_DISMISS: 'notification-toast-dismiss',
  NOTIFICATION_PERMISSION_BANNER: 'notification-permission-banner',
  NOTIFICATION_PERMISSION_ENABLE_BUTTON: 'notification-permission-enable-button',
  NOTIFICATION_PERMISSION_LATER_BUTTON: 'notification-permission-later-button',

  // Notification Preferences
  NOTIFICATION_PREFERENCES_SCREEN: 'notification-preferences-screen',
  NOTIFICATION_PREFERENCES_ERROR: 'notification-preferences-error',
  NOTIFICATION_PREFERENCES_SAVE_BUTTON: 'notification-preferences-save-button',
  NOTIFICATION_PREFERENCE_DROPDOWN: 'notification-preference-dropdown',
  NOTIFICATION_SETTINGS_BUTTON: 'notification-settings-button',

  // Content Upload Components
  CONTENT_UPLOADER: 'content-uploader',
  CONTENT_UPLOADER_BUTTON: 'content-uploader-button',
  CONTENT_UPLOADER_ERROR: 'content-uploader-error',
  CONTENT_PREVIEW: 'content-preview',
  CONTENT_PREVIEW_IMAGE: 'content-preview-image',
  CONTENT_PREVIEW_VIDEO_THUMBNAIL: 'content-preview-video-thumbnail',
  CONTENT_PREVIEW_DOCUMENT: 'content-preview-document',
  CONTENT_PREVIEW_DELETE_BUTTON: 'content-preview-delete-button',
  UPLOAD_PROGRESS_CONTAINER: 'upload-progress-container',
  UPLOAD_PROGRESS_FILE_NAME: 'upload-progress-file-name',
  UPLOAD_PROGRESS_BAR: 'upload-progress-bar',
  UPLOAD_PROGRESS_CANCEL_BUTTON: 'upload-progress-cancel-button',
  IMAGE_PICKER: 'image-picker',
  VIDEO_PICKER: 'video-picker',
  DOCUMENT_PICKER: 'document-picker',
  CONTENT_IMAGE: 'content-image',
  CONTENT_IMAGE_CATEGORY: 'content-image-category',
  CONTENT_IMAGE_MENU_ITEM: 'content-image-menu-item',
  CONTENT_VIDEO: 'content-video',
  CONTENT_VIDEO_CATEGORY: 'content-video-category',
  CONTENT_VIDEO_MENU_ITEM: 'content-video-menu-item',

  // Color Scheme Editor
  COLOR_SCHEME_EDITOR: 'color-scheme-editor',
  COLOR_SCHEME_INPUT: 'color-scheme-input',
  COLOR_SCHEME_INPUT_ROW: 'color-scheme-input-row',
  COLOR_SCHEME_SWATCH: 'color-scheme-swatch',
  COLOR_SCHEME_PRESET: 'color-scheme-preset',
  COLOR_SCHEME_RESET_BUTTON: 'color-scheme-reset-button',

  // Typography Editor
  TYPOGRAPHY_EDITOR: 'typography-editor',
  TYPOGRAPHY_SECTION: 'typography-section',
  TYPOGRAPHY_FONT_PICKER: 'typography-font-picker',
  TYPOGRAPHY_SIZE_INPUT: 'typography-size-input',
  TYPOGRAPHY_WEIGHT_PICKER: 'typography-weight-picker',
  TYPOGRAPHY_PREVIEW: 'typography-preview',
  TYPOGRAPHY_RESET_BUTTON: 'typography-reset-button',

  // Price Style Editor
  PRICE_STYLE_EDITOR: 'price-style-editor',
  PRICE_STYLE_FONT_SIZE_SLIDER: 'price-style-font-size-slider',
  PRICE_STYLE_FONT_WEIGHT_DROPDOWN: 'price-style-font-weight-dropdown',
  PRICE_STYLE_COLOR_INPUT: 'price-style-color-input',
  PRICE_STYLE_COLOR_SWATCH: 'price-style-color-swatch',
  PRICE_STYLE_CURRENCY_POSITION_BEFORE: 'price-style-currency-position-before',
  PRICE_STYLE_CURRENCY_POSITION_AFTER: 'price-style-currency-position-after',
  PRICE_STYLE_SHOW_CURRENCY_TOGGLE: 'price-style-show-currency-toggle',
  PRICE_STYLE_STRIKETHROUGH_TOGGLE: 'price-style-strikethrough-toggle',
  PRICE_STYLE_PREVIEW: 'price-style-preview',

  // Media Position Editor
  MEDIA_POSITION_EDITOR: 'media-position-editor',
  MEDIA_POSITION_BUTTON: 'media-position-button',
  MEDIA_SIZE_BUTTON: 'media-size-button',
  MEDIA_FIT_BUTTON: 'media-fit-button',
  MEDIA_BORDER_RADIUS_SLIDER: 'media-border-radius-slider',
  MEDIA_SHOW_TOGGLE: 'media-show-toggle',
  MEDIA_PREVIEW: 'media-preview',

  // Box Style Editor
  BOX_STYLE_EDITOR: 'box-style-editor',
  BOX_STYLE_PREVIEW: 'box-style-preview',
  BOX_STYLE_BACKGROUND_COLOR_INPUT: 'box-style-background-color-input',
  BOX_STYLE_BACKGROUND_COLOR_SWATCH: 'box-style-background-color-swatch',
  BOX_STYLE_BORDER_COLOR_INPUT: 'box-style-border-color-input',
  BOX_STYLE_BORDER_COLOR_SWATCH: 'box-style-border-color-swatch',
  BOX_STYLE_BORDER_WIDTH_SLIDER: 'box-style-border-width-slider',
  BOX_STYLE_BORDER_WIDTH_DECREASE: 'box-style-border-width-decrease',
  BOX_STYLE_BORDER_WIDTH_INCREASE: 'box-style-border-width-increase',
  BOX_STYLE_BORDER_RADIUS_SLIDER: 'box-style-border-radius-slider',
  BOX_STYLE_BORDER_RADIUS_DECREASE: 'box-style-border-radius-decrease',
  BOX_STYLE_BORDER_RADIUS_INCREASE: 'box-style-border-radius-increase',
  BOX_STYLE_PADDING_SLIDER: 'box-style-padding-slider',
  BOX_STYLE_PADDING_DECREASE: 'box-style-padding-decrease',
  BOX_STYLE_PADDING_INCREASE: 'box-style-padding-increase',
  BOX_STYLE_SHADOW_TOGGLE: 'box-style-shadow-toggle',

  // Header Editor
  HEADER_EDITOR: 'header-editor',
  HEADER_EDITOR_PREVIEW: 'header-editor-preview',
  HEADER_EDITOR_SHOW_LOGO_TOGGLE: 'header-editor-show-logo-toggle',
  HEADER_EDITOR_LOGO_POSITION_LEFT: 'header-editor-logo-position-left',
  HEADER_EDITOR_LOGO_POSITION_CENTER: 'header-editor-logo-position-center',
  HEADER_EDITOR_LOGO_POSITION_RIGHT: 'header-editor-logo-position-right',
  HEADER_EDITOR_LOGO_SIZE_SMALL: 'header-editor-logo-size-small',
  HEADER_EDITOR_LOGO_SIZE_MEDIUM: 'header-editor-logo-size-medium',
  HEADER_EDITOR_LOGO_SIZE_LARGE: 'header-editor-logo-size-large',
  HEADER_EDITOR_BANNER_HEIGHT_SLIDER: 'header-editor-banner-height-slider',
  HEADER_EDITOR_SHOW_MENU_NAME_TOGGLE: 'header-editor-show-menu-name-toggle',
  HEADER_EDITOR_SHOW_MENU_DESCRIPTION_TOGGLE: 'header-editor-show-menu-description-toggle',
  HEADER_EDITOR_TITLE_POSITION_LEFT: 'header-editor-title-position-left',
  HEADER_EDITOR_TITLE_POSITION_CENTER: 'header-editor-title-position-center',
  HEADER_EDITOR_TITLE_POSITION_RIGHT: 'header-editor-title-position-right',

  // Global Styling Tab
  GLOBAL_STYLING_TAB: 'global-styling-tab',
  GLOBAL_STYLING_TAB_LAYOUT: 'global-styling-tab-layout',
  GLOBAL_STYLING_TAB_COLORS: 'global-styling-tab-colors',
  GLOBAL_STYLING_TAB_TYPOGRAPHY: 'global-styling-tab-typography',
  GLOBAL_STYLING_TAB_MEDIA: 'global-styling-tab-media',
  GLOBAL_STYLING_TAB_HEADER: 'global-styling-tab-header',
  GLOBAL_STYLING_TAB_SPACING: 'global-styling-tab-spacing',
  GLOBAL_STYLING_SECTION_HEADER: 'global-styling-section-header',
  GLOBAL_STYLING_SECTION_CONTENT: 'global-styling-section-content',

  // Spacing Settings Editor
  SPACING_EDITOR: 'spacing-editor',
  SPACING_PAGE_PADDING_SLIDER: 'spacing-page-padding-slider',
  SPACING_CATEGORY_SPACING_SLIDER: 'spacing-category-spacing-slider',
  SPACING_ITEM_SPACING_SLIDER: 'spacing-item-spacing-slider',
  SPACING_CONTENT_PADDING_SLIDER: 'spacing-content-padding-slider',

  // Native Forms Showcase
  NATIVE_FORMS_PAGE: 'native-forms-page',
  SHOWCASE_LOGIN_EMAIL: 'showcase-login-email',
  SHOWCASE_LOGIN_PASSWORD: 'showcase-login-password',
  SHOWCASE_LOGIN_PASSWORD_TOGGLE: 'showcase-login-password-toggle',
  SHOWCASE_LOGIN_REMEMBER: 'showcase-login-remember',
  SHOWCASE_LOGIN_SUBMIT: 'showcase-login-submit',
  SHOWCASE_REGISTER_NAME: 'showcase-register-name',
  SHOWCASE_REGISTER_EMAIL: 'showcase-register-email',
  SHOWCASE_REGISTER_PASSWORD: 'showcase-register-password',
  SHOWCASE_REGISTER_CONFIRM_PASSWORD: 'showcase-register-confirm-password',
  SHOWCASE_REGISTER_SUBMIT: 'showcase-register-submit',
  SHOWCASE_CONTACT_NAME: 'showcase-contact-name',
  SHOWCASE_CONTACT_EMAIL: 'showcase-contact-email',
  SHOWCASE_CONTACT_SUBJECT: 'showcase-contact-subject',
  SHOWCASE_CONTACT_MESSAGE: 'showcase-contact-message',
  SHOWCASE_CONTACT_SUBMIT: 'showcase-contact-submit',
  SHOWCASE_NEWSLETTER_EMAIL: 'showcase-newsletter-email',
  SHOWCASE_NEWSLETTER_SUBMIT: 'showcase-newsletter-submit',

  // Tenant Theme Editor
  TENANT_THEME_EDITOR_SCREEN: 'tenant-theme-editor-screen',
  TENANT_THEME_EDITOR_LOADING: 'tenant-theme-editor-loading',
  TENANT_THEME_EDITOR_SAVE: 'tenant-theme-editor-save',
  TENANT_THEME_EDITOR_RESET: 'tenant-theme-editor-reset',
  TENANT_THEME_COLOR_PRIMARY: 'tenant-theme-color-primary',
  TENANT_THEME_COLOR_SECONDARY: 'tenant-theme-color-secondary',
  TENANT_THEME_COLOR_ACCENT: 'tenant-theme-color-accent',
  TENANT_THEME_PREVIEW: 'tenant-theme-preview',
  TENANT_THEME_TYPOGRAPHY_SCALE: 'tenant-theme-typography-scale',

  // Theme Settings
  THEME_SETTINGS_SCREEN: 'theme-settings-screen',
  THEME_SETTINGS_LOADING: 'theme-settings-loading',
  THEME_SWATCH_PRIMARY: 'theme-swatch-primary',
  THEME_SWATCH_SECONDARY: 'theme-swatch-secondary',
  THEME_SWATCH_ACCENT: 'theme-swatch-accent',
  THEME_LOGO_PREVIEW: 'theme-logo-preview',
  THEME_MODE_LIGHT: 'theme-mode-light',
  THEME_MODE_DARK: 'theme-mode-dark',
  THEME_CUSTOMIZE_BUTTON: 'theme-customize-button',
  THEME_RESET_BUTTON: 'theme-reset-button',
  THEME_COLOR_PICKER: 'theme-color-picker',
  THEME_COLOR_SCALE: 'theme-color-scale',
  THEME_MODE_OVERRIDES: 'theme-mode-overrides',
  THEME_BRANDING_UPLOAD: 'theme-branding-upload',
  THEME_LIVE_PREVIEW: 'theme-live-preview',

  // Native Components Showcase
  NATIVE_COMPONENTS_PAGE: 'native-components-page',
  NATIVE_CHECKBOX_CHECKED: 'native-checkbox-checked',
  NATIVE_CHECKBOX_UNCHECKED: 'native-checkbox-unchecked',
  NATIVE_CHECKBOX_DISABLED: 'native-checkbox-disabled',
  NATIVE_CHECKBOX_INDETERMINATE: 'native-checkbox-indeterminate',

  // Image Crop Modal
  CROP_MODAL: 'crop-modal',
  CROP_MODAL_APPLY: 'crop-modal-apply',
  CROP_MODAL_CANCEL: 'crop-modal-cancel',
  CROP_MODAL_ZOOM_SLIDER: 'crop-modal-zoom-slider',
  CROP_ASPECT_SQUARE: 'crop-aspect-square',
  CROP_ASPECT_LANDSCAPE: 'crop-aspect-landscape',
  CROP_ASPECT_CLASSIC: 'crop-aspect-classic',
  CROP_ASPECT_FREE: 'crop-aspect-free',

  // Products Showcase Pages
  STUDIO_NATIVE_PRODUCTS_PAGE: 'native-products-page',
  STUDIO_NATIVE_PRODUCTS_GRID: 'native-products-grid',
  STUDIO_PRODUCTS_GRID: 'products-grid',
  STUDIO_PRODUCTS_CATEGORY_FILTER: 'products-category-filter',
  STUDIO_BTN_RETRY: 'btn-retry',
} as const;
