import React, { useCallback, useEffect, useState } from 'react';

import { ActivityIndicator, ScrollView, StyleSheet, Text, View } from 'react-native';

import { useQueryClient } from '@tanstack/react-query';

import AddressSection from './AddressSection';
import BusinessInfoSection from './BusinessInfoSection';
import ContactInfoSection from './ContactInfoSection';
import OperatingHoursSection from './OperatingHoursSection';
import { notifyError, notifySuccess } from '../../../../lib/notifications';
import { FM } from '../../../../localization/helpers';
import {
  getIdentityServiceAPIMeGetBusinessProfileQueryKey,
  useIdentityServiceAPIMeGetBusinessProfile,
  useIdentityServiceAPIMeUpdateBusinessProfile,
} from '../../../../server/autoGeneratedHooks/identity/me/me';
import { TestIds } from '../../../../shared/testIds';
import { useTheme } from '../../../../theme/hooks/useTheme';
import { isValueDefined } from '../../../../utils/is';
import { Button } from '../../../core/Button';
import ButtonVariant from '../../../core/Button/utils/ButtonVariant';
import Breadcrumb from '../../../Shared/Breadcrumb';
import Heading from '../../../Shared/Heading';
import { BODY_FONT_SIZE, ERROR_TEXT_MARGIN_TOP, SECTION_SPACING } from '../constants';
import { useOperatingHours } from '../hooks/useOperatingHours';
import { buildRequestData } from '../utils/buildRequestData';

const styles = StyleSheet.create({
  container: { flex: 1 },
  scrollContent: { padding: SECTION_SPACING },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  errorText: { fontSize: BODY_FONT_SIZE, textAlign: 'center', marginTop: ERROR_TEXT_MARGIN_TOP },
  sectionGap: { marginTop: SECTION_SPACING },
  buttonSpacing: { marginTop: SECTION_SPACING },
});

const BusinessProfileSettingsScreen = (): React.ReactElement => {
  const { data: profile, isLoading, isError } = useIdentityServiceAPIMeGetBusinessProfile();
  const updateProfile = useIdentityServiceAPIMeUpdateBusinessProfile();
  const queryClient = useQueryClient();

  const { theme } = useTheme();
  const { colors } = theme;
  const primary = theme.palette.primary['500'];
  const errorColor = theme.semantic.error['500'];

  const [name, setName] = useState('');
  const [description, setDescription] = useState('');
  const [cuisineType, setCuisineType] = useState('');
  const [phone, setPhone] = useState('');
  const [email, setEmail] = useState('');
  const [website, setWebsite] = useState('');
  const [addressLine1, setAddressLine1] = useState('');
  const [addressLine2, setAddressLine2] = useState('');
  const [city, setCity] = useState('');
  const [state, setState] = useState('');
  const [postalCode, setPostalCode] = useState('');
  const [country, setCountry] = useState('');

  const operatingHours = useOperatingHours(profile?.operatingHoursJson);

  useEffect(() => {
    if (isValueDefined(profile)) {
      setName(profile.name ?? '');
      setDescription(profile.description ?? '');
      setCuisineType(profile.cuisineType ?? '');
      setPhone(profile.phone ?? '');
      setEmail(profile.email ?? '');
      setWebsite(profile.website ?? '');
      setAddressLine1(profile.addressLine1 ?? '');
      setAddressLine2(profile.addressLine2 ?? '');
      setCity(profile.city ?? '');
      setState(profile.state ?? '');
      setPostalCode(profile.postalCode ?? '');
      setCountry(profile.country ?? '');
    }
  }, [profile]);

  const handleSave = useCallback(() => {
    const fields = {
      name, description, cuisineType, phone, email, website,
      addressLine1, addressLine2, city, state, postalCode, country,
    };
    const data = buildRequestData(fields, operatingHours.serialize());

    updateProfile.mutate(
      { data },
      {
        onSuccess: () => {
          queryClient.invalidateQueries({
            queryKey: getIdentityServiceAPIMeGetBusinessProfileQueryKey(),
          }).catch(() => {});
          notifySuccess(FM('settings.businessProfile.messages.saveSuccess'));
        },
        onError: () => {
          notifyError(FM('settings.businessProfile.messages.saveError'));
        },
      },
    );
  }, [
    name, description, cuisineType, phone, email, website,
    addressLine1, addressLine2, city, state, postalCode, country,
    operatingHours, updateProfile, queryClient,
  ]);

  if (isLoading)
    return (
      <View style={styles.loadingContainer} testID={TestIds.BUSINESS_PROFILE_LOADING}>
        <ActivityIndicator color={primary} size="large" />
        <Text style={[styles.errorText, { color: colors.textSecondary }]}>{FM('loading')}</Text>
      </View>
    );

  if (isError)
    return (
      <View style={styles.loadingContainer} testID={TestIds.BUSINESS_PROFILE_ERROR}>
        <Text style={[styles.errorText, { color: errorColor }]}>
          {FM('settings.businessProfile.messages.loadError')}
        </Text>
      </View>
    );

  const isSaving = updateProfile.isPending;
  const saveLabel = isSaving ? FM('common.saving') : FM('settings.businessProfile.save');

  return (
    <View
      style={[styles.container, { backgroundColor: colors.background }]}
      testID={TestIds.BUSINESS_PROFILE_SCREEN}
    >
      <ScrollView contentContainerStyle={styles.scrollContent}>
        <Breadcrumb />
        <Heading>{FM('settings.businessProfile.title')}</Heading>

        <BusinessInfoSection
          cuisineType={cuisineType}
          description={description}
          name={name}
          onCuisineTypeChange={setCuisineType}
          onDescriptionChange={setDescription}
          onNameChange={setName}
        />

        <View style={styles.sectionGap}>
          <ContactInfoSection
            email={email}
            phone={phone}
            website={website}
            onEmailChange={setEmail}
            onPhoneChange={setPhone}
            onWebsiteChange={setWebsite}
          />
        </View>

        <View style={styles.sectionGap}>
          <AddressSection
            addressLine1={addressLine1}
            addressLine2={addressLine2}
            city={city}
            country={country}
            postalCode={postalCode}
            state={state}
            onAddressLine1Change={setAddressLine1}
            onAddressLine2Change={setAddressLine2}
            onCityChange={setCity}
            onCountryChange={setCountry}
            onPostalCodeChange={setPostalCode}
            onStateChange={setState}
          />
        </View>

        <View style={styles.sectionGap}>
          <OperatingHoursSection
            hours={operatingHours.hours}
            onCloseTimeChange={operatingHours.updateCloseTime}
            onOpenTimeChange={operatingHours.updateOpenTime}
            onToggleClosed={operatingHours.toggleClosed}
          />
        </View>

        <View style={styles.buttonSpacing}>
          <Button
            accessibilityHint={FM('settings.businessProfile.saveHint')}
            accessibilityLabel={FM('settings.businessProfile.save')}
            disabled={isSaving}
            label={saveLabel}
            testID={TestIds.BUSINESS_PROFILE_SAVE_BUTTON}
            variant={ButtonVariant.Primary}
            onPress={handleSave}
          />
        </View>
      </ScrollView>
    </View>
  );
};

export default BusinessProfileSettingsScreen;
