/**
 * Tab bar for the FullMenuEditor.
 * Extracted to keep FullMenuEditor under the file line limit.
 * Scrollable horizontally on phone to prevent overflow on narrow screens.
 */
import React from 'react';

import { ScrollView, StyleSheet, View } from 'react-native';

import { FM } from '@/localization/helpers';
import type { TenantMenusDto } from '@/server/autoGeneratedHooks/onlinemenu/models/tenantMenusDto';
import { TestIds } from '@/shared/testIds';
import { isValueDefined } from '@/utils/is';


import EditorTabButton from './EditorTabButton';
import EditorTab from '../enums/EditorTab';

const TABS_MARGIN_BOTTOM = 16;
const BORDER_BOTTOM_WIDTH = 1;

const styles = StyleSheet.create({
  tabContainer: { flexDirection: 'row', borderBottomWidth: BORDER_BOTTOM_WIDTH, marginBottom: TABS_MARGIN_BOTTOM },
  scrollContent: { flexDirection: 'row' },
});

interface EditorTabsProps {
  activeTab: EditorTab;
  onSetActiveTab: (tab: EditorTab) => void;
  backgroundColor: string;
  inactiveTabBg: string;
  isPhone: boolean;
  item: TenantMenusDto | null;
  primaryColor: string;
  textColor: string;
  borderColor: string;
}

const EditorTabs = ({ activeTab, onSetActiveTab, backgroundColor, inactiveTabBg, isPhone, item, primaryColor, textColor, borderColor }: EditorTabsProps): React.ReactElement => {
  const tabButtons = (
    <>
      <EditorTabButton backgroundColor={backgroundColor} hint={FM('onlineMenus.tab.metadataHint')}
        inactiveTabBg={inactiveTabBg} isActive={activeTab === EditorTab.Metadata} isPhone={isPhone}
        label={FM('onlineMenus.tab.metadata')} primaryColor={primaryColor} testID={TestIds.MENU_TAB_METADATA}
        textColor={textColor} onPress={() => { onSetActiveTab(EditorTab.Metadata); }} />
      <EditorTabButton backgroundColor={backgroundColor} hint={FM('onlineMenus.tab.contentHint')}
        inactiveTabBg={inactiveTabBg} isActive={activeTab === EditorTab.Content} isPhone={isPhone}
        label={FM('onlineMenus.tab.content')} primaryColor={primaryColor} testID={TestIds.MENU_TAB_CONTENT}
        textColor={textColor} onPress={() => { onSetActiveTab(EditorTab.Content); }} />
      <EditorTabButton backgroundColor={backgroundColor} hint={FM('onlineMenus.tab.previewHint')}
        inactiveTabBg={inactiveTabBg} isActive={activeTab === EditorTab.Preview} isPhone={isPhone}
        label={FM('onlineMenus.tab.preview')} primaryColor={primaryColor} testID={TestIds.MENU_TAB_PREVIEW}
        textColor={textColor} onPress={() => { onSetActiveTab(EditorTab.Preview); }} />
      {isValueDefined(item) ? (
        <>
          <EditorTabButton backgroundColor={backgroundColor} hint={FM('translations.tabHint')}
            inactiveTabBg={inactiveTabBg} isActive={activeTab === EditorTab.Translations} isPhone={isPhone}
            label={FM('translations.tabTitle')} primaryColor={primaryColor} testID={TestIds.TRANSLATION_MANAGER_TAB}
            textColor={textColor} onPress={() => { onSetActiveTab(EditorTab.Translations); }} />
          <EditorTabButton backgroundColor={backgroundColor} hint={FM('onlineMenus.versioning.tabHint')}
            inactiveTabBg={inactiveTabBg} isActive={activeTab === EditorTab.History} isPhone={isPhone}
            label={FM('onlineMenus.versioning.tabTitle')} primaryColor={primaryColor} testID={TestIds.VERSION_HISTORY_TAB}
            textColor={textColor} onPress={() => { onSetActiveTab(EditorTab.History); }} />
        </>
      ) : null}
    </>
  );

  if (isPhone)
    return (
      <ScrollView
        horizontal
        contentContainerStyle={styles.scrollContent}
        showsHorizontalScrollIndicator={false}
        style={{ borderBottomWidth: BORDER_BOTTOM_WIDTH, borderBottomColor: borderColor, marginBottom: TABS_MARGIN_BOTTOM }}
      >
        {tabButtons}
      </ScrollView>
    );

  return (
    <View style={[styles.tabContainer, { borderBottomColor: borderColor }]}>
      {tabButtons}
    </View>
  );
};

export default EditorTabs;
