import React, { useCallback, useEffect, useMemo } from 'react';

import { Modal, Text, TouchableOpacity, useWindowDimensions, View } from 'react-native';

import { useSelector } from 'react-redux';

import AutoSaveIndicator from '@/components/OnlineMenus/components/AutoSaveIndicator';
import UndoRedoBar from '@/components/OnlineMenus/components/UndoRedoBar';
import { useBreadcrumbState } from '@/components/OnlineMenus/hooks/useBreadcrumbState';
import { ExportPdfButton } from '@/components/OnlineMenus/PdfExport';
import { applyThemeToMenuContents } from '@/components/OnlineMenus/ThemeSelector';
import type { MenuTheme } from '@/components/OnlineMenus/ThemeSelector';
import BreadcrumbBar from '@/components/Shared/BreadcrumbBar';
import { useTooltipTourContext } from '@/features/tooltipTour/components/TooltipProvider';
import { useBreakpoint } from '@/hooks/useBreakpoint';
import { notify } from '@/lib/notifications';
import { useSubscription } from '@/lib/subscription/hooks/useSubscription';
import { FM } from '@/localization/helpers';
import type { TenantMenusDto } from '@/server/autoGeneratedHooks/onlinemenu/models/tenantMenusDto';
import { useOnlineMenuWebMenuUpdate } from '@/server/autoGeneratedHooks/onlinemenu/tenantmenus/tenantmenus';
import { EDITOR_TWO_PANE_BREAKPOINT_PX } from '@/shared/constants';
import SaveStatus from '@/shared/enums/SaveStatus';
import ThemeMode from '@/shared/enums/ThemeMode';
import TooltipTourId from '@/shared/enums/TooltipTourId';
import { TestIds } from '@/shared/testIds';
import type { RootState } from '@/store/reduxStore';
import { themePalette } from '@/theme/utils/styles';
import type { MenuContents } from '@/types/menuTypes';
import { isValueDefined } from '@/utils/is';

import EditorBody from './EditorBody';
import EditorTabContent from './EditorTabContent';
import EditorTabs from './EditorTabs';
import { deriveEditorColors } from './utils/deriveEditorColors';
import { fullEditorStyles as styles } from './utils/fullMenuEditorStyles';
import EditorTab from '../enums/EditorTab';
import { useAutoSave } from '../hooks/useAutoSave';
import { useFullMenuEditorState } from '../hooks/useFullMenuEditorState';

interface FullMenuEditorProps {
  visible: boolean;
  item: TenantMenusDto | null;
  onSave: (data: { name: string; description?: string | null; contents: MenuContents }) => void;
  onCancel: () => void;
  isSaving: boolean;
}

const FullMenuEditor: React.FC<FullMenuEditorProps> = ({ visible, item, onSave, onCancel, isSaving }) => {
  const theme = useSelector((s: RootState) => s.ui.theme);
  const colors = theme === ThemeMode.Dark ? themePalette.dark : themePalette.light;
  const { isPhone } = useBreakpoint();
  const { width } = useWindowDimensions();
  const isTwoPane = !isPhone && width >= EDITOR_TWO_PANE_BREAKPOINT_PX;
  const { limits } = useSubscription();
  const { startTour, hasSeenTour } = useTooltipTourContext();

  useEffect(() => {
    if (visible && !hasSeenTour(TooltipTourId.Editor)) startTour(TooltipTourId.Editor);
  }, [visible, hasSeenTour, startTour]);

  const {
    activeTab, setActiveTab, name, description, menuContents, nameError, setNameError,
    handleNameChange, handleDescriptionChange, handleMenuContentsChange,
    canUndo, canRedo, undo, redo,
    activeCategoryId, setActiveCategoryId, collapseAllRef,
  } = useFullMenuEditorState(visible, item);

  const updateMutation = useOnlineMenuWebMenuUpdate();
  const autoSaveParams = useMemo(() => ({
    externalId: item?.externalId, name, description, menuContents, updateMutation,
  }), [item?.externalId, name, description, menuContents, updateMutation]);
  const { saveStatus, triggerSave, cancelPendingSave } = useAutoSave(autoSaveParams);

  const handleSave = useCallback(() => {
    if (name.trim() === '') {
      setNameError(FM('onlineMenus.errors.nameRequired'));
      setActiveTab(EditorTab.Metadata);
      return;
    }
    setNameError('');
    // Drop any pending debounced autoSave before the manual save. Without this,
    // a debounce armed by the reopen-with-stale-list-cache cycle can fire ~1.5s
    // later and overwrite the just-saved menu with empty contents.
    cancelPendingSave();
    onSave({ name: name.trim(), description: description.trim() !== '' ? description.trim() : null, contents: menuContents });
  }, [name, description, menuContents, onSave, setNameError, setActiveTab, cancelPendingSave]);

  const handleCancel = useCallback(() => {
    if (isValueDefined(item?.externalId)) triggerSave();
    onCancel();
  }, [onCancel, item?.externalId, triggerSave]);

  const handleMenuRestored = useCallback(() => {
    onCancel();
  }, [onCancel]);

  const handleThemeSelect = useCallback((menuTheme: MenuTheme) => {
    handleMenuContentsChange(applyThemeToMenuContents(menuTheme, menuContents));
  }, [menuContents, handleMenuContentsChange]);

  const handlePremiumThemeBlocked = useCallback(() => {
    notify('info', FM('settings.billing.featureGating.premiumThemeRequired'));
  }, []);

  const handleNavigateToContent = useCallback(() => {
    collapseAllRef.current?.();
    setActiveCategoryId(null);
  }, [collapseAllRef, setActiveCategoryId]);

  const handleNavigateToMetadata = useCallback(() => {
    setActiveTab(EditorTab.Metadata);
  }, [setActiveTab]);

  const breadcrumbParams = useMemo(() => ({
    menuName: name, activeTab, activeCategoryId, categories: menuContents.categories ?? [],
    onNavigateToMenuList: handleCancel, onNavigateToMetadata: handleNavigateToMetadata,
    onNavigateToContent: handleNavigateToContent,
  }), [name, activeTab, activeCategoryId, menuContents.categories, handleCancel, handleNavigateToMetadata, handleNavigateToContent]);
  const breadcrumbs = useBreadcrumbState(breadcrumbParams);

  const { borderColor, textColor, errorColor, successColor, backgroundColor, primaryColor, textOnPrimary, textSecondary, inactiveTabBg } = deriveEditorColors(colors);

  return (
    <Modal transparent animationType="fade" testID={TestIds.MENU_EDITOR} visible={visible} onRequestClose={handleCancel}>
      <View style={[styles.overlay, isPhone ? styles.overlayPhone : undefined]}>
        <View style={[styles.modalContent, isPhone ? styles.modalContentPhone : undefined, { backgroundColor }]}>
          <Text style={[styles.header, { color: textColor }]}>
            {isValueDefined(item) ? FM('onlineMenus.edit') : FM('onlineMenus.create')}
          </Text>

          <BreadcrumbBar crumbs={breadcrumbs} isPhone={isPhone} />

          <EditorTabs activeTab={activeTab} backgroundColor={backgroundColor}
            borderColor={borderColor} inactiveTabBg={inactiveTabBg} isPhone={isPhone}
            item={item} primaryColor={primaryColor}
            textColor={textColor} onSetActiveTab={setActiveTab} />

          <View style={[styles.toolbarRow, isPhone ? styles.toolbarRowPhone : undefined]}>
            <UndoRedoBar borderColor={borderColor} canRedo={canRedo} canUndo={canUndo}
              textColor={textColor} onRedo={redo} onUndo={undo} />
            <ExportPdfButton borderColor={borderColor} contents={menuContents}
              menuName={name} restaurantName="" textColor={textColor} />
            <AutoSaveIndicator errorColor={errorColor} saveStatus={saveStatus}
              successColor={successColor} textColor={textColor} />
          </View>

          <EditorBody
            borderColor={borderColor} description={description} isTwoPane={isTwoPane}
            menuContents={menuContents} name={name} textColor={textColor}
          >
            <EditorTabContent
              activeTab={activeTab} backgroundColor={backgroundColor} borderColor={borderColor}
              collapseAllRef={collapseAllRef} description={description} errorColor={errorColor}
              hasPremiumThemes={limits.hasPremiumThemes} item={item} menuContents={menuContents}
              name={name} nameError={nameError} primaryColor={primaryColor}
              setNameError={setNameError} textColor={textColor} textSecondary={textSecondary}
              onCategoryFocus={setActiveCategoryId}
              onDescriptionChange={handleDescriptionChange} onMenuContentsChange={handleMenuContentsChange}
              onMenuRestored={handleMenuRestored} onNameChange={handleNameChange}
              onPremiumThemeBlocked={handlePremiumThemeBlocked}
              onThemeSelect={handleThemeSelect}
            />
          </EditorBody>

          <View style={[styles.buttonRow, isPhone ? styles.buttonRowPhone : undefined, { borderTopColor: borderColor }]}>
            <TouchableOpacity
              accessibilityHint={FM('onlineMenus.cancelHint')} accessibilityLabel={FM('onlineMenus.cancel')}
              accessibilityRole="button" disabled={isSaving}
              style={[styles.button, isPhone ? styles.buttonPhone : undefined, { backgroundColor: borderColor }]}
              testID={TestIds.MENU_EDITOR_CANCEL_BUTTON} onPress={handleCancel}
            >
              <Text style={[styles.buttonText, { color: textColor }]}>{FM('onlineMenus.cancel')}</Text>
            </TouchableOpacity>
            <TouchableOpacity
              accessibilityHint={FM('onlineMenus.saveHint')} accessibilityLabel={FM('onlineMenus.save')}
              accessibilityRole="button" disabled={isSaving || saveStatus === SaveStatus.Saving}
              style={[styles.button, isPhone ? styles.buttonPhone : undefined, { backgroundColor: primaryColor }]}
              testID={TestIds.MENU_EDITOR_SAVE_BUTTON} onPress={handleSave}
            >
              <Text style={[styles.buttonText, { color: textOnPrimary }]}>
                {isSaving ? FM('loading') : FM('onlineMenus.save')}
              </Text>
            </TouchableOpacity>
          </View>
        </View>
      </View>
    </Modal>
  );
};

export default FullMenuEditor;
