import React from 'react';

import { fireEvent, render } from '@testing-library/react-native';

import type { TenantMenusDto } from '@/server/autoGeneratedHooks/onlinemenu/models/tenantMenusDto';

import MenuEditorModal from './MenuEditorModal';


// Mock dependencies
jest.mock('react-redux', () => ({
  useSelector: () => 'light',
}));

const NAME_PLACEHOLDER = 'e.g., Weekend Brunch Menu';
const DESCRIPTION_PLACEHOLDER = 'e.g., Our signature brunch served every Saturday and Sunday';

describe('MenuEditorModal', () => {
  const mockOnSave = jest.fn();
  const mockOnCancel = jest.fn();

  const defaultProps = {
    visible: true,
    item: null,
    onSave: mockOnSave,
    onCancel: mockOnCancel,
    isSaving: false,
  };

  beforeEach(() => {
    jest.clearAllMocks();
  });

  it('calls onSave with name and description when save button is pressed', () => {
    const { getByPlaceholderText, getByText } = render(<MenuEditorModal {...defaultProps} />);

    const nameInput = getByPlaceholderText(NAME_PLACEHOLDER);
    const descriptionInput = getByPlaceholderText(DESCRIPTION_PLACEHOLDER);
    const saveButton = getByText('Save');

    fireEvent.changeText(nameInput, 'Dinner Menu');
    fireEvent.changeText(descriptionInput, 'Evening dining options');
    fireEvent.press(saveButton);

    expect(mockOnSave).toHaveBeenCalledWith({
      name: 'Dinner Menu',
      description: 'Evening dining options',
    });
  });

  it('calls onSave with null description when description is empty', () => {
    const { getByPlaceholderText, getByText } = render(<MenuEditorModal {...defaultProps} />);

    const nameInput = getByPlaceholderText(NAME_PLACEHOLDER);
    const saveButton = getByText('Save');

    fireEvent.changeText(nameInput, 'Lunch Menu');
    fireEvent.press(saveButton);

    expect(mockOnSave).toHaveBeenCalledWith({
      name: 'Lunch Menu',
      description: null,
    });
  });

  it('does not call onSave when name is empty', () => {
    const { getByText } = render(<MenuEditorModal {...defaultProps} />);

    const saveButton = getByText('Save');
    fireEvent.press(saveButton);

    expect(mockOnSave).not.toHaveBeenCalled();
  });

  it('trims whitespace from name and description', () => {
    const { getByPlaceholderText, getByText } = render(<MenuEditorModal {...defaultProps} />);

    const nameInput = getByPlaceholderText(NAME_PLACEHOLDER);
    const descriptionInput = getByPlaceholderText(DESCRIPTION_PLACEHOLDER);
    const saveButton = getByText('Save');

    fireEvent.changeText(nameInput, '  Breakfast Menu  ');
    fireEvent.changeText(descriptionInput, '  Morning options  ');
    fireEvent.press(saveButton);

    expect(mockOnSave).toHaveBeenCalledWith({
      name: 'Breakfast Menu',
      description: 'Morning options',
    });
  });

  it('initializes form with existing item data when editing', () => {
    const existingMenu: Partial<TenantMenusDto> = {
      externalId: '123',
      name: 'Existing Menu',
      description: 'Existing description',
    };

    const { getByDisplayValue } = render(
      <MenuEditorModal {...defaultProps} item={existingMenu} />,
    );

    expect(getByDisplayValue('Existing Menu')).toBeTruthy();
    expect(getByDisplayValue('Existing description')).toBeTruthy();
  });

  it('calls onCancel when cancel button is pressed', () => {
    const { getByText } = render(<MenuEditorModal {...defaultProps} />);

    const cancelButton = getByText('Cancel');
    fireEvent.press(cancelButton);

    expect(mockOnCancel).toHaveBeenCalledTimes(1);
  });

  it('clears error when user starts typing in name field', () => {
    const { getByPlaceholderText, getByText, queryByText } = render(
      <MenuEditorModal {...defaultProps} />,
    );

    const saveButton = getByText('Save');
    fireEvent.press(saveButton);

    // Error should be shown
    expect(queryByText('Name is required')).toBeTruthy();

    const nameInput = getByPlaceholderText(NAME_PLACEHOLDER);
    fireEvent.changeText(nameInput, 'New Menu');

    // Error should be cleared
    expect(queryByText('Name is required')).toBeNull();
  });

  it('shows loading text when isSaving is true', () => {
    const { getByText, queryByText } = render(<MenuEditorModal {...defaultProps} isSaving />);

    // Save button text changes to "Loading..."
    expect(getByText('Loading...')).toBeTruthy();
    expect(queryByText('Save')).toBeNull();

    // Cancel button should still be visible
    expect(getByText('Cancel')).toBeTruthy();
  });
});
