import React, { useCallback, useEffect, useState } from 'react';

import { Modal, ScrollView, Text, TextInput, TouchableOpacity, View } from 'react-native';

import { useSelector } from 'react-redux';

import { styles } from '@/components/OnlineMenus/MenuEditorModalStyles';
import { useBreakpoint } from '@/hooks/useBreakpoint';
import { FM } from '@/localization/helpers';
import type { TenantMenusDto } from '@/server/autoGeneratedHooks/onlinemenu/models/tenantMenusDto';
import ThemeMode from '@/shared/enums/ThemeMode';
import { TestIds } from '@/shared/testIds';
import type { RootState } from '@/store/reduxStore';
import { themePalette } from '@/theme/utils/styles';
import { isValueDefined } from '@/utils/is';

interface MenuEditorModalProps {
  visible: boolean;
  item: TenantMenusDto | null;
  onSave: (data: { name: string; description?: string | null }) => void;
  onCancel: () => void;
  isSaving: boolean;
}

const MenuEditorModal: React.FC<MenuEditorModalProps> = ({ visible, item, onSave, onCancel, isSaving }) => {
  const theme = useSelector((s: RootState) => s.ui.theme);
  const colors = theme === ThemeMode.Dark ? themePalette.dark : themePalette.light;
  const { isPhone } = useBreakpoint();

  const [name, setName] = useState('');
  const [description, setDescription] = useState('');
  const [nameError, setNameError] = useState('');

  useEffect(() => {
    if (visible) {
      setName(item?.name ?? '');
      setDescription(item?.description ?? '');
      setNameError('');
    }
  }, [visible, item]);

  const handleSave = useCallback(() => {
    if (name.trim() === '') {
      setNameError(FM('onlineMenus.errors.nameRequired'));
      return;
    }
    setNameError('');
    onSave({
      name: name.trim(),
      description: description.trim() !== '' ? description.trim() : null,
    });
  }, [name, description, onSave]);

  const handleCancel = useCallback(() => {
    setName('');
    setDescription('');
    setNameError('');
    onCancel();
  }, [onCancel]);

  const borderColor = String(colors.border) !== '' ? String(colors.border) : '#ccc';
  const textColor = String(colors.text);
  const errorColor = String(colors.error);
  const backgroundColor = String(colors.surface);
  const primaryColor = String(colors.primary);
  const textOnPrimary = String(colors.textOnPrimary);
  const textSecondary = String(colors.textSecondary);

  const headerText = isValueDefined(item)
    ? FM('onlineMenus.edit')
    : FM('onlineMenus.create');

  const handleNameChange = (text: string): void => {
    setName(text);
    if (nameError !== '') setNameError('');
  };

  return (
    <Modal
      transparent
      animationType="fade"
      testID={TestIds.MENU_EDITOR}
      visible={visible}
      onRequestClose={handleCancel}
    >
      <View style={[styles.overlay, isPhone ? styles.overlayPhone : undefined]}>
        <View
          accessibilityViewIsModal
          aria-label={headerText}
          role="dialog"
          style={[styles.modalContent, isPhone ? styles.modalContentPhone : undefined, { backgroundColor }]}
        >
          <ScrollView showsVerticalScrollIndicator={false}>
            <Text style={[styles.header, { color: textColor }]}>{headerText}</Text>

            <Text style={[styles.label, { color: textColor }]}>{FM('onlineMenus.nameLabel')} *</Text>
            <TextInput
              accessibilityHint={FM('onlineMenus.menuNameHint')}
              accessibilityLabel={FM('onlineMenus.menuNameLabel')}
              placeholder={FM('onlineMenus.namePlaceholder')}
              placeholderTextColor={textSecondary}
              style={[styles.input, { borderColor, color: textColor, backgroundColor }]}
              testID={TestIds.MENU_EDITOR_NAME_INPUT}
              value={name}
              onChangeText={handleNameChange}
            />
            {nameError !== '' ? <Text style={[styles.errorText, { color: errorColor }]}>{nameError}</Text> : null}

            <Text style={[styles.label, { color: textColor }]}>
              {FM('onlineMenus.descriptionLabel')}
            </Text>
            <TextInput
              multiline
              accessibilityHint={FM('onlineMenus.menuDescriptionHint')}
              accessibilityLabel={FM('onlineMenus.menuDescriptionLabel')}
              numberOfLines={4}
              placeholder={FM('onlineMenus.descriptionPlaceholder')}
              placeholderTextColor={textSecondary}
              style={[styles.input, styles.textArea, { borderColor, color: textColor, backgroundColor }]}
              testID={TestIds.MENU_EDITOR_DESCRIPTION_INPUT}
              value={description}
              onChangeText={setDescription}
            />

            <View style={[styles.buttonRow, isPhone ? styles.buttonRowPhone : undefined]}>
              <TouchableOpacity
                accessibilityHint={FM('onlineMenus.cancelHint')}
                accessibilityLabel={FM('onlineMenus.cancel')}
                accessibilityRole="button"
                disabled={isSaving}
                style={[styles.button, isPhone ? styles.buttonPhone : undefined, { backgroundColor: borderColor }]}
                testID={TestIds.MENU_EDITOR_CANCEL_BUTTON}
                onPress={handleCancel}
              >
                <Text style={[styles.buttonText, { color: textColor }]}>{FM('onlineMenus.cancel')}</Text>
              </TouchableOpacity>

              <TouchableOpacity
                accessibilityHint={FM('onlineMenus.saveHint')}
                accessibilityLabel={FM('onlineMenus.save')}
                accessibilityRole="button"
                disabled={isSaving}
                style={[styles.button, isPhone ? styles.buttonPhone : undefined, { backgroundColor: primaryColor }]}
                testID={TestIds.MENU_EDITOR_SAVE_BUTTON}
                onPress={handleSave}
              >
                <Text style={[styles.buttonText, { color: textOnPrimary }]}>
                  {isSaving ? FM('loading') : FM('onlineMenus.save')}
                </Text>
              </TouchableOpacity>
            </View>
          </ScrollView>
        </View>
      </View>
    </Modal>
  );
};

export default MenuEditorModal;
