/**
 * Converts auto-generated DTO contents to the local MenuContents type.
 * The auto-generated types use `| null` for nullable fields while local types use `| undefined`.
 * This is a known boundary between auto-generated and local types.
 */

import type { TenantMenusDto } from '@/server/autoGeneratedHooks/onlinemenu/models/tenantMenusDto';
import type { MenuContents } from '@/types/menuTypes';
import { isValueDefined } from '@/utils/is';

export function toLocalMenuContents(contents: TenantMenusDto['contents']): MenuContents | undefined {
  if (!isValueDefined(contents)) return undefined;
  // eslint-disable-next-line @typescript-eslint/consistent-type-assertions -- auto-gen to local type boundary: structurally compatible except null vs undefined in nested nullable fields
  return { ...contents, categories: contents.categories ?? [] } as MenuContents;
}
